//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSDK_PBGeneratedMessage.h"

@class GSDK_PBMutableArray;

@interface ACPMeasurementBatch : GSDK_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GSDK_PBMutableArray *bundlesArray; // @dynamic bundlesArray;
@property(nonatomic) _Bool hasBundlesArray; // @dynamic hasBundlesArray;

@end

