//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSDK_PBGeneratedMessage.h"

@class GSDK_PBMutableArray;

@interface ACPResultData : GSDK_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasResultsArray; // @dynamic hasResultsArray;
@property(nonatomic) _Bool hasStatusArray; // @dynamic hasStatusArray;
@property(retain, nonatomic) GSDK_PBMutableArray *resultsArray; // @dynamic resultsArray;
@property(retain, nonatomic) GSDK_PBMutableArray *statusArray; // @dynamic statusArray;

@end

