//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "GADRewardBasedVideoAdDelegate.h"

@class GADBannerView, GADInterstitial, NSString;

@interface AdmobCommunicatorIOS : UIViewController <GADRewardBasedVideoAdDelegate>
{
    NSString *AdmobBannerID;
    NSString *AdmobInterstitialID;
    NSString *AdmobMediation;
    GADInterstitial *interstitial;
    GADBannerView *banner;
}

- (void)createInterstitial;
- (void)createRewardVideo;
- (void)initCommunicator;
- (void)loadRewardVideo;
- (void)offBanner;
- (void)onBanner;
- (void)onInterstitial;
- (void)onRewardVideo;
- (void)rewardBasedVideoAd:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)rewardBasedVideoAd:(id)arg1 didRewardUserWithReward:(id)arg2;
- (void)rewardBasedVideoAdDidClose:(id)arg1;
- (void)rewardBasedVideoAdDidOpen:(id)arg1;
- (void)rewardBasedVideoAdDidReceiveAd:(id)arg1;
- (void)rewardBasedVideoAdDidStartPlaying:(id)arg1;
- (void)rewardBasedVideoAdWillLeaveApplication:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

