//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALAdDisplayDelegate.h"

@class NSString;

@interface ALAdDisplayProxy : NSObject <ALAdDisplayDelegate>
{
    id <ALAdDisplayDelegate> delegate;
}

- (void).cxx_destruct;
- (void)ad:(id)arg1 wasClickedIn:(id)arg2;
- (void)ad:(id)arg1 wasDisplayedIn:(id)arg2;
- (void)ad:(id)arg1 wasHiddenIn:(id)arg2;
@property(retain, nonatomic) id <ALAdDisplayDelegate> delegate; // @synthesize delegate;
- (id)initWithDisplayDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

