//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALAdViewForegroundClickTrackingProtocol.h"
#import "ALAdViewProtocol.h"

@protocol ALAdViewInternalProtocol <ALAdViewProtocol, ALAdViewForegroundClickTrackingProtocol>
@property __weak id <ALAdDisplayDelegate> weakAdDisplayDelegate;
@property __weak id <ALAdLoadDelegate> weakAdLoadDelegate;
@property __weak id <ALInterstitialAdDismissProxy> weakInterstitialDismissalDelegate;
@end

