//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALAdLoadDelegate.h"

@class ALAdLoadState, ALLogManager, ALSdk, NSString;

@interface ALAdServiceLoadProxy : NSObject <ALAdLoadDelegate>
{
    ALSdk *sdk;
    ALAdLoadState *loadState;
    ALLogManager *logger;
}

- (void).cxx_destruct;
- (void)adService:(id)arg1 didFailToLoadAdWithError:(int)arg2;
- (void)adService:(id)arg1 didLoadAd:(id)arg2;
- (id)initWithSdk:(id)arg1 loadState:(id)arg2;
@property(retain, nonatomic) ALAdLoadState *loadState; // @synthesize loadState;
@property(retain, nonatomic) ALLogManager *logger; // @synthesize logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

