//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class ALAdSize, ALAdType;

@interface ALAdSpec : NSObject <NSCopying>
{
    ALAdSize *_size;
    ALAdType *_type;
}

+ (id)specFromAd:(id)arg1;
+ (id)specWithSize:(id)arg1 type:(id)arg2;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)initWithSize:(id)arg1 type:(id)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToSpec:(id)arg1;
@property(retain, nonatomic) ALAdSize *size; // @synthesize size=_size;
@property(retain, nonatomic) ALAdType *type; // @synthesize type=_type;

@end

