//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALClickTrackingOverlayView, NSURL;

@protocol ALAdViewForegroundClickTrackingProtocol <NSObject>
@property _Bool foregroundClickInvalidated;
- (void)removeClickTrackingOverlay;
@property(retain, nonatomic) ALClickTrackingOverlayView *trackingOverlay;

@optional
- (void)showClickTrackingOverlay;
- (void)trackClickInForeground:(NSURL *)arg1;
@end

