//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface ALAdSize : NSObject <NSCopying>
{
    unsigned long long width;
    unsigned long long height;
    NSString *label;
}

+ (id)allSizes;
+ (void)initialize;
+ (id)sizeBanner;
+ (id)sizeInterstitial;
+ (id)sizeLeader;
+ (id)sizeMRec;
+ (id)sizeWithLabel:(id)arg1 orDefault:(id)arg2;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)debugDescription;
- (id)description;
- (unsigned long long)hash;
@property(nonatomic) unsigned long long height; // @synthesize height;
- (id)initWithLabel:(id)arg1;
- (id)initWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToSize:(id)arg1;
@property(readonly, copy, nonatomic) NSString *label; // @synthesize label;
@property(nonatomic) unsigned long long width; // @synthesize width;

@end

