//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALAd, ALAdSize, NSDate, NSMutableArray;

@interface ALAdLoadState : NSObject
{
    _Bool isWaitingForAd;
    NSObject *adLoadLock;
    ALAdSize *size;
    ALAd *loadedAd;
    NSDate *loadedAdExpiration;
    NSMutableArray *pendingAdLoadDelegates;
    NSMutableArray *adUpdateObservers;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSObject *adLoadLock; // @synthesize adLoadLock;
@property(retain, nonatomic) NSMutableArray *adUpdateObservers; // @synthesize adUpdateObservers;
- (id)initWithAdSize:(id)arg1;
@property(nonatomic) _Bool isWaitingForAd; // @synthesize isWaitingForAd;
@property(retain, nonatomic) ALAd *loadedAd; // @synthesize loadedAd;
@property(retain, nonatomic) NSDate *loadedAdExpiration; // @synthesize loadedAdExpiration;
@property(retain, nonatomic) NSMutableArray *pendingAdLoadDelegates; // @synthesize pendingAdLoadDelegates;
@property(retain, nonatomic) ALAdSize *size; // @synthesize size;

@end

