//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALPostbackDelegate.h"

@class ALAd, ALAdService, NSString, UIViewController<ALApplicationControlProtocol>;

@interface ALAdServiceVideoPostbackProxy : NSObject <ALPostbackDelegate>
{
    ALAdService *_adService;
    ALAd *_ad;
    id <ALAdViewForegroundClickTrackingProtocol> _videoView;
    UIViewController<ALApplicationControlProtocol> *_viewController;
}

+ (id)postbackProxyWithAdService:(id)arg1 videoView:(id)arg2 ad:(id)arg3 viewController:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) ALAd *ad; // @synthesize ad=_ad;
@property(nonatomic) __weak ALAdService *adService; // @synthesize adService=_adService;
- (void)clickThrough;
- (void)postbackService:(id)arg1 didExecutePostback:(id)arg2;
- (void)postbackService:(id)arg1 didFailToExecutePostback:(id)arg2 errorCode:(long long)arg3;
@property(retain, nonatomic) id <ALAdViewForegroundClickTrackingProtocol> videoView; // @synthesize videoView=_videoView;
@property(nonatomic) __weak UIViewController<ALApplicationControlProtocol> *viewController; // @synthesize viewController=_viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

