//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALAd, NSNumber;

@protocol ALAdVideoPlaybackDelegate <NSObject>
- (void)videoPlaybackBeganInAd:(ALAd *)arg1;
- (void)videoPlaybackEndedInAd:(ALAd *)arg1 atPlaybackPercent:(NSNumber *)arg2 fullyWatched:(_Bool)arg3;
@end

