//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ALApplicationControlProtocol.h"
#import "ALHtmlAdViewDelegate.h"
#import "ALInterstitialExtendedControlProxy.h"
#import "ALWebViewButtonDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class ALCircularCountdownView, ALCloseButton, ALHtmlAdView, ALIOSAd, ALIncentivizedWarningManager, ALInterstitialAd, ALLogManager, ALSdk, ALVideoPlayer, ALVideoViewControllerClickForwarder, ALWebViewButton, AVPlayer, NSNumber, NSString, UIImageView, UITapGestureRecognizer, UIView;

@interface ALAutoLayoutVideoViewController : UIViewController <UIGestureRecognizerDelegate, ALWebViewButtonDelegate, ALHtmlAdViewDelegate, ALInterstitialExtendedControlProxy, ALApplicationControlProtocol>
{
    _Bool _dismissesOnClick;
    _Bool _wasPlayedToEnd;
    _Bool _statusBarOriginallyHidden;
    _Bool _didEnterBackground;
    _Bool _skippable;
    _Bool _poststitialShown;
    _Bool _usedVideoStream;
    ALIOSAd *_currentAd;
    NSString *_currentPlacement;
    ALSdk *_sdk;
    ALInterstitialAd *_wrapper;
    ALVideoPlayer *_videoPlayer;
    ALCloseButton *_closeButton;
    ALCloseButton *_skipButton;
    ALHtmlAdView *_videoPoststitial;
    ALCircularCountdownView *_countdownClock;
    UIImageView *_muteImageView;
    ALWebViewButton *_videoButton;
    id _countdownTextTimeObserver;
    UITapGestureRecognizer *_closeRecognizer;
    unsigned long long _videoStreamStalledCount;
    unsigned long long _targetInterfaceOrientations;
    double _incentNonVideoAdStartTime;
    ALVideoViewControllerClickForwarder *_clickForwarder;
    ALIncentivizedWarningManager *_incentivizedWarningManager;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <ALAdDisplayDelegate> adDisplayDelegate; // @dynamic adDisplayDelegate;
@property(nonatomic) __weak id <ALAdVideoPlaybackDelegate> adVideoPlaybackDelegate; // @dynamic adVideoPlaybackDelegate;
- (void)addTapHandler:(SEL)arg1 toView:(id)arg2;
- (void)appPaused:(id)arg1;
- (void)appResumed:(id)arg1;
@property(readonly, nonatomic) __weak AVPlayer *avPlayer; // @dynamic avPlayer;
- (void)bringSubviewAboveVideoLayer:(id)arg1;
@property(retain, nonatomic) ALVideoViewControllerClickForwarder *clickForwarder; // @synthesize clickForwarder=_clickForwarder;
- (void)clickThroughFromVideo;
@property(retain, nonatomic) ALCloseButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UITapGestureRecognizer *closeRecognizer; // @synthesize closeRecognizer=_closeRecognizer;
@property(readonly, nonatomic) __weak UIView *containingView; // @dynamic containingView;
@property(retain, nonatomic) ALCircularCountdownView *countdownClock; // @synthesize countdownClock=_countdownClock;
@property(retain, nonatomic) id countdownTextTimeObserver; // @synthesize countdownTextTimeObserver=_countdownTextTimeObserver;
@property(readonly, nonatomic) __weak NSNumber *countdownTime; // @dynamic countdownTime;
- (id)createCountdownTimeObserver;
- (id)createVideoButton;
@property(retain) ALIOSAd *currentAd; // @synthesize currentAd=_currentAd;
@property(copy) NSString *currentPlacement; // @synthesize currentPlacement=_currentPlacement;
@property(nonatomic) _Bool didEnterBackground; // @synthesize didEnterBackground=_didEnterBackground;
- (void)didReceiveClickCommandOnWebViewButton:(id)arg1;
- (void)didReceiveCloseCommandOnHtmlAdView:(id)arg1;
- (void)didReceiveCloseCommandOnWebViewButton:(id)arg1;
- (void)didReceiveSkipCommandOnWebViewButton:(id)arg1;
- (void)dismiss;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
@property _Bool dismissesOnClick; // @synthesize dismissesOnClick=_dismissesOnClick;
- (void)fadeCountdownClockIfNeeded;
- (void)fadeInCloseButton;
- (void)fadeInSkipButton;
- (void)fadeInVideoButton;
- (void)fadeOutSkipButton;
- (void)fadeOutVideoButton;
- (void)fadeVideoButtonIfNeeded;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleExtendedCloseAreaTouch:(id)arg1;
- (void)handleSkipButtonTap;
- (void)handleVideoPlayerError;
- (void)handleVideoTap;
- (void)hidePoststitial;
@property(nonatomic) double incentNonVideoAdStartTime; // @synthesize incentNonVideoAdStartTime=_incentNonVideoAdStartTime;
@property(retain, nonatomic) ALIncentivizedWarningManager *incentivizedWarningManager; // @synthesize incentivizedWarningManager=_incentivizedWarningManager;
- (id)initWithSdk:(id)arg1 currentAd:(id)arg2 currentPlacement:(id)arg3 wrapper:(id)arg4;
@property(readonly, nonatomic, getter=isFullyWatched) _Bool fullyWatched; // @dynamic fullyWatched;
@property(readonly, nonatomic, getter=isIncentivizedAd) _Bool incentivizedAd; // @dynamic incentivizedAd;
@property(readonly, nonatomic, getter=isIncentivizedNonVideoAd) _Bool incentivizedNonVideoAd; // @dynamic incentivizedNonVideoAd;
@property(nonatomic, getter=isSkippable) _Bool skippable; // @synthesize skippable=_skippable;
@property(readonly, nonatomic, getter=isVideoAd) _Bool videoAd; // @dynamic videoAd;
@property(nonatomic, getter=isVideoMuted) _Bool videoMuted; // @dynamic videoMuted;
- (_Bool)isViewVisible:(id)arg1;
- (void)itemDidFailToPlayToEnd:(id)arg1;
- (void)itemDidPlayToEnd:(id)arg1;
- (void)itemDidReceiveNewErrorLogEntry:(id)arg1;
- (void)itemDidStall:(id)arg1;
@property(readonly, nonatomic) __weak ALLogManager *logger; // @dynamic logger;
- (id)muteImageForMuteState:(_Bool)arg1;
@property(retain, nonatomic) UIImageView *muteImageView; // @synthesize muteImageView=_muteImageView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly, nonatomic) __weak NSNumber *percentViewed; // @dynamic percentViewed;
- (void)performBrokenVideoFailsafeIfNeeded;
- (id)placementAwareVideoCompletionURLForPercentViewed:(unsigned long long)arg1;
- (void)playVideo;
- (void)player:(id)arg1 statusDidChange:(id)arg2;
- (void)playerRateDidChange:(id)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)prepareAdditionalTouchArea;
- (void)prepareCountdownClock;
- (void)prepareInterface;
- (void)prerenderPoststitial;
- (void)removeObservers;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic, getter=wasPoststitialShown) _Bool poststitialShown; // @synthesize poststitialShown=_poststitialShown;
@property(retain, nonatomic) ALCloseButton *skipButton; // @synthesize skipButton=_skipButton;
@property(nonatomic) _Bool statusBarOriginallyHidden; // @synthesize statusBarOriginallyHidden=_statusBarOriginallyHidden;
@property(nonatomic) unsigned long long targetInterfaceOrientations; // @synthesize targetInterfaceOrientations=_targetInterfaceOrientations;
@property(nonatomic) _Bool usedVideoStream; // @synthesize usedVideoStream=_usedVideoStream;
@property(retain, nonatomic) ALWebViewButton *videoButton; // @synthesize videoButton=_videoButton;
@property(retain, nonatomic) ALVideoPlayer *videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) ALHtmlAdView *videoPoststitial; // @synthesize videoPoststitial=_videoPoststitial;
@property(nonatomic) unsigned long long videoStreamStalledCount; // @synthesize videoStreamStalledCount=_videoStreamStalledCount;
@property _Bool wasPlayedToEnd; // @synthesize wasPlayedToEnd=_wasPlayedToEnd;
@property(nonatomic) __weak ALInterstitialAd *wrapper; // @synthesize wrapper=_wrapper;
- (_Bool)shouldWarnIncentivizedAdClose;
- (void)showPoststitial;
- (void)skipVideo;
@property(readonly, nonatomic) double standardAnimationTime; // @dynamic standardAnimationTime;
- (unsigned long long)supportedInterfaceOrientations;
@property(readonly, nonatomic) __weak NSNumber *timeLeft; // @dynamic timeLeft;
- (void)toggleMute;
@property(readonly, nonatomic) _Bool videoMutedInitially; // @dynamic videoMutedInitially;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(nonatomic, getter=isAdHidden, setter=setAdHidden:) _Bool adHidden;
@property(nonatomic) __weak id <ALAdLoadDelegate> adLoadDelegate;
@property(nonatomic, getter=currentFrame, setter=setCurrentFrame:) struct CGRect currentFrame;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

