//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ALCloseButtonExtendedClickArea;

@interface ALCloseButton : UIView
{
    ALCloseButtonExtendedClickArea *_extendedClickArea;
}

+ (id)closeButtonWithStyle:(unsigned long long)arg1 frame:(struct CGRect)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long closeButtonStyle; // @dynamic closeButtonStyle;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) ALCloseButtonExtendedClickArea *extendedClickArea; // @synthesize extendedClickArea=_extendedClickArea;
- (id)initWithFrame:(struct CGRect)arg1;

@end

