//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ALConnectionUtils : NSObject
{
}

+ (id)adServerUrl:(id)arg1 with:(id)arg2;
+ (id)apiResultFrom:(id)arg1;
+ (id)apiUrl:(id)arg1 with:(id)arg2;
+ (id)enforceSSLIfNeededForURLString:(id)arg1 usingSDK:(id)arg2;
+ (void)handleApiError:(long long)arg1 fromSdk:(id)arg2;
+ (id)networkType;
+ (id)secureEndpointForUrl:(id)arg1;
+ (void)updateSettingsFor:(id)arg1 fromMessage:(id)arg2;

@end

