//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSString;

@interface ALEvent : NSObject
{
    NSString *_eventType;
    NSDictionary *_parameters;
    NSString *_uniqueIdentifier;
    NSDate *_creationDate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
- (id)description;
@property(copy, nonatomic) NSString *eventType; // @synthesize eventType=_eventType;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToEvent:(id)arg1;
@property(copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;

@end

