//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALLogManager, ALSdk, NSArray;

@interface ALFileManager : NSObject
{
    ALSdk *_sdk;
    NSObject *_fileSystemLock;
}

- (void).cxx_destruct;
- (id)allCachedFileNames;
@property(readonly) __weak NSArray *allCachedFilePaths; // @dynamic allCachedFilePaths;
- (unsigned long long)bytesToMegabytes:(unsigned long long)arg1;
- (_Bool)cacheResourceWithData:(id)arg1 named:(id)arg2;
- (unsigned long long)cacheSizeAfterDroppingExpiredFiles;
- (void)compactCache;
- (void)dropCache;
- (void)dropCacheIfRequired:(unsigned long long)arg1;
- (id)filePathForResourceNamed:(id)arg1;
@property(retain) NSObject *fileSystemLock; // @synthesize fileSystemLock=_fileSystemLock;
@property(readonly) unsigned long long fileTTL; // @dynamic fileTTL;
- (_Bool)hasCachedResourceNamed:(id)arg1;
- (id)initWithSdk:(id)arg1;
@property(readonly) __weak ALLogManager *logManager; // @dynamic logManager;
@property(readonly) unsigned long long maximumCacheSize; // @dynamic maximumCacheSize;
- (_Bool)removeExistingFileAtPath:(id)arg1;
- (_Bool)removeExistingFileNamed:(id)arg1;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
- (id)urlForResourceNamed:(id)arg1;
- (id)urlStringForResourceNamed:(id)arg1;

@end

