//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol ALInterstitialUIViewControlProxy <NSObject>

@optional
@property(nonatomic, getter=currentFrame, setter=setCurrentFrame:) struct CGRect currentFrame;
@property(nonatomic, getter=isAdHidden, setter=setAdHidden:) _Bool adHidden;
@end

