//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALSdk, NSString;

@interface ALIncentivizedConfirmationManager : NSObject
{
    ALSdk *sdk;
    NSString *result;
}

- (void).cxx_destruct;
- (id)confirmationTextFromResult;
- (id)initWithSdk:(id)arg1 result:(id)arg2;
- (void)presentConfirmationToUser;
@property(retain, nonatomic) NSString *result; // @synthesize result;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk;

@end

