//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALInterstitialControlProxy.h"

@class ALLogManager, ALSdk, NSString;

@interface ALInterstitialAd : NSObject <ALInterstitialControlProxy>
{
    _Bool _hidden;
    ALSdk *sdk;
    id <ALInterstitialControlProxy> currentInterstitialController;
    id <ALAdVideoPlaybackDelegate> adVideoPlaybackDelegate;
    id <ALAdDisplayDelegate> adDisplayDelegate;
    id <ALAdLoadDelegate> adLoadDelegate;
    struct CGRect _frame;
}

+ (_Bool)isReadyForDisplay;
+ (id)shared;
+ (id)show;
+ (id)showOver:(id)arg1;
+ (id)showOver:(id)arg1 placement:(id)arg2;
+ (id)showOverPlacement:(id)arg1;
- (void).cxx_destruct;
@property(retain) id <ALAdDisplayDelegate> adDisplayDelegate; // @synthesize adDisplayDelegate;
@property(retain) id <ALAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate;
@property(retain) id <ALAdVideoPlaybackDelegate> adVideoPlaybackDelegate; // @synthesize adVideoPlaybackDelegate;
@property(retain) id <ALInterstitialControlProxy> currentInterstitialController; // @synthesize currentInterstitialController;
- (void)dismiss;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)displayInterstitialAd:(id)arg1 overWindow:(id)arg2 placement:(id)arg3;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
- (id)initInterstitialAdWithSdk:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 sdk:(id)arg2;
- (id)initWithSdk:(id)arg1;
@property(readonly, getter=isReadyForDisplay) _Bool readyForDisplay;
@property(readonly, nonatomic) ALLogManager *logger; // @dynamic logger;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk;
- (void)show;
- (void)showInterstitialInSubview:(id)arg1 overWindow:(id)arg2 withPlacement:(id)arg3;
- (void)showInterstitialInViewController:(id)arg1 overWindow:(id)arg2 withPlacement:(id)arg3;
- (void)showOver:(id)arg1;
- (void)showOver:(id)arg1 andRender:(id)arg2;
- (void)showOver:(id)arg1 placement:(id)arg2;
- (void)showOver:(id)arg1 placement:(id)arg2 andRender:(id)arg3;
- (void)showOverPlacement:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property _Bool dismissesOnClick;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

