//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALInterstitialAdDismissProxy.h"
#import "ALInterstitialControlProxy.h"
#import "ALInterstitialCurrentAdProxy.h"
#import "ALInterstitialUIViewControlProxy.h"

@class ALAd, ALInterstitialAd, ALSdk, NSString;

@protocol ALInterstitialExtendedControlProxy <ALInterstitialControlProxy, ALInterstitialCurrentAdProxy, ALInterstitialUIViewControlProxy, ALInterstitialAdDismissProxy>
- (id)initWithSdk:(ALSdk *)arg1 currentAd:(ALAd *)arg2 currentPlacement:(NSString *)arg3 wrapper:(ALInterstitialAd *)arg4;
@end

