//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALLogManager, ALSdk;

@interface ALNativeAdService : NSObject
{
    ALSdk *_sdk;
    ALLogManager *_logger;
}

- (void).cxx_destruct;
- (id)initWithSdk:(id)arg1;
- (void)loadNativeAdGroupOfCount:(unsigned long long)arg1 andNotify:(id)arg2;
- (void)loadNativeAds:(unsigned long long)arg1 andNotify:(id)arg2;
@property(retain, nonatomic) ALLogManager *logger; // @synthesize logger=_logger;
- (void)precacheResourcesForNativeAd:(id)arg1 andNotify:(id)arg2;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;

@end

