//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALLoadableObject.h"

@class ALSdk, NSNumber, NSString, NSURL;

@interface ALNativeAd : NSObject <ALLoadableObject>
{
    NSNumber *_adIdNumber;
    NSString *_title;
    NSString *_descriptionText;
    NSString *_captionText;
    NSString *_ctaText;
    NSURL *_iconURL;
    NSURL *_imageURL;
    NSNumber *_starRating;
    NSURL *_videoURL;
    NSURL *_impressionTrackingURL;
    NSURL *_clickURL;
    NSURL *_videoStartTrackingURL;
    ALSdk *_parentSdk;
    NSURL *_sourceIconURL;
    NSURL *_sourceImageURL;
    NSURL *_sourceVideoURL;
    NSURL *_videoEndTrackingURL;
    NSString *_clCode;
}

+ (id)sizeNative;
+ (id)specNative;
+ (id)typeNative;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *adIdNumber; // @synthesize adIdNumber=_adIdNumber;
@property(copy, nonatomic) NSString *captionText; // @synthesize captionText=_captionText;
@property(copy, nonatomic) NSString *clCode; // @synthesize clCode=_clCode;
@property(retain, nonatomic) NSURL *clickURL; // @synthesize clickURL=_clickURL;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) NSString *ctaText; // @synthesize ctaText=_ctaText;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(retain, nonatomic) NSURL *iconURL; // @synthesize iconURL=_iconURL;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) NSURL *impressionTrackingURL; // @synthesize impressionTrackingURL=_impressionTrackingURL;
@property(readonly, getter=isImagePrecached) _Bool imagePrecached;
@property(readonly, getter=isVideoPrecached) _Bool videoPrecached;
- (void)launchClickTarget;
@property(nonatomic) __weak ALSdk *parentSdk; // @synthesize parentSdk=_parentSdk;
@property(retain, nonatomic) NSURL *sourceIconURL; // @synthesize sourceIconURL=_sourceIconURL;
@property(retain, nonatomic) NSURL *sourceImageURL; // @synthesize sourceImageURL=_sourceImageURL;
@property(retain, nonatomic) NSURL *sourceVideoURL; // @synthesize sourceVideoURL=_sourceVideoURL;
@property(retain, nonatomic) NSNumber *starRating; // @synthesize starRating=_starRating;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSURL *videoEndTrackingURL; // @synthesize videoEndTrackingURL=_videoEndTrackingURL;
@property(retain, nonatomic) NSURL *videoStartTrackingURL; // @synthesize videoStartTrackingURL=_videoStartTrackingURL;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
- (id)videoEndTrackingURL:(unsigned long long)arg1 firstPlay:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

