//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ALPendingRewardReportManager : NSObject
{
    NSMutableDictionary *pendingRewardParameters;
    NSObject *managerLock;
    NSMutableDictionary *pendingRewardResults;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)init;
@property(retain) NSObject *managerLock; // @synthesize managerLock;
@property(retain, nonatomic) NSMutableDictionary *pendingRewardParameters; // @synthesize pendingRewardParameters;
@property(retain, nonatomic) NSMutableDictionary *pendingRewardResults; // @synthesize pendingRewardResults;
- (id)removeSavedParametersForAd:(id)arg1;
- (id)removeSavedRewardResultForAd:(id)arg1;
- (void)saveParameters:(id)arg1 forAd:(id)arg2;
- (void)saveRewardResult:(id)arg1 forAd:(id)arg2;

@end

