//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSURL;

@interface ALPostbackRequest : NSObject <NSCoding>
{
    NSURL *_targetURL;
    NSDictionary *_requestBody;
    long long _attemptNumber;
}

+ (id)postbackRequestWithURL:(id)arg1 requestBody:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) long long attemptNumber; // @synthesize attemptNumber=_attemptNumber;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToRequest:(id)arg1;
@property(retain, nonatomic) NSDictionary *requestBody; // @synthesize requestBody=_requestBody;
@property(retain, nonatomic) NSURL *targetURL; // @synthesize targetURL=_targetURL;

@end

