//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALSdk;

@interface ALPostbackService : NSObject
{
    ALSdk *_sdk;
}

- (void).cxx_destruct;
- (void)dispatchPostbackAsync:(id)arg1 andNotify:(id)arg2;
- (void)dispatchPostbackAsync:(id)arg1 postBody:(id)arg2 andNotify:(id)arg3;
- (void)dispatchPostbackAsync:(id)arg1 postBody:(id)arg2 retryCount:(long long)arg3 retryDelay:(double)arg4 timeout:(double)arg5 andNotify:(id)arg6;
- (id)initWithSdk:(id)arg1;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;

@end

