//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALPostbackService, NSURL;

@protocol ALPostbackDelegate <NSObject>
- (void)postbackService:(ALPostbackService *)arg1 didExecutePostback:(NSURL *)arg2;
- (void)postbackService:(ALPostbackService *)arg1 didFailToExecutePostback:(NSURL *)arg2 errorCode:(long long)arg3;
@end

