//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ALReachability : NSObject
{
}

+ (id)currentNetworkType;
+ (void)initialize;
+ (_Bool)isReachable;
+ (_Bool)isReachableViaWWAN;
+ (_Bool)isReachableViaWiFi;
+ (_Bool)isReachableWithFlags:(unsigned int)arg1;
+ (id)networkTypeFromSystemConfiguration;

@end

