//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ALSdkSettings : NSObject
{
    _Bool _isTestAdsEnabled;
    _Bool _isVerboseLogging;
    _Bool _muted;
    NSString *_autoPreloadAdSizes;
    NSString *_autoPreloadAdTypes;
}

- (void).cxx_destruct;
@property(retain) NSString *autoPreloadAdSizes; // @synthesize autoPreloadAdSizes=_autoPreloadAdSizes;
@property(retain) NSString *autoPreloadAdTypes; // @synthesize autoPreloadAdTypes=_autoPreloadAdTypes;
- (id)init;
@property _Bool isTestAdsEnabled; // @synthesize isTestAdsEnabled=_isTestAdsEnabled;
@property _Bool isVerboseLogging; // @synthesize isVerboseLogging=_isVerboseLogging;
@property _Bool muted; // @synthesize muted=_muted;

@end

