//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALSdk, NSMutableDictionary, NSString;

@interface ALStatsManager : NSObject
{
    NSMutableDictionary *stats;
    ALSdk *sdk;
    NSString *userDataKey;
}

- (void).cxx_destruct;
- (void)clearAll;
- (void)clearKey:(id)arg1;
- (void)incrementKey:(id)arg1;
- (id)init;
- (id)initWithSdk:(id)arg1;
- (void)loadAll;
- (void)persistAll;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk;
@property(retain, nonatomic) NSString *userDataKey; // @synthesize userDataKey;
- (void)setValue:(id)arg1 forKey:(id)arg2;
@property(readonly, copy) NSMutableDictionary *stats; // @synthesize stats;
- (id)valueOfKey:(id)arg1;

@end

