//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKStoreProductViewController.h"

#import "SKStoreProductViewControllerDelegate.h"

@class ALHtmlAdView, ALIOSAd, NSString, UIViewController<ALApplicationControlProtocol>;

@interface ALStoreKitProductViewController : SKStoreProductViewController <SKStoreProductViewControllerDelegate>
{
    ALIOSAd *_ad;
    ALHtmlAdView *_adView;
    UIViewController<ALApplicationControlProtocol> *_interstitialViewController;
    id <ALStoreKitProductViewControllerDelegate> _storeViewControllerDelegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ALIOSAd *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) ALHtmlAdView *adView; // @synthesize adView=_adView;
- (id)initWithAd:(id)arg1 inAdView:(id)arg2 interstitialViewController:(id)arg3;
@property(retain, nonatomic) UIViewController<ALApplicationControlProtocol> *interstitialViewController; // @synthesize interstitialViewController=_interstitialViewController;
- (_Bool)prefersStatusBarHidden;
- (void)productViewControllerDidFinish:(id)arg1;
@property(nonatomic) __weak id <ALStoreKitProductViewControllerDelegate> storeViewControllerDelegate; // @synthesize storeViewControllerDelegate=_storeViewControllerDelegate;
- (_Bool)shouldAutorotate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

