//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class ALLogManager, ALSdk, NSString;

@interface ALTask : NSOperation
{
    ALSdk *_sdk;
    NSString *_tag;
}

- (void).cxx_destruct;
- (id)initWithSdk:(id)arg1;
@property(retain, nonatomic) ALLogManager *logger; // @dynamic logger;
- (void)main;
- (void)run;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;

@end

