//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALTaskCacheNativeAdBase.h"

@interface ALTaskCacheNativeAdImages : ALTaskCacheNativeAdBase
{
}

- (_Bool)cacheResourcesForNativeAd:(id)arg1 fileManager:(id)arg2;
- (id)initWithSdk:(id)arg1 nativeAdsToPopulate:(id)arg2 precacheDelegate:(id)arg3;
- (void)notifyPrecacheDelegateFailureForNativeAd:(id)arg1;
- (void)notifyPrecacheDelegateSuccessForNativeAd:(id)arg1;

@end

