//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALTask.h"

#import "ALConnectionManagerDelegate.h"

@class ALAd, NSString;

@interface ALTaskReportReward : ALTask <ALConnectionManagerDelegate>
{
    ALAd *sourceAd;
}

- (void).cxx_destruct;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (id)initWithSdk:(id)arg1 adToReport:(id)arg2;
- (void)run;
- (void)sendApiRequestWith:(id)arg1;
@property(retain, nonatomic) ALAd *sourceAd; // @synthesize sourceAd;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

