//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALTask.h"

#import "ALConnectionManagerDelegate.h"

@class NSString;

@interface ALTaskAPISubmitData : ALTask <ALConnectionManagerDelegate>
{
    unsigned long long _attemptsLeft;
}

@property unsigned long long attemptsLeft; // @synthesize attemptsLeft=_attemptsLeft;
- (void)connectionVia:(id)arg1 didFailWith:(long long)arg2;
- (void)connectionVia:(id)arg1 didSucceedWith:(long long)arg2 responseBody:(id)arg3;
- (void)populateDeviceInfo:(id)arg1;
- (void)populateStats:(id)arg1;
- (void)run;
- (void)sendApiRequestWith:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

