//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALSdk, ALVideoView, AVAsset, AVPlayer, AVPlayerItem, NSURL;

@interface ALVideoPlayer : NSObject
{
    ALVideoView *_videoView;
    struct AVPlayerItem *_playerItem;
    struct AVAsset *_playerAsset;
    NSURL *_mediaSource;
    ALSdk *_sdk;
    id <ALAdVideoPlaybackDelegate> _videoPlaybackDelegate;
    struct AVPlayer *_player;
}

- (void).cxx_destruct;
- (id)createVideoView;
- (id)initWithSdk:(id)arg1 mediaSource:(id)arg2;
@property(retain, nonatomic) NSURL *mediaSource; // @synthesize mediaSource=_mediaSource;
- (void)playVideo;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) AVAsset *playerAsset; // @synthesize playerAsset=_playerAsset;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) ALSdk *sdk; // @synthesize sdk=_sdk;
@property(retain, nonatomic) id <ALAdVideoPlaybackDelegate> videoPlaybackDelegate; // @synthesize videoPlaybackDelegate=_videoPlaybackDelegate;
@property(retain, nonatomic) ALVideoView *videoView; // @synthesize videoView=_videoView;
- (void)stopVideo;

@end

