//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class ALSdk, NSDictionary, NSString;

@interface ALVideoButtonProperties : NSObject <NSCopying>
{
    _Bool _tapToFade;
    NSString *_horizontalConstraint;
    NSString *_verticalConstraint;
    double _widthPercentOfScreen;
    double _heightPercentOfScreen;
    double _margin;
    unsigned long long _gravity;
    double _tapToFadeDuration;
    double _fadeInDuration;
    double _fadeOutDuration;
    double _fadeInDelay;
    double _fadeOutDelay;
    ALSdk *_sdk;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDictionary *defaultProperties; // @dynamic defaultProperties;
- (id)description;
@property(nonatomic) double fadeInDelay; // @synthesize fadeInDelay=_fadeInDelay;
@property(nonatomic) double fadeInDuration; // @synthesize fadeInDuration=_fadeInDuration;
@property(nonatomic) double fadeOutDelay; // @synthesize fadeOutDelay=_fadeOutDelay;
@property(nonatomic) double fadeOutDuration; // @synthesize fadeOutDuration=_fadeOutDuration;
@property(nonatomic) unsigned long long gravity; // @synthesize gravity=_gravity;
- (unsigned long long)hash;
@property(nonatomic) double heightPercentOfScreen; // @synthesize heightPercentOfScreen=_heightPercentOfScreen;
@property(copy, nonatomic) NSString *horizontalConstraint; // @synthesize horizontalConstraint=_horizontalConstraint;
- (id)initWithSdk:(id)arg1 properties:(id)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToVideoButtonProperties:(id)arg1;
@property(nonatomic) double margin; // @synthesize margin=_margin;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
@property(nonatomic) _Bool tapToFade; // @synthesize tapToFade=_tapToFade;
@property(nonatomic) double tapToFadeDuration; // @synthesize tapToFadeDuration=_tapToFadeDuration;
@property(copy, nonatomic) NSString *verticalConstraint; // @synthesize verticalConstraint=_verticalConstraint;
@property(nonatomic) double widthPercentOfScreen; // @synthesize widthPercentOfScreen=_widthPercentOfScreen;

@end

