//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

#import "UIWebViewDelegate.h"

@class ALSdk, NSString;

@interface ALWebViewButton : UIWebView <UIWebViewDelegate>
{
    id <ALWebViewButtonDelegate> _clickDelegate;
    ALSdk *_sdk;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <ALWebViewButtonDelegate> clickDelegate; // @synthesize clickDelegate=_clickDelegate;
- (id)initWithSdk:(id)arg1;
@property(nonatomic) __weak ALSdk *sdk; // @synthesize sdk=_sdk;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

