//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ALWebViewProvider : NSObject
{
}

+ (_Bool)isWebKitSupported;
+ (void)proxyDelegateForWebView:(id)arg1 adView:(id)arg2;
+ (id)webViewForSdk:(id)arg1 frame:(struct CGRect)arg2;

@end

