//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSString, UILabel;

@interface CCUIMultilineTextField : UITextView
{
    UILabel *_placeHolderLabel;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *placeHolderLabel; // @synthesize placeHolderLabel=_placeHolderLabel;
@property(nonatomic) NSString *placeholder;
- (void)setText:(id)arg1;
- (void)textChanged:(id)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;

@end

