//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioSessionDelegate.h"
#import "CDAudioInterruptProtocol.h"
#import "CDLongAudioSourceDelegate.h"

@class CDLongAudioSource, CDSoundEngine, NSMutableArray, NSString;

@interface CDAudioManager : NSObject <CDLongAudioSourceDelegate, CDAudioInterruptProtocol, AVAudioSessionDelegate>
{
    CDSoundEngine *soundEngine;
    CDLongAudioSource *backgroundMusic;
    NSMutableArray *audioSourceChannels;
    NSString *_audioSessionCategory;
    _Bool _audioWasPlayingAtStartup;
    int _mode;
    SEL backgroundMusicCompletionSelector;
    id backgroundMusicCompletionListener;
    _Bool willPlayBackgroundMusic;
    _Bool _mute;
    _Bool _resigned;
    _Bool _interrupted;
    _Bool _audioSessionActive;
    _Bool enabled_;
    _Bool _isObservingAppEvents;
    int _resignBehavior;
}

+ (id)alloc;
+ (void)configure:(int)arg1;
+ (void)end;
+ (void)initAsynchronously:(int)arg1;
+ (id)sharedManager;
+ (int)sharedManagerState;
- (void)applicationDidBecomeActive;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)audioSessionInterrupted;
- (void)audioSessionResumed;
- (_Bool)audioSessionSetActive:(_Bool)arg1;
- (_Bool)audioSessionSetCategory:(id)arg1;
- (id)audioSourceForChannel:(int)arg1;
- (id)audioSourceLoad:(id)arg1 channel:(int)arg2;
@property(readonly) CDLongAudioSource *backgroundMusic;
- (void)badAlContextHandler;
- (void)beginInterruption;
- (void)cdAudioSourceDidFinishPlaying:(id)arg1;
- (void)dealloc;
- (_Bool)enabled;
- (void)endInterruption;
- (id)init:(int)arg1;
- (_Bool)isBackgroundMusicPlaying;
- (_Bool)isDeviceMuted;
- (_Bool)isOtherAudioPlaying;
- (_Bool)mute;
- (void)pauseBackgroundMusic;
- (void)playBackgroundMusic:(id)arg1 loop:(_Bool)arg2;
- (void)preloadBackgroundMusic:(id)arg1;
- (void)resumeBackgroundMusic;
- (void)rewindBackgroundMusic;
- (void)setBackgroundMusicCompletionListener:(id)arg1 selector:(SEL)arg2;
- (void)setEnabled:(_Bool)arg1;
- (void)setMode:(int)arg1;
- (void)setMute:(_Bool)arg1;
- (void)setResignBehavior:(int)arg1 autoHandle:(_Bool)arg2;
@property(readonly) CDSoundEngine *soundEngine; // @synthesize soundEngine;
- (void)stopBackgroundMusic;
@property(readonly) _Bool willPlayBackgroundMusic; // @synthesize willPlayBackgroundMusic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

