//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"
#import "CDAudioInterruptProtocol.h"

@class AVAudioPlayer, NSString;

@interface CDLongAudioSource : NSObject <AVAudioPlayerDelegate, CDAudioInterruptProtocol>
{
    AVAudioPlayer *audioSourcePlayer;
    NSString *audioSourceFilePath;
    long long numberOfLoops;
    float volume;
    id <CDLongAudioSourceDelegate> delegate;
    _Bool mute;
    _Bool enabled_;
    _Bool backgroundMusic;
    _Bool paused;
    _Bool stopped;
    _Bool systemPaused;
    double systemPauseLocation;
    int state;
}

- (void)audioPlayerBeginInterruption:(id)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)audioPlayerEndInterruption:(id)arg1;
@property(readonly) NSString *audioSourceFilePath; // @synthesize audioSourceFilePath;
@property(readonly) AVAudioPlayer *audioSourcePlayer; // @synthesize audioSourcePlayer;
@property(nonatomic) _Bool backgroundMusic; // @synthesize backgroundMusic;
- (void)dealloc;
@property id <CDLongAudioSourceDelegate> delegate; // @synthesize delegate;
- (_Bool)enabled;
- (id)init;
- (_Bool)isPlaying;
- (void)load:(id)arg1;
- (_Bool)mute;
@property(nonatomic) long long numberOfLoops;
- (void)pause;
@property(readonly) _Bool paused; // @synthesize paused;
- (void)play;
- (void)resume;
- (void)rewind;
- (void)setEnabled:(_Bool)arg1;
- (void)setMute:(_Bool)arg1;
@property(nonatomic) float volume;
- (void)stop;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

