//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDFloatInterpolator;

@interface CDPropertyModifier : NSObject
{
    CDFloatInterpolator *interpolator;
    float startValue;
    float endValue;
    id target;
    _Bool stopTargetWhenComplete;
}

- (Class)_allowableType;
- (float)_getTargetProperty;
- (void)_setTargetProperty:(float)arg1;
- (void)_stopTarget;
- (void)dealloc;
@property(nonatomic) float endValue;
- (id)init:(id)arg1 interpolationType:(int)arg2 startVal:(float)arg3 endVal:(float)arg4;
@property(nonatomic) int interpolationType;
- (void)modify:(float)arg1;
@property(nonatomic) float startValue;
@property(nonatomic) _Bool stopTargetWhenComplete; // @synthesize stopTargetWhenComplete;

@end

