//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDPropertyModifier.h"

@interface CDSoundSourcePitchBender : CDPropertyModifier
{
}

- (Class)_allowableType;
- (float)_getTargetProperty;
- (void)_setTargetProperty:(float)arg1;
- (void)_stopTarget;

@end

