//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GSDK_PBArray, GSDK_PBGeneratedMessage, NSData, NSOutputStream, NSString, TAGPBArray, TAGPBGeneratedMessage;

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AVAsset {
    Class _field1;
    id _field2;
};

struct AVPlayer {
    Class _field1;
    id _field2;
};

struct AVPlayerItem {
    Class _field1;
    id _field2;
};

struct AVPlayerLayer {
    Class _field1;
    struct _CALayerIvars _field2;
    id _field3;
};

struct Acceleration {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    int _field4;
    void *_field5;
    _Bool _field6;
    double _field7;
    double _field8;
    double _field9;
    double _field10;
};

struct ActionManager;

struct CGAffineTransform {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CGVector {
    double dx;
    double dy;
};

struct Camera;

struct Color3B {
    unsigned char _field1;
    unsigned char _field2;
    unsigned char _field3;
};

struct ComponentContainer;

struct Director;

struct DownloadTask {
    CDUnknownFunctionPointerType *_field1;
    basic_string_a490aa4c _field2;
    basic_string_a490aa4c _field3;
    basic_string_a490aa4c _field4;
    struct unique_ptr<cocos2d::network::IDownloadTask, std::__1::default_delete<cocos2d::network::IDownloadTask>> _field5;
};

struct DownloaderApple {
    CDUnknownFunctionPointerType *_field1;
    struct function<void (const cocos2d::network::DownloadTask &, long long, long long, long long, std::__1::function<long long (void *, long long)>&)> _field2;
    struct function<void (const cocos2d::network::DownloadTask &, int, int, const std::__1::basic_string<char>&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>&)> _field3;
    void *_field4;
};

struct DownloaderHints {
    unsigned int countOfMaxProcessingTasks;
    unsigned int timeoutInSeconds;
    basic_string_a490aa4c tempFileNameSuffix;
};

struct EventDispatcher;

struct EventListenerTouchOneByOne;

struct FIRAReachabilityApi {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    CDUnknownFunctionPointerType _field5;
};

struct GADAdSize {
    struct CGSize size;
    unsigned long long flags;
};

struct GAIReachabilityApi {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    CDUnknownFunctionPointerType _field5;
};

struct GLProgramState;

struct IDownloadTask;

struct Map<int, cocos2d::ui::LayoutParameter *> {
    struct unordered_map<int, cocos2d::ui::LayoutParameter *, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, cocos2d::ui::LayoutParameter *>>> _field1;
};

struct Mat4 {
    float _field1[16];
};

struct Node;

struct PBExtensionDescription {
    char *_field1;
    int _field2;
    char *_field3;
    int _field4;
    union {
        _Bool _field1;
        unsigned int _field2;
        int _field3;
        float _field4;
        unsigned long long _field5;
        long long _field6;
        double _field7;
        int _field8;
        long long _field9;
        int _field10;
        long long _field11;
        unsigned int _field12;
        unsigned long long _field13;
        id _field14;
        id _field15;
        id _field16;
        id _field17;
        int _field18;
        id _field19;
        id _field20;
    } _field5;
    char *_field6;
    unsigned int _field7;
    char *_field8;
};

struct PBInputBufferState {
    char *bytes;
    unsigned long long bufferSize;
    unsigned long long bufferPos;
    unsigned long long currentLimit;
};

struct PBMessageEnumDescription {
    char *_field1;
};

struct PBMessageEnumValueDescription {
    char *_field1;
    int _field2;
};

struct PBMessageExtensionRangeDescription {
    unsigned int _field1;
    unsigned int _field2;
};

struct PBMessageFieldDescription {
    char *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    int _field5;
    unsigned long long _field6;
    char *_field7;
    union {
        _Bool _field1;
        unsigned int _field2;
        int _field3;
        float _field4;
        unsigned long long _field5;
        long long _field6;
        double _field7;
        int _field8;
        long long _field9;
        int _field10;
        long long _field11;
        unsigned int _field12;
        unsigned long long _field13;
        id _field14;
        id _field15;
        id _field16;
        id _field17;
        int _field18;
        id _field19;
        id _field20;
    } _field8;
    CDUnion_28c59bcd _field9;
};

struct PBOutputBufferState {
    char *bytes;
    unsigned long long size;
    unsigned long long position;
    NSOutputStream *output;
};

struct PhysicsBody;

struct Quaternion {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct Ref;

struct Scheduler;

struct Size {
    float _field1;
    float _field2;
};

struct TAGPBExtensionDescription {
    char *_field1;
    int _field2;
    char *_field3;
    int _field4;
    union {
        _Bool _field1;
        unsigned int _field2;
        int _field3;
        float _field4;
        unsigned long long _field5;
        long long _field6;
        double _field7;
        int _field8;
        long long _field9;
        int _field10;
        long long _field11;
        unsigned int _field12;
        unsigned long long _field13;
        id _field14;
        id _field15;
        id _field16;
        id _field17;
        int _field18;
        id _field19;
        id _field20;
    } _field5;
    char *_field6;
    unsigned int _field7;
    char *_field8;
};

struct TAGPBInputBufferState {
    char *bytes;
    unsigned long long bufferSize;
    unsigned long long bufferPos;
    unsigned long long currentLimit;
};

struct TAGPBMessageEnumDescription {
    char *_field1;
};

struct TAGPBMessageEnumValueDescription {
    char *_field1;
    int _field2;
};

struct TAGPBMessageExtensionRangeDescription {
    unsigned int _field1;
    unsigned int _field2;
};

struct TAGPBMessageFieldDescription {
    char *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    int _field5;
    unsigned long long _field6;
    char *_field7;
    union {
        _Bool _field1;
        unsigned int _field2;
        int _field3;
        float _field4;
        unsigned long long _field5;
        long long _field6;
        double _field7;
        int _field8;
        long long _field9;
        int _field10;
        long long _field11;
        unsigned int _field12;
        unsigned long long _field13;
        id _field14;
        id _field15;
        id _field16;
        id _field17;
        int _field18;
        id _field19;
        id _field20;
    } _field8;
    CDUnion_28c59bcd _field9;
};

struct TAGPBOutputBufferState {
    char *bytes;
    unsigned long long size;
    unsigned long long position;
    NSOutputStream *output;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct UIImage {
    Class _field1;
};

struct Vec2 {
    float _field1;
    float _field2;
};

struct Vector<cocos2d::Node *> {
    struct vector<cocos2d::Node *, std::__1::allocator<cocos2d::Node *>> _field1;
};

struct VideoPlayer {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    int _field4;
    void *_field5;
    _Bool _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    struct Quaternion _field11;
    float _field12;
    float _field13;
    float _field14;
    struct Vec2 _field15;
    float _field16;
    struct Vec2 _field17;
    _Bool _field18;
    _Bool _field19;
    float _field20;
    float _field21;
    struct Vec2 _field22;
    struct Vec2 _field23;
    struct Size _field24;
    _Bool _field25;
    struct Mat4 _field26;
    struct Mat4 _field27;
    _Bool _field28;
    struct Mat4 _field29;
    _Bool _field30;
    struct Mat4 *_field31;
    _Bool _field32;
    _Bool _field33;
    long long _field34;
    int _field35;
    float _field36;
    struct Vector<cocos2d::Node *> _field37;
    struct Node *_field38;
    struct Director *_field39;
    int _field40;
    basic_string_a490aa4c _field41;
    unsigned long long _field42;
    void *_field43;
    struct Ref *_field44;
    struct GLProgramState *_field45;
    struct Scheduler *_field46;
    struct ActionManager *_field47;
    struct EventDispatcher *_field48;
    _Bool _field49;
    _Bool _field50;
    _Bool _field51;
    _Bool _field52;
    _Bool _field53;
    int _field54;
    int _field55;
    int _field56;
    struct ComponentContainer *_field57;
    unsigned char _field58;
    unsigned char _field59;
    struct Color3B _field60;
    struct Color3B _field61;
    _Bool _field62;
    _Bool _field63;
    unsigned short _field64;
    struct function<void ()> _field65;
    struct function<void ()> _field66;
    struct function<void ()> _field67;
    struct function<void ()> _field68;
    struct PhysicsBody *_field69;
    struct Vector<cocos2d::Node *> _field70;
    _Bool _field71;
    CDUnknownFunctionPointerType *_field72;
    struct function<void (cocos2d::ui::Widget *, cocos2d::ui::Widget *)> _field73;
    struct function<cocos2d::ui::Widget *(cocos2d::ui::Widget::FocusDirection)> _field74;
    _Bool _field75;
    _Bool _field76;
    _Bool _field77;
    _Bool _field78;
    _Bool _field79;
    _Bool _field80;
    _Bool _field81;
    _Bool _field82;
    _Bool _field83;
    int _field84;
    int _field85;
    int _field86;
    int _field87;
    struct Size _field88;
    struct Vec2 _field89;
    struct Vec2 _field90;
    _Bool _field91;
    struct Camera *_field92;
    struct EventListenerTouchOneByOne *_field93;
    struct Vec2 _field94;
    struct Vec2 _field95;
    struct Vec2 _field96;
    _Bool _field97;
    _Bool _field98;
    struct Map<int, cocos2d::ui::LayoutParameter *> _field99;
    int _field100;
    _Bool _field101;
    _Bool _field102;
    struct Ref *_field103;
    struct function<void (cocos2d::Ref *, cocos2d::ui::Widget::TouchEventType)> _field104;
    struct function<void (cocos2d::Ref *)> _field105;
    struct function<void (cocos2d::Ref *, int)> _field106;
    basic_string_a490aa4c _field107;
    basic_string_a490aa4c _field108;
    _Bool _field109;
    _Bool _field110;
    _Bool _field111;
    _Bool _field112;
    basic_string_a490aa4c _field113;
    int _field114;
    int _field115;
    struct function<void (cocos2d::Ref *, cocos2d::experimental::ui::VideoPlayer::EventType)> _field116;
    void *_field117;
};

struct _CALayerIvars {
    int _field1;
    unsigned int _field2;
    void *_field3;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct __hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>;

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *__data_;
                    unsigned long long __size_;
                    unsigned long long __cap_;
                } __l;
                struct __short {
                    char __data_[23];
                    struct {
                        unsigned char __size_;
                    } ;
                } __s;
                struct __raw {
                    unsigned long long __words[3];
                } __r;
            } ;
        } __first_;
    } __r_;
};

struct deque<NSURLSessionTask *, std::__1::allocator<NSURLSessionTask *>> {
    struct __split_buffer<NSURLSessionTask **, std::__1::allocator<NSURLSessionTask **>> {
        id **__first_;
        id **__begin_;
        id **__end_;
        struct __compressed_pair<NSURLSessionTask ***, std::__1::allocator<NSURLSessionTask **>> {
            id **__first_;
        } __end_cap_;
    } __map_;
    unsigned long long __start_;
    struct __compressed_pair<unsigned long, std::__1::allocator<NSURLSessionTask *>> {
        unsigned long long __first_;
    } __size_;
};

struct function<bool (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<bool (std::__1::basic_string<char>)> *__f_;
};

struct function<cocos2d::ui::Widget *(cocos2d::ui::Widget::FocusDirection)> {
    struct type _field1;
    struct __base<cocos2d::ui::Widget *(cocos2d::ui::Widget::FocusDirection)> *_field2;
};

struct function<void ()> {
    struct type _field1;
    struct __base<void ()> *_field2;
};

struct function<void (cocos2d::Ref *)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *)> *_field2;
};

struct function<void (cocos2d::Ref *, cocos2d::experimental::ui::VideoPlayer::EventType)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *, cocos2d::experimental::ui::VideoPlayer::EventType)> *_field2;
};

struct function<void (cocos2d::Ref *, cocos2d::ui::Widget::TouchEventType)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *, cocos2d::ui::Widget::TouchEventType)> *_field2;
};

struct function<void (cocos2d::Ref *, int)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *, int)> *_field2;
};

struct function<void (cocos2d::ui::Widget *, cocos2d::ui::Widget *)> {
    struct type _field1;
    struct __base<void (cocos2d::ui::Widget *, cocos2d::ui::Widget *)> *_field2;
};

struct function<void (const cocos2d::network::DownloadTask &, int, int, const std::__1::basic_string<char>&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>&)> {
    struct type _field1;
    struct __base<void (const cocos2d::network::DownloadTask &, int, int, const std::__1::basic_string<char>&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>&)> *_field2;
};

struct function<void (const cocos2d::network::DownloadTask &, long long, long long, long long, std::__1::function<long long (void *, long long)>&)> {
    struct type _field1;
    struct __base<void (const cocos2d::network::DownloadTask &, long long, long long, long long, std::__1::function<long long (void *, long long)>&)> *_field2;
};

struct function<void (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<void (std::__1::basic_string<char>)> *__f_;
};

struct in_addr {
    unsigned int _field1;
};

struct queue<NSURLSessionTask *, std::__1::deque<NSURLSessionTask *, std::__1::allocator<NSURLSessionTask *>>> {
    struct deque<NSURLSessionTask *, std::__1::allocator<NSURLSessionTask *>> c;
};

struct re_guts;

struct shared_ptr<const cocos2d::network::DownloadTask> {
    struct DownloadTask *__ptr_;
    struct __shared_weak_count *__cntrl_;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct type {
    unsigned char __lx[24];
};

struct unique_ptr<cocos2d::network::IDownloadTask, std::__1::default_delete<cocos2d::network::IDownloadTask>> {
    struct __compressed_pair<cocos2d::network::IDownloadTask *, std::__1::default_delete<cocos2d::network::IDownloadTask>> {
        struct IDownloadTask *_field1;
    } _field1;
};

struct unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>>> {
    struct __compressed_pair<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>**, std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>>> {
        struct __hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *> **_field1;
        struct __bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>> {
            struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>> {
                unsigned long long _field1;
            } _field1;
        } _field2;
    } _field1;
};

struct unordered_map<int, cocos2d::ui::LayoutParameter *, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, cocos2d::ui::LayoutParameter *>>> {
    struct __hash_table<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::hash<int>, true>, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::equal_to<int>, true>, std::__1::allocator<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>>> {
        struct unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>>> _field1;
        struct __compressed_pair<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>>> {
            struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*> {
                struct __hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *> *_field1;
            } _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::hash<int>, true>> {
            unsigned long long _field1;
        } _field3;
        struct __compressed_pair<float, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::equal_to<int>, true>> {
            float _field1;
        } _field4;
    } _field1;
};

struct vector<cocos2d::Node *, std::__1::allocator<cocos2d::Node *>> {
    struct Node **_field1;
    struct Node **_field2;
    struct __compressed_pair<cocos2d::Node **, std::__1::allocator<cocos2d::Node *>> {
        struct Node **_field1;
    } _field3;
};

struct vng_tm_zip_s {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
};

#pragma mark Typedef'd Structures

typedef struct {
    id _field1;
    unsigned short _field2;
} CDStruct_6a59ab51;

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
} CDStruct_27b5ccfc;

typedef struct {
    long long _field1;
    int _field2;
    unsigned int _field3;
    long long _field4;
} CDStruct_198678f7;

typedef struct {
    long long majorVersion;
    long long minorVersion;
    long long patchVersion;
} CDStruct_f6aba300;

typedef struct {
    long long _field1;
    long long _field2;
} CDStruct_912cb5d2;

typedef struct {
    struct vng_tm_zip_s _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
} CDStruct_b33206b2;

// Template types
typedef struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *__data_;
                    unsigned long long __size_;
                    unsigned long long __cap_;
                } __l;
                struct __short {
                    char __data_[23];
                    struct {
                        unsigned char __size_;
                    } ;
                } __s;
                struct __raw {
                    unsigned long long __words[3];
                } __r;
            } ;
        } __first_;
    } __r_;
} basic_string_a490aa4c;

typedef struct function<bool (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<bool (std::__1::basic_string<char>)> *__f_;
} function_10b5811e;

typedef struct function<void (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<void (std::__1::basic_string<char>)> *__f_;
} function_ef19a04c;

typedef struct shared_ptr<const cocos2d::network::DownloadTask> {
    struct DownloadTask *__ptr_;
    struct __shared_weak_count *__cntrl_;
} shared_ptr_55131426;

#pragma mark Named Unions

union _GLKMatrix4 {
    struct {
        float m00;
        float m01;
        float m02;
        float m03;
        float m10;
        float m11;
        float m12;
        float m13;
        float m20;
        float m21;
        float m22;
        float m23;
        float m30;
        float m31;
        float m32;
        float m33;
    } ;
    float m[16];
};

#pragma mark Typedef'd Unions

typedef union {
    char *_field1;
    CDUnknownFunctionPointerType _field2;
} CDUnion_28c59bcd;

// Ambiguous groups
typedef union {
    _Bool _field1;
    unsigned int _field2;
    int _field3;
    float _field4;
    unsigned long long _field5;
    long long _field6;
    double _field7;
    int _field8;
    long long _field9;
    int _field10;
    long long _field11;
    unsigned int _field12;
    unsigned long long _field13;
    id _field14;
    id _field15;
    id _field16;
    id _field17;
    int _field18;
    id _field19;
    id _field20;
} CDUnion_c05604a2;

typedef union {
    _Bool valueBool;
    unsigned int valueFixed32;
    int valueSFixed32;
    float valueFloat;
    unsigned long long valueFixed64;
    long long valueSFixed64;
    double valueDouble;
    int valueInt32;
    long long valueInt64;
    int valueSInt32;
    long long valueSInt64;
    unsigned int valueUInt32;
    unsigned long long valueUInt64;
    NSData *valueData;
    NSString *valueString;
    GSDK_PBGeneratedMessage *valueMessage;
    GSDK_PBGeneratedMessage *valueGroup;
    int valueEnum;
    GSDK_PBArray *valueArray;
    id valueObject;
} CDUnion_cfc866cd;

typedef union {
    _Bool valueBool;
    unsigned int valueFixed32;
    int valueSFixed32;
    float valueFloat;
    unsigned long long valueFixed64;
    long long valueSFixed64;
    double valueDouble;
    int valueInt32;
    long long valueInt64;
    int valueSInt32;
    long long valueSInt64;
    unsigned int valueUInt32;
    unsigned long long valueUInt64;
    NSData *valueData;
    NSString *valueString;
    TAGPBGeneratedMessage *valueMessage;
    TAGPBGeneratedMessage *valueGroup;
    int valueEnum;
    TAGPBArray *valueArray;
    id valueObject;
} CDUnion_3de46016;

