//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface DFPCustomRenderedAd : NSObject
{
    _Bool _isRendered;
    id <DFPCustomRenderedAdEventHandler> _eventHandler;
    NSString *_adHTML;
    NSURL *_adBaseURL;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSURL *adBaseURL; // @synthesize adBaseURL=_adBaseURL;
@property(readonly, copy, nonatomic) NSString *adHTML; // @synthesize adHTML=_adHTML;
- (void)finishedRenderingAdView:(id)arg1;
- (id)init;
- (id)initWithAdHTML:(id)arg1 adBaseURL:(id)arg2 eventHandler:(id)arg3;
- (void)recordClick;
- (void)recordImpression;

@end

