//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ACPUserAttribute, FIRAValue, NSString;

@interface FIRAUserAttribute : NSObject
{
    NSString *_name;
    FIRAValue *_value;
    double _lastSetTimestamp;
}

- (void).cxx_destruct;
- (id)initWithName:(id)arg1 value:(id)arg2 lastSetTimestamp:(double)arg3;
@property(readonly, nonatomic) _Bool isPublic;
@property(readonly, nonatomic) double lastSetTimestamp; // @synthesize lastSetTimestamp=_lastSetTimestamp;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) ACPUserAttribute *protoUserAttribute;
@property(readonly, nonatomic) FIRAValue *value; // @synthesize value=_value;

@end

