//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIROptions, FIR_ICOREICoreConfiguration, NSString;

@interface FIRApp : NSObject
{
    _Bool _alreadySentConfigureNotification;
    _Bool _alreadySentDeleteNotification;
    NSString *_name;
    FIROptions *_options;
    FIR_ICOREICoreConfiguration *_icoreConfiguration;
    CDUnknownBlockType _getTokenImplementation;
}

+ (id)actualBundleID;
+ (void)addAppToAppDictionary:(id)arg1;
+ (id)allApps;
+ (id)appNamed:(id)arg1;
+ (void)checkExpectedBundleID;
+ (void)configure;
+ (void)configureDefaultAppWithOptions:(id)arg1 sendingNotifications:(_Bool)arg2;
+ (void)configureWithName:(id)arg1 options:(id)arg2;
+ (void)configureWithOptions:(id)arg1;
+ (void)configureWithoutSendingNotification;
+ (id)defaultApp;
+ (id)deviceModel;
+ (id)errorForInvalidAppID;
+ (id)errorForMissingOptions;
+ (id)errorForSubspecConfigurationFailureWithDomain:(id)arg1 errorCode:(long long)arg2 service:(id)arg3 reason:(id)arg4;
+ (id)expectedBundleID;
+ (id)filePathURLWithName:(id)arg1;
+ (void)initClearcut;
+ (id)installString;
+ (void)logAppInfo:(id)arg1;
+ (int)mapFromServiceStringToTypeEnum:(id)arg1;
+ (void)populateLogProto:(id)arg1 withError:(id)arg2;
+ (void)registerForNotifications;
+ (void)removeFIRAppFromNotificationCenter:(id)arg1;
+ (void)resetApps;
+ (void)sendLogsToClearcut:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)sendNotificationsToSDKs:(id)arg1;
+ (_Bool)validateAppIDFingerprint:(id)arg1 withVersion:(id)arg2;
+ (_Bool)validateAppIDFormat:(id)arg1 withVersion:(id)arg2;
+ (_Bool)writeStringToURL:(id)arg1 withURL:(id)arg2;
+ (void)writeTimestampNowToFile;
- (void).cxx_destruct;
@property(nonatomic) _Bool alreadySentConfigureNotification; // @synthesize alreadySentConfigureNotification=_alreadySentConfigureNotification;
@property(nonatomic) _Bool alreadySentDeleteNotification; // @synthesize alreadySentDeleteNotification=_alreadySentDeleteNotification;
- (_Bool)configureCore;
- (void)deleteApp:(CDUnknownBlockType)arg1;
- (void)getTokenForcingRefresh:(_Bool)arg1 withCallback:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) CDUnknownBlockType getTokenImplementation; // @synthesize getTokenImplementation=_getTokenImplementation;
@property(retain, nonatomic) FIR_ICOREICoreConfiguration *icoreConfiguration; // @synthesize icoreConfiguration=_icoreConfiguration;
- (id)initInstanceWithName:(id)arg1 options:(id)arg2;
- (_Bool)isAppIDValid;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) FIROptions *options; // @synthesize options=_options;
- (void)populateLogProtoWithCommonInfo:(id)arg1;
- (void)populateLogProtoWithInstalledServices:(id)arg1;
- (void)sendLogsWithServiceName:(id)arg1 version:(id)arg2 error:(id)arg3;

@end

