//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRAPersistedConfig, FIRASqliteStore;

@interface FIRADatabase : NSObject
{
    FIRASqliteStore *_sqliteStore;
    FIRAPersistedConfig *_persistedConfig;
}

+ (id)databasePathWithName:(id)arg1;
+ (_Bool)deleteDatabaseFileWithName:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
- (id)addOnTableDefinitions;
- (id)allAudienceIDs:(id *)arg1;
- (id)allDataTypesFromTableWithName:(id)arg1 tableLimit:(long long)arg2 error:(id *)arg3 createDataTypeBlock:(CDUnknownBlockType)arg4;
- (id)allEventAggregates:(id *)arg1;
- (id)allFilterResults:(id *)arg1;
- (id)allLifetimeValueUserAttributes:(id *)arg1;
- (id)allUserAttributes:(id *)arg1;
- (id)appMetadataFromDictionary:(id)arg1;
- (id)bundleRowIDPairsWithRecords:(id)arg1 countLimit:(long long)arg2 sizeLimit:(long long)arg3;
- (id)columnNamesFromColumnInfo:(id)arg1;
- (id)constructAlterStatementForTableWithName:(id)arg1 columnInfo:(id)arg2;
- (id)constructCreateStatementForTableWithName:(id)arg1 columnInfo:(id)arg2;
- (id)containsRawEventWithMetadataFingerprint:(long long)arg1 error:(id *)arg2;
- (id)containsUserAttributeWithName:(id)arg1 error:(id *)arg2;
- (id)dailyCounts:(id *)arg1;
- (id)dailyCountsFromDictionary:(id)arg1;
- (id)dataTypesFromTableWithName:(id)arg1 columnName:(id)arg2 columnValue:(id)arg3 error:(id *)arg4 createDataTypeBlock:(CDUnknownBlockType)arg5;
- (_Bool)deleteAllEventFilters:(id *)arg1;
- (_Bool)deleteAllPropertyFilters:(id *)arg1;
- (_Bool)deleteBundlesWithRowIDs:(id)arg1 error:(id *)arg2;
- (_Bool)deleteEventFilters:(id)arg1 error:(id *)arg2;
- (_Bool)deleteFilterResults:(id)arg1 error:(id *)arg2;
- (_Bool)deletePropertyFilters:(id)arg1 error:(id *)arg2;
- (_Bool)deleteRawEventMetadataWithMetadataFingerprint:(long long)arg1 error:(id *)arg2;
- (id)deleteRawEventsOverAbsoluteLimit:(id *)arg1;
- (_Bool)deleteRawEventsWithMaxRowID:(long long)arg1 error:(id *)arg2;
- (_Bool)deleteStaleBundlesOlderThanMaxAge:(double)arg1 error:(id *)arg2;
- (_Bool)deleteStaleRawEventsDataOlderThanMaxAge:(double)arg1 error:(id *)arg2;
- (_Bool)deleteUnusedRawEventsMetadata:(id *)arg1;
- (_Bool)deleteUserAttributeWithName:(id)arg1 error:(id *)arg2;
- (id)dictionaryFromAppMetadata:(id)arg1;
- (id)dictionaryFromDailyCounts:(id)arg1;
- (id)dictionaryFromEventAggregates:(id)arg1;
- (id)dictionaryFromEventFilter:(id)arg1;
- (id)dictionaryFromFilterResult:(id)arg1;
- (id)dictionaryFromMeasurementBundleMetadata:(id)arg1;
- (id)dictionaryFromPropertyFilter:(id)arg1;
- (id)dictionaryFromRawEvent:(id)arg1;
- (id)dictionaryFromUserAttribute:(id)arg1;
- (id)elementaryTableDefinitions;
- (_Bool)ensureAllTables;
- (id)eventAggregatesFromDictionary:(id)arg1;
- (id)eventAggregatesWithName:(id)arg1 error:(id *)arg2;
- (id)eventFilterFromDictionary:(id)arg1;
- (id)eventFiltersForEventName:(id)arg1 error:(id *)arg2;
- (id)eventFromDictionary:(id)arg1 error:(id *)arg2;
- (id)filterResultForAudienceID:(int)arg1 error:(id *)arg2;
- (id)filterResultFromDictionary:(id)arg1;
- (id)initWithDatabaseName:(id)arg1 persistedConfig:(id)arg2;
- (_Bool)initializeAppMetadata;
- (_Bool)insertBundle:(id)arg1 error:(id *)arg2;
- (_Bool)insertDataType:(id)arg1 inTableWithName:(id)arg2 error:(id *)arg3 createDictionaryBlock:(CDUnknownBlockType)arg4;
- (_Bool)insertIfNotExistsRawEventMetadata:(id)arg1 error:(id *)arg2;
- (_Bool)insertRawEvent:(id)arg1 metadataFingerprint:(long long)arg2 error:(id *)arg3;
- (id)isQueuedBundleTableEmpty:(id *)arg1;
- (id)isRawEventsTableEmpty:(id *)arg1;
- (id)lastRemoteConfigUpdateTimestamp:(id *)arg1;
- (id)maybeDeleteStaleData:(id *)arg1;
- (id)measurementBundleFromDictionary:(id)arg1;
- (id)nextMetadataFingerprintToProcess:(id *)arg1;
- (_Bool)performTransaction:(CDUnknownBlockType)arg1;
- (id)propertyFilterFromDictionary:(id)arg1;
- (id)propertyFiltersForPropertyName:(id)arg1 error:(id *)arg2;
- (id)publicEventCount:(id *)arg1;
- (id)publicUserAttributeCount:(id *)arg1;
- (id)queryACPMeasurementConfigWithError:(id *)arg1;
- (id)queryAppMetadata:(id *)arg1;
- (id)queryBundlesWithCountLimit:(long long)arg1 sizeLimit:(long long)arg2 error:(id *)arg3;
- (id)queryLatestBundleTime:(id *)arg1;
- (id)queryLatestRawEventTime:(id *)arg1;
- (id)queryRawEventsMetadataWithFingerprint:(long long)arg1 error:(id *)arg2;
- (id)rawEventDataFromDictionary:(id)arg1 error:(id *)arg2;
- (id)rawEventsWithMetadataFingerprint:(long long)arg1 error:(id *)arg2 eventFilter:(CDUnknownBlockType)arg3;
- (_Bool)updateAppMetadata:(id)arg1 error:(id *)arg2;
- (_Bool)updateDailyCounts:(id)arg1 error:(id *)arg2;
- (_Bool)updateDataType:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 error:(id *)arg5 createDictionaryBlock:(CDUnknownBlockType)arg6;
- (_Bool)updateEventAggregates:(id)arg1 error:(id *)arg2;
- (_Bool)updateEventFilters:(id)arg1 error:(id *)arg2;
- (_Bool)updateFilterResults:(id)arg1 error:(id *)arg2;
- (_Bool)updatePropertyFilters:(id)arg1 error:(id *)arg2;
- (_Bool)updateRemoteConfig:(id)arg1 error:(id *)arg2;
- (_Bool)updateRemoteConfigSuccessfulTimestamp:(double)arg1 error:(id *)arg2;
- (_Bool)updateUserAttribute:(id)arg1 error:(id *)arg2;
- (_Bool)upsertDataType:(id)arg1 inTableWithName:(id)arg2 columnName:(id)arg3 columnValue:(id)arg4 tableLimit:(long long)arg5 error:(id *)arg6 createDictionaryBlock:(CDUnknownBlockType)arg7;
- (id)userAttributeFromDictionary:(id)arg1;
- (id)userAttributeWithName:(id)arg1 error:(id *)arg2;

@end

