//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRANetworkLogger : NSObject
{
}

+ (void)logWithLoggerDomain:(id)arg1 logLevel:(long long)arg2 message:(id)arg3;
+ (void)logWithLoggerDomain:(id)arg1 logLevel:(long long)arg2 message:(id)arg3 context:(id)arg4;
+ (void)logWithLoggerDomain:(id)arg1 logLevel:(long long)arg2 message:(id)arg3 contexts:(id)arg4;

@end

