//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface FIRAPropertyFilter : NSObject
{
    int _audienceID;
    int _filterID;
    NSString *_propertyName;
    NSData *_data;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) int audienceID; // @synthesize audienceID=_audienceID;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
@property(readonly, nonatomic) int filterID; // @synthesize filterID=_filterID;
- (id)initWithAudienceID:(int)arg1 filterID:(int)arg2 propertyName:(id)arg3 data:(id)arg4;
@property(readonly, nonatomic) NSString *propertyName; // @synthesize propertyName=_propertyName;

@end

