//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface FIRAFilterResult : NSObject
{
    int _audienceID;
    NSData *_currentResults;
    NSData *_previousResults;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) int audienceID; // @synthesize audienceID=_audienceID;
@property(readonly, nonatomic) NSData *currentResults; // @synthesize currentResults=_currentResults;
- (id)initWithAudienceID:(int)arg1 currentResults:(id)arg2 previousResults:(id)arg3;
@property(readonly, nonatomic) NSData *previousResults; // @synthesize previousResults=_previousResults;

@end

