//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRADailyCounts : NSObject
{
    int _day;
    int _conversionsCount;
    int _allEventsCount;
    int _publicEventsCount;
    int _errorEventsCount;
}

@property(readonly, nonatomic) int allEventsCount; // @synthesize allEventsCount=_allEventsCount;
@property(readonly, nonatomic) int conversionsCount; // @synthesize conversionsCount=_conversionsCount;
@property(readonly, nonatomic) int day; // @synthesize day=_day;
- (void)decrementAllEventsCount;
@property(readonly, nonatomic) int errorEventsCount; // @synthesize errorEventsCount=_errorEventsCount;
- (void)incrementCountsForCurrentDay:(int)arg1 isPublicEvent:(_Bool)arg2 isConversion:(_Bool)arg3;
- (void)incrementErrorEventsCountForCurrentDay:(int)arg1;
- (id)initWithDay:(int)arg1 conversionsCount:(int)arg2 allEventsCount:(int)arg3 publicEventsCount:(int)arg4 errorEventsCount:(int)arg5;
@property(readonly, nonatomic) int publicEventsCount; // @synthesize publicEventsCount=_publicEventsCount;

@end

