//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FIRAReachabilityDelegate.h"

@class FIRAMutableDictionary, FIRAReachabilityChecker, NSString;

@interface FIRANetwork : NSObject <FIRAReachabilityDelegate>
{
    FIRAReachabilityChecker *_reachability;
    FIRAMutableDictionary *_requests;
    NSString *_loggerDomain;
    _Bool _networkConnected;
    id <FIRANetworkReachabilityDelegate> _reachabilityDelegate;
}

+ (void)handleEventsForBackgroundURLSessionID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getURL:(id)arg1 headers:(id)arg2 queue:(id)arg3 usingBackgroundSession:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)handleErrorWithCode:(long long)arg1 queue:(id)arg2 withHandler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic, getter=hasUploadInProgress) _Bool uploadInProgress;
- (id)init;
- (id)initWithLoggerDomain:(id)arg1;
@property(readonly, nonatomic, getter=isNetworkConnected) _Bool networkConnected; // @synthesize networkConnected=_networkConnected;
- (id)postURL:(id)arg1 payload:(id)arg2 queue:(id)arg3 usingBackgroundSession:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)reachability:(id)arg1 statusChanged:(int)arg2;
@property(nonatomic) __weak id <FIRANetworkReachabilityDelegate> reachabilityDelegate; // @synthesize reachabilityDelegate=_reachabilityDelegate;

@end

