//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDecimalNumber;

@interface FIRAAudienceComparisonValues : NSObject
{
    _Bool _isValid;
    NSDecimalNumber *_comparisonValue;
    NSDecimalNumber *_maxComparisonValue;
    NSDecimalNumber *_minComparisonValue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDecimalNumber *comparisonValue; // @synthesize comparisonValue=_comparisonValue;
@property(nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(retain, nonatomic) NSDecimalNumber *maxComparisonValue; // @synthesize maxComparisonValue=_maxComparisonValue;
@property(retain, nonatomic) NSDecimalNumber *minComparisonValue; // @synthesize minComparisonValue=_minComparisonValue;

@end

