//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRADataTypeValidator : NSObject
{
}

+ (void)initialize;
+ (_Bool)isValidForwardedEventOrigin:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidInternalEventName:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidInternalEventOrigin:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidInternalEventParameterName:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidInternalEventParameterValue:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidInternalString:(id)arg1 maxLength:(long long)arg2 type:(long long)arg3 failureCode:(long long *)arg4;
+ (_Bool)isValidInternalUserAttributeName:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidInternalUserAttributeValue:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidPublicEventName:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidPublicEventParameterName:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidPublicEventParameterValue:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidPublicString:(id)arg1 maxLength:(long long)arg2 type:(long long)arg3 failureCode:(long long *)arg4;
+ (_Bool)isValidPublicUserAttributeName:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidPublicUserAttributeValue:(id)arg1 failureCode:(long long *)arg2;
+ (_Bool)isValidString:(id)arg1 maxLength:(long long)arg2 type:(long long)arg3 failureCode:(long long *)arg4;
+ (_Bool)isValidValue:(id)arg1 maxLength:(long long)arg2 type:(long long)arg3 failureCode:(long long *)arg4;

@end

