//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRAnalytics : NSObject
{
}

+ (id)addLogEventListener:(CDUnknownBlockType)arg1;
+ (void)createAppDelegateProxy;
+ (void)dispatchAsyncOnSerialQueue:(CDUnknownBlockType)arg1;
+ (void)handleEventsForBackgroundURLSession:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)handleOpenURL:(id)arg1;
+ (void)handleSetEnabled:(id)arg1;
+ (void)handleSetMinimumSessionInterval:(id)arg1;
+ (void)handleSetSessionTimeoutInterval:(id)arg1;
+ (void)handleUserActivity:(id)arg1;
+ (void)logEventOnSerialQueueWithOrigin:(id)arg1 isPublicEvent:(_Bool)arg2 name:(id)arg3 parameters:(id)arg4 timestamp:(double)arg5 ignoreEnabled:(_Bool)arg6 ignoreInterceptor:(_Bool)arg7;
+ (void)logEventWithName:(id)arg1 parameters:(id)arg2;
+ (void)logEventWithOrigin:(id)arg1 isPublicEvent:(_Bool)arg2 name:(id)arg3 parameters:(id)arg4;
+ (void)logEventWithOrigin:(id)arg1 isPublicEvent:(_Bool)arg2 name:(id)arg3 parameters:(id)arg4 timestamp:(double)arg5 ignoreEnabled:(_Bool)arg6 ignoreInterceptor:(_Bool)arg7;
+ (void)logEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3;
+ (void)logInternalEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3;
+ (void)maybeEnableTagManager;
+ (void)notifyEventListeners:(id)arg1;
+ (void)notifyEventListenersOnSerialQueue:(id)arg1;
+ (void)observeNotificationsForAnalyticsConfiguration:(id)arg1;
+ (void)removeInternalUserAttributeForName:(id)arg1;
+ (void)removeLogEventListener:(id)arg1;
+ (void)removeUserAttributeForName:(id)arg1;
+ (void)setInternalUserProperty:(id)arg1 forName:(id)arg2;
+ (void)setIsAnalyticsEnabled:(_Bool)arg1;
+ (void)setLogEventInterceptor:(CDUnknownBlockType)arg1;
+ (void)setOpenURLListener:(CDUnknownBlockType)arg1;
+ (void)setUserAttributeNumber:(id)arg1 forName:(id)arg2;
+ (void)setUserID:(id)arg1;
+ (void)setUserPropertyString:(id)arg1 forName:(id)arg2;
+ (void)startWithConfiguration:(id)arg1 options:(id)arg2;

@end

