//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface FIRAAlarm : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_timer;
}

- (void).cxx_destruct;
- (void)cancel;
- (void)dealloc;
@property(readonly, nonatomic) _Bool hasTaskScheduled;
- (id)initWithDispatchQueue:(id)arg1;
- (void)runAfterDelay:(double)arg1 withBlock:(CDUnknownBlockType)arg2;

@end

