//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRAASLLogger, FIRAMonitoringSampledData, NSObject<OS_dispatch_queue>, NSUserDefaults;

@interface FIRAMonitor : NSObject
{
    long long _logLevel;
    FIRAASLLogger *_logger;
    FIRAMonitoringSampledData *_monitoringSampledData;
    NSObject<OS_dispatch_queue> *_monitorQueue;
    long long _libraryVersion;
    NSUserDefaults *_userDefaults;
    _Bool _isDebugModeEnabled;
    _Bool _encodeContexts;
}

+ (id)encodedStringWithContextArray:(id)arg1 insertSpaces:(_Bool)arg2;
+ (id)encodedStringWithContextObject:(id)arg1;
+ (_Bool)isMonitorableLevel:(long long)arg1;
+ (_Bool)isSilentLevel:(long long)arg1;
+ (id)lastFIRASymbolFromException:(id)arg1;
+ (id)logLevelDescriptionFromLogLevel:(long long)arg1;
+ (id)monitoringDataKeyWithMessage:(id)arg1 logLevel:(long long)arg2 libraryVersion:(long long)arg3;
+ (id)stringWithLogMessage:(id)arg1 logLevel:(long long)arg2 contexts:(id)arg3 encodeContexts:(_Bool)arg4 monitorLoggingTag:(id)arg5;
- (void).cxx_destruct;
- (void)clearMonitoringData;
@property(nonatomic) _Bool encodeContexts; // @synthesize encodeContexts=_encodeContexts;
- (id)initWithLibraryVersion:(long long)arg1;
- (id)initWithLogLevel:(long long)arg1 logger:(id)arg2 libraryVersion:(long long)arg3;
- (void)insertOrUpdateMonitoringDataWithMessage:(id)arg1 encodedContext:(id)arg2 logLevel:(long long)arg3;
@property(nonatomic) _Bool isDebugModeEnabled; // @synthesize isDebugModeEnabled=_isDebugModeEnabled;
- (_Bool)isLoggableLevel:(long long)arg1;
- (void)loadMonitoringDataFromUserDefaults;
- (void)logToConsole:(id)arg1 logLevel:(long long)arg2;
- (void)logWithLevel:(long long)arg1 message:(id)arg2;
- (void)logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3;
- (void)logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 context:(id)arg4;
- (void)logWithLevel:(long long)arg1 message:(id)arg2 context:(id)arg3 context:(id)arg4 context:(id)arg5;
- (void)logWithLevel:(long long)arg1 message:(id)arg2 contexts:(id)arg3;
- (id)monitoringDataForDispatchWithSamplePeriod:(double)arg1 lastSampledTimestamp:(double)arg2;
- (void)saveMonitoringDataToUserDefaults;
- (void)setLogLevel:(long long)arg1;

@end

