//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ASIdentifierManager, NSString;

@interface FIRAASIdentifierManager : NSObject
{
    ASIdentifierManager *_sharedIdentifierManager;
}

+ (id)sharedInstance;
+ (id)sharedManager;
- (void).cxx_destruct;
- (id)advertisingIdentifier;
@property(readonly, nonatomic) NSString *advertisingIdentifierString;
@property(readonly, nonatomic) _Bool hasLimitedAdTracking;
- (id)initWithIdentifierManager:(id)arg1;
- (_Bool)isAdvertisingTrackingEnabled;
@property(readonly, nonatomic) _Bool limitedAdTracking;

@end

