//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface FIRClearcutAccountData : NSObject
{
    NSMutableDictionary *_logSourceToWriter;
    NSString *_accountLogDirectory;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *accountLogDirectory; // @synthesize accountLogDirectory=_accountLogDirectory;
- (id)filenameWithCurrentTimeInDirectory:(id)arg1;
- (void)flushWriters;
- (id)initWithAccountLogDirectory:(id)arg1;
@property(readonly, copy, nonatomic) NSMutableDictionary *logSourceToWriter; // @synthesize logSourceToWriter=_logSourceToWriter;
- (void)removeWriterForLogSource:(int)arg1;
- (id)writerForLogSource:(int)arg1;

@end

