//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface FIRInstanceIDCheckinPreferences : NSObject
{
    _Bool _hasPreCachedAuthCredentials;
    NSString *_deviceID;
    NSString *_secretToken;
    NSString *_deviceDataVersion;
    NSString *_digest;
    NSString *_versionInfo;
    NSMutableDictionary *_gServicesData;
    long long _lastCheckinTimestampMillis;
}

+ (id)checkinDeviceIDFromKeychainContent:(id)arg1;
+ (id)checkinKeychainContent:(id)arg1 forIndex:(int)arg2;
+ (id)checkinSecretFromKeychainContent:(id)arg1;
+ (id)preferencesFromKeychainContents:(id)arg1;
- (void).cxx_destruct;
- (id)checkinKeychainContent;
- (id)checkinPlistContents;
@property(copy, nonatomic) NSString *deviceDataVersion; // @synthesize deviceDataVersion=_deviceDataVersion;
@property(copy, nonatomic) NSString *deviceID; // @synthesize deviceID=_deviceID;
@property(copy, nonatomic) NSString *digest; // @synthesize digest=_digest;
@property(retain, nonatomic) NSMutableDictionary *gServicesData; // @synthesize gServicesData=_gServicesData;
@property(nonatomic) _Bool hasPreCachedAuthCredentials; // @synthesize hasPreCachedAuthCredentials=_hasPreCachedAuthCredentials;
- (_Bool)hasValidCheckinInfo;
- (id)initWithDeviceID:(id)arg1 secretToken:(id)arg2;
@property(nonatomic) long long lastCheckinTimestampMillis; // @synthesize lastCheckinTimestampMillis=_lastCheckinTimestampMillis;
- (void)reset;
@property(copy, nonatomic) NSString *secretToken; // @synthesize secretToken=_secretToken;
@property(copy, nonatomic) NSString *versionInfo; // @synthesize versionInfo=_versionInfo;
- (void)updateWithCheckinPlistContents:(id)arg1;

@end

