//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FIRInstanceIDCachedToken : NSObject
{
    _Bool _shouldRefreshTokens;
    _Bool _shouldInvalidateAllTokens;
    NSString *_token;
    long long _status;
}

- (void).cxx_destruct;
- (id)initWithToken:(id)arg1 status:(long long)arg2;
- (_Bool)isValid;
@property(nonatomic) _Bool shouldInvalidateAllTokens; // @synthesize shouldInvalidateAllTokens=_shouldInvalidateAllTokens;
@property(nonatomic) _Bool shouldRefreshTokens; // @synthesize shouldRefreshTokens=_shouldRefreshTokens;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;

@end

