//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRInstanceIDLogger : NSObject
{
    id <FIRInstanceIDLogFilter> _filter;
    id <FIRInstanceIDLogWriter> _writer;
    id <FIRInstanceIDLogFormatter> _formatter;
}

+ (id)standardLogger;
- (void).cxx_destruct;
@property(retain, nonatomic) id <FIRInstanceIDLogFilter> filter; // @synthesize filter=_filter;
@property(retain, nonatomic) id <FIRInstanceIDLogFormatter> formatter; // @synthesize formatter=_formatter;
- (id)initWithFilter:(id)arg1 formatter:(id)arg2 writer:(id)arg3;
- (void)logFuncAssert:(const char *)arg1 msg:(id)arg2;
- (void)logFuncDebug:(const char *)arg1 msg:(id)arg2;
- (void)logFuncError:(const char *)arg1 msg:(id)arg2;
- (void)logFuncInfo:(const char *)arg1 msg:(id)arg2;
- (void)logInternalFunc:(const char *)arg1 format:(id)arg2 valist:(char *)arg3 level:(BOOL)arg4;
@property(retain, nonatomic) id <FIRInstanceIDLogWriter> writer; // @synthesize writer=_writer;

@end

