//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRInstanceIDCheckinService, FIRInstanceIDStore, NSMutableDictionary;

@interface FIRInstanceIDAuthService : NSObject
{
    _Bool _allowMissingAPNSToken;
    _Bool _isCheckinInProgress;
    int _checkinRetryCount;
    FIRInstanceIDStore *_store;
    FIRInstanceIDCheckinService *_checkinService;
    NSMutableDictionary *_IIDAuthTokenBySenderID;
    long long _lastCheckinTimestampSeconds;
    long long _nextScheduledCheckinIntervalSeconds;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *IIDAuthTokenBySenderID; // @synthesize IIDAuthTokenBySenderID=_IIDAuthTokenBySenderID;
@property(nonatomic) _Bool allowMissingAPNSToken; // @synthesize allowMissingAPNSToken=_allowMissingAPNSToken;
- (id)cachedIIDAuthTokenForAuthorizedEntity:(id)arg1;
- (long long)calculateNextCheckinRetryIntervalInSeconds;
- (id)checkinAuthToken;
- (id)checkinPreferences;
@property int checkinRetryCount; // @synthesize checkinRetryCount=_checkinRetryCount;
@property(retain, nonatomic) FIRInstanceIDCheckinService *checkinService; // @synthesize checkinService=_checkinService;
- (void)doCheckin:(_Bool)arg1;
- (void)fetchCheckinInfoWithHandler:(CDUnknownBlockType)arg1;
- (_Bool)hasValidCheckinInfo;
- (id)initWithCheckinService:(id)arg1 store:(id)arg2;
- (id)initWithStore:(id)arg1;
@property _Bool isCheckinInProgress; // @synthesize isCheckinInProgress=_isCheckinInProgress;
@property long long lastCheckinTimestampSeconds; // @synthesize lastCheckinTimestampSeconds=_lastCheckinTimestampSeconds;
@property long long nextScheduledCheckinIntervalSeconds; // @synthesize nextScheduledCheckinIntervalSeconds=_nextScheduledCheckinIntervalSeconds;
- (void)saveIIDAuthToken:(id)arg1 forAuthorizedEntity:(id)arg2;
- (void)scheduleCheckin:(_Bool)arg1;
@property(retain, nonatomic) FIRInstanceIDStore *store; // @synthesize store=_store;
- (void)stopCheckinRequest;

@end

