//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRInstanceIDRegistrar, FIRInstanceIDStore;

@interface FIRInstanceIDTokenManager : NSObject
{
    _Bool _allowMissingAPNSToken;
    FIRInstanceIDRegistrar *_registrar;
    FIRInstanceIDStore *_instanceIDStore;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool allowMissingAPNSToken; // @synthesize allowMissingAPNSToken=_allowMissingAPNSToken;
- (_Bool)deleteAllTokensLocallyWithError:(id *)arg1;
- (void)deleteAllTokensWithKeyPair:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)deleteTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 keyPair:(id)arg3 handler:(CDUnknownBlockType)arg4;
- (void)fetchNewTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 keyPair:(id)arg3 options:(id)arg4 handler:(CDUnknownBlockType)arg5;
- (id)init;
@property(retain, nonatomic) FIRInstanceIDStore *instanceIDStore; // @synthesize instanceIDStore=_instanceIDStore;
- (_Bool)invalidateCachedToken:(id)arg1 withAuthorizedEntity:(id)arg2 scope:(id)arg3 options:(id)arg4;
@property(retain, nonatomic) FIRInstanceIDRegistrar *registrar; // @synthesize registrar=_registrar;
- (_Bool)shouldResetTokenOnAPNSToken:(id)arg1 isSandbox:(_Bool)arg2;
- (_Bool)shouldResetTokenOnAppVersion;
- (id)tokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 options:(id)arg3;

@end

