//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface FIRInstanceIDKeyPair : NSObject
{
    struct __SecKey *_privateKey;
    struct __SecKey *_publicKey;
    NSData *_publicKeyData;
    NSData *_privateKeyData;
}

+ (id)appIdentityWithKeyPair:(id)arg1;
+ (struct __SecKey *)cachedKeyRefWithTag:(id)arg1;
+ (_Bool)deleteKeyPairWithPrivateTag:(id)arg1 publicTag:(id)arg2 error:(id *)arg3;
+ (id)generateRSA2048KeyPairWithPrivateTag:(id)arg1 publicTag:(id)arg2 error:(id *)arg3;
+ (id)keyDataWithTag:(id)arg1;
+ (id)keyPairForPrivateKeyTag:(id)arg1 publicKeyTag:(id)arg2 error:(id *)arg3;
+ (id)queryDictWithTag:(id)arg1 addReturnAttr:(_Bool)arg2 withTypeData:(_Bool)arg3;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (id)initWithPrivateKey:(struct __SecKey *)arg1 publicKey:(struct __SecKey *)arg2 publicKeyData:(id)arg3 privateKeyData:(id)arg4;
- (_Bool)isValid;
- (struct __SecKey *)privateKey;
@property(retain, nonatomic) NSData *privateKeyData; // @synthesize privateKeyData=_privateKeyData;
- (struct __SecKey *)publicKey;
@property(retain, nonatomic) NSData *publicKeyData; // @synthesize publicKeyData=_publicKeyData;

@end

