//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FIRInstanceIDAuthKeychain : NSObject
{
    NSString *_generic;
    NSString *_identifier;
}

+ (id)keychainQueryForService:(id)arg1 account:(id)arg2 generic:(id)arg3;
+ (void)printKeychainItems;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *generic; // @synthesize generic=_generic;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1;
- (id)keychainQueryForService:(id)arg1 account:(id)arg2;
- (id)passwordForService:(id)arg1 account:(id)arg2 error:(id *)arg3;
- (_Bool)removeAllItemsWithError:(id *)arg1;
- (_Bool)removePasswordForService:(id)arg1 account:(id)arg2 error:(id *)arg3;
- (_Bool)setPassword:(id)arg1 forService:(id)arg2 accessibility:(void *)arg3 account:(id)arg4 error:(id *)arg5;

@end

