//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRInstanceIDAuthKeychain;

@interface FIRInstanceIDTokenStore : NSObject
{
    FIRInstanceIDAuthKeychain *_keychain;
}

+ (id)actualTokenFromCachedToken:(id)arg1;
+ (id)cacheKeyForAuthorizedEntity:(id)arg1 scope:(id)arg2;
+ (long long)cacheTimeForCachedToken:(id)arg1;
+ (id)cacheValueForToken:(id)arg1;
+ (id)defaultStore;
- (void).cxx_destruct;
- (long long)cacheTimeForTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2;
- (id)init;
- (id)initWithKeychain:(id)arg1;
@property(retain, nonatomic) FIRInstanceIDAuthKeychain *keychain; // @synthesize keychain=_keychain;
- (_Bool)removeAllTokensWithError:(id *)arg1;
- (_Bool)removeGCMTokensWithError:(id *)arg1;
- (_Bool)removeTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 error:(id *)arg3;
- (_Bool)saveToken:(id)arg1 withAuthorizedEntity:(id)arg2 scope:(id)arg3;
- (id)tokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2;

@end

