//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@interface FIRInstanceIDConfig : NSObject <NSCopying, NSMutableCopying>
{
    BOOL _logLevel;
    _Bool _allowMissingAPNSToken;
}

+ (id)defaultConfig;
- (_Bool)allowGCMRegistrationWithoutAPNSToken;
@property(nonatomic) _Bool allowMissingAPNSToken; // @synthesize allowMissingAPNSToken=_allowMissingAPNSToken;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithLogLevel:(BOOL)arg1;
@property(nonatomic) BOOL logLevel; // @synthesize logLevel=_logLevel;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (void)setAllowGCMRegistrationWithoutAPNSToken:(_Bool)arg1;

@end

