//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface FIRInstanceIDBackupExcludedPlist : NSObject
{
    _Bool _fileInApplicationSupport;
    NSDictionary *_cachedPlistContents;
    NSString *_fileName;
    NSString *_applicationSupportSubDirectory;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *applicationSupportSubDirectory; // @synthesize applicationSupportSubDirectory=_applicationSupportSubDirectory;
@property(retain, nonatomic) NSDictionary *cachedPlistContents; // @synthesize cachedPlistContents=_cachedPlistContents;
- (id)contentAsDictionary;
- (_Bool)deleteFile:(id *)arg1;
- (_Bool)doesFileExist;
- (_Bool)doesFileExistInDirectory:(unsigned long long)arg1;
@property(nonatomic) _Bool fileInApplicationSupport; // @synthesize fileInApplicationSupport=_fileInApplicationSupport;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (id)initWithFileName:(id)arg1 applicationSupportSubDirectory:(id)arg2;
- (void)moveToApplicationSupportSubDirectory;
- (_Bool)moveToApplicationSupportSubDirectory:(id)arg1;
- (id)pathWithName:(id)arg1 inDirectory:(unsigned long long)arg2;
- (unsigned long long)plistDirectory;
- (id)plistPathInDirectory:(unsigned long long)arg1;
- (_Bool)writeDictionary:(id)arg1 error:(id *)arg2;

@end

