//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDictionary, NSString;

@interface FIROptions : NSObject <NSCopying>
{
    NSDictionary *_analyticsOptionsDictionary;
    long long _createAnalyticsOptionsDictionaryOnce;
    _Bool _usingOptionsFromDefaultPlist;
    NSString *_deepLinkURLScheme;
    NSDictionary *_optionsDictionary;
}

+ (id)defaultOptions;
+ (id)defaultOptionsDictionary;
+ (id)plistFilePathWithName:(id)arg1;
+ (void)resetDefaultOptions;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *APIKey;
@property(readonly, copy, nonatomic) NSString *GCMSenderID;
@property(readonly, nonatomic) NSDictionary *analyticsOptionsDictionary;
@property(readonly, copy, nonatomic) NSString *androidClientID;
@property(readonly, copy, nonatomic) NSString *clientID;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSString *databaseURL;
@property(copy, nonatomic) NSString *deepLinkURLScheme; // @synthesize deepLinkURLScheme=_deepLinkURLScheme;
@property(readonly, copy, nonatomic) NSString *googleAppID;
- (id)initInternalWithOptionsDictionary:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithGoogleAppID:(id)arg1 bundleID:(id)arg2 GCMSenderID:(id)arg3 APIKey:(id)arg4 clientID:(id)arg5 trackingID:(id)arg6 androidClientID:(id)arg7 databaseURL:(id)arg8 storageBucket:(id)arg9 deepLinkURLScheme:(id)arg10;
@property(readonly, nonatomic) _Bool isAnalyticsCollectionDeactivated;
@property(readonly, nonatomic) _Bool isAnalyticsCollectionEnabled;
@property(readonly, nonatomic) _Bool isAnalyticsEnabled;
@property(readonly, nonatomic) _Bool isMeasurementEnabled;
@property(readonly, nonatomic) _Bool isSignInEnabled;
@property(readonly, copy, nonatomic) NSString *libraryVersionID;
@property(retain, nonatomic) NSDictionary *optionsDictionary; // @synthesize optionsDictionary=_optionsDictionary;
@property(nonatomic) _Bool usingOptionsFromDefaultPlist; // @synthesize usingOptionsFromDefaultPlist=_usingOptionsFromDefaultPlist;
@property(readonly, copy, nonatomic) NSString *storageBucket;
@property(readonly, copy, nonatomic) NSString *trackingID;

@end

