//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView, UIViewController;

@interface GADAdViewState : NSObject
{
    UIView *_superview;
    id <GADAdViewDelegate> _delegate;
    UIViewController *_viewController;
    unsigned long long _autoresizingMask;
    struct CGRect _frame;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long autoresizingMask; // @synthesize autoresizingMask=_autoresizingMask;
@property(nonatomic) __weak id <GADAdViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) UIView *superview; // @synthesize superview=_superview;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;

@end

