//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADAdViewActiveViewReporter : NSObject
{
    _Bool _reporting;
    id <GADAdViewActiveViewMonitoring> _observer;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <GADAdViewActiveViewMonitoring> observer; // @synthesize observer=_observer;
@property(readonly, nonatomic) _Bool reporting; // @synthesize reporting=_reporting;
- (void)start;
- (void)stop;

@end

