//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADViewController.h"

@class GADAdAppAdViewDelegate, GADAdView, NSString, NSURL, UIButton, UIViewController;

@interface GADAdAppViewController : GADViewController
{
    _Bool _viewWasConfigured;
    NSURL *_URLToLoad;
    NSString *_HTMLToLoad;
    NSURL *_HTMLBaseURLToLoad;
    NSString *_originalAudioSessionCategory;
    _Bool _viewHasAppearedAtLeastOnce;
    _Bool _orientationNotifiedToTheAdViewAtLeastOnce;
    _Bool _useCustomClose;
    _Bool _adOrientationsOverridesLockedOrientation;
    long long _customClosePosition;
    GADAdView *_adView;
    UIViewController *_hostViewController;
    long long _forcedAdOrientation;
    UIButton *_closeButton;
    unsigned long long _adOrientations;
    double _orientationUpdateAnimationDuration;
    GADAdAppAdViewDelegate *_adViewDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long adOrientations; // @synthesize adOrientations=_adOrientations;
@property(nonatomic) _Bool adOrientationsOverridesLockedOrientation; // @synthesize adOrientationsOverridesLockedOrientation=_adOrientationsOverridesLockedOrientation;
@property(retain, nonatomic) GADAdView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) GADAdAppAdViewDelegate *adViewDelegate; // @synthesize adViewDelegate=_adViewDelegate;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
- (void)closeButtonPressed:(id)arg1;
- (void)configureView;
@property(nonatomic) long long customClosePosition; // @synthesize customClosePosition=_customClosePosition;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
@property(nonatomic) long long forcedAdOrientation; // @synthesize forcedAdOrientation=_forcedAdOrientation;
@property(readonly, nonatomic) UIViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
- (id)init;
- (id)initWithAdView:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)isLoaded;
- (void)load:(id)arg1;
- (void)loadHTML:(id)arg1 baseURL:(id)arg2;
@property(nonatomic) double orientationUpdateAnimationDuration; // @synthesize orientationUpdateAnimationDuration=_orientationUpdateAnimationDuration;
- (void)positionMRAIDCloseButton;
- (void)relinquishScreenWithCompletion:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool useCustomClose; // @synthesize useCustomClose=_useCustomClose;
- (_Bool)shouldDismissOnApplicationEnteringForeground;
- (void)updateCloseButtonVisibilityAndImage;
- (void)viewChangedToOrientation:(long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

@end

