//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADAdConfiguration, NSDictionary, NSObject<OS_dispatch_queue>, NSSet;

@interface GADAdLoaderConfiguration : NSObject
{
    NSDictionary *_adClassRequestParameters;
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADAdConfiguration *_adConfiguration;
    NSSet *_adTypeClasses;
    NSSet *_adTypes;
}

- (void).cxx_destruct;
@property(copy) NSDictionary *adClassRequestParameters;
@property(readonly, copy, nonatomic) NSSet *adTypeClasses; // @synthesize adTypeClasses=_adTypeClasses;
@property(readonly, copy, nonatomic) NSSet *adTypes; // @synthesize adTypes=_adTypes;
- (id)initWithAdTypes:(id)arg1 options:(id)arg2;
@property(readonly, copy, nonatomic) NSDictionary *options;
- (id)requestParameters;

@end

