//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADViewMonitorDelegate.h"

@class GADViewMonitor, NSString;

@interface GADAdExposureMonitor : NSObject <GADViewMonitorDelegate>
{
    NSString *_adUnitID;
    GADViewMonitor *_viewMonitor;
    _Bool _adUnitExposureBegan;
}

- (void).cxx_destruct;
- (void)finishMonitoring;
- (id)initWithView:(id)arg1 adUnitID:(id)arg2;
- (void)startMonitoring;
- (void)viewMonitorDidRefresh:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

