//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDecimalNumber, NSString;

@interface GADAdReward : NSObject
{
    NSString *_type;
    NSDecimalNumber *_amount;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDecimalNumber *amount; // @synthesize amount=_amount;
- (id)init;
- (id)initWithRewardDictionary:(id)arg1;
- (id)initWithRewardType:(id)arg1 rewardAmount:(id)arg2;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;

@end

