//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADAdMediationDelegate.h"
#import "GADSlotAdLoadDelegate.h"
#import "GADSlotAdResponseDelegate.h"
#import "GADSlotDelegate.h"

@class GADAdLoaderConfiguration, GADSlot, NSMutableArray, NSString, UIViewController;

@interface GADAdLoader : NSObject <GADAdMediationDelegate, GADSlotAdLoadDelegate, GADSlotAdResponseDelegate, GADSlotDelegate>
{
    GADSlot *_slot;
    id <GADAdLoaderDelegate> _delegate;
    NSString *_adUnitID;
    GADAdLoaderConfiguration *_adLoaderConfiguration;
    UIViewController *_rootViewController;
    NSMutableArray *_appEventAdLoaders;
    NSMutableArray *_adPreprocessors;
    NSMutableArray *_nativeAds;
}

- (void).cxx_destruct;
- (void)ad:(id)arg1 processMediatedAd:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)adDidFinishLoadingAssets:(id)arg1;
@property(retain, nonatomic) GADAdLoaderConfiguration *adLoaderConfiguration; // @synthesize adLoaderConfiguration=_adLoaderConfiguration;
- (id)adLoaderConfigurationForAd:(id)arg1 networkConfiguration:(id)arg2;
@property(readonly, nonatomic) NSMutableArray *adPreprocessors; // @synthesize adPreprocessors=_adPreprocessors;
@property(readonly, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
@property(readonly, nonatomic) NSMutableArray *appEventAdLoaders; // @synthesize appEventAdLoaders=_appEventAdLoaders;
- (struct CGRect)bounds;
@property(nonatomic) __weak id <GADAdLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)frame;
- (void)handleFailedRequestWithRequestError:(id)arg1;
- (id)init;
- (id)initWithAdUnitID:(id)arg1 rootViewController:(id)arg2 adTypes:(id)arg3 options:(id)arg4;
- (void)loadAssetsForNativeAd:(id)arg1;
- (void)loadRequest:(id)arg1;
- (id)mediationConnectorForConfiguration:(id)arg1 networkConfiguration:(id)arg2;
@property(readonly, nonatomic) NSMutableArray *nativeAds; // @synthesize nativeAds=_nativeAds;
@property(readonly, nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void)slot:(id)arg1 didFailToLoadAdContentWithError:(id)arg2;
- (_Bool)slot:(id)arg1 shouldProcessAdResponse:(id)arg2 error:(id *)arg3;
- (void)slot:(id)arg1 willProcessMediatedAdResponse:(id)arg2;
- (void)slotFinishedLoadingAdContent:(id)arg1;
- (id)validAdSizes;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

