//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADAdType : NSObject
{
    _Bool _isRewardBasedVideoAd;
    _Bool _isInterstitial;
    struct GADAdSize _adSize;
}

+ (id)bannerAdTypeForSize:(struct GADAdSize)arg1;
+ (id)interstitialAdType;
@property(nonatomic) struct GADAdSize adSize; // @synthesize adSize=_adSize;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (id)initForInterstitial;
- (id)initForRewardBasedVideoAd;
- (id)initWithAdSize:(struct GADAdSize)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool isInterstitial; // @synthesize isInterstitial=_isInterstitial;
- (_Bool)isRewardBasedVideoAd;
- (_Bool)isValid;

@end

