//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FIRAAdExposureReporter, FIRAIdentifiers, FIRAScreenViewReporter, FIRAnalytics;

@interface GADAnalytics : NSObject
{
    FIRAAdExposureReporter *_adExposureReporter;
    FIRAIdentifiers *_analyticsIdentifiers;
    FIRAnalytics *_analytics;
    FIRAScreenViewReporter *_screenViewReporter;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)adEventID;
- (id)appInstanceID;
- (void)beginAdUnitExposure:(id)arg1;
- (void)endAdUnitExposure:(id)arg1;
- (void)getScreenName:(id *)arg1 screenClass:(id *)arg2;
- (id)googleAppID;
- (id)init;
- (void)logEventWithName:(id)arg1 adEventID:(id)arg2;
- (void)setScreenName:(id)arg1 screenClass:(id)arg2;

@end

