//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface GADClearcutConfig : NSObject
{
    _Bool _enabled;
    _Bool _useJSCore;
    double _beaconInterval;
    NSURL *_scriptURL;
    NSString *_version;
    NSURL *_baseURL;
    long long _maxBufferedCommandSize;
    NSString *_JSConfig;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *JSConfig; // @synthesize JSConfig=_JSConfig;
@property(readonly, copy, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(readonly, nonatomic) double beaconInterval; // @synthesize beaconInterval=_beaconInterval;
@property(readonly, nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (id)init;
@property(readonly, nonatomic) long long maxBufferedCommandSize; // @synthesize maxBufferedCommandSize=_maxBufferedCommandSize;
@property(readonly, copy, nonatomic) NSURL *scriptURL; // @synthesize scriptURL=_scriptURL;
@property(readonly, nonatomic) _Bool useJSCore; // @synthesize useJSCore=_useJSCore;
@property(readonly, copy, nonatomic) NSString *version; // @synthesize version=_version;

@end

