//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GADCrashReporter : NSObject
{
    CDUnknownFunctionPointerType _previousUncaughtExceptionHandler;
    _Bool _reportingEnabled;
}

+ (id)sharedInstance;
- (void)handleUncaughtException:(id)arg1;
- (id)init;
- (void)reportUncaughtException:(id)arg1;
@property(nonatomic) _Bool reportingEnabled; // @synthesize reportingEnabled=_reportingEnabled;

@end

