//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADCSIConfiguration;

@interface GADCSIReporter : NSObject
{
    GADCSIConfiguration *_configuration;
}

- (void).cxx_destruct;
- (id)URLForTimeRecorder:(id)arg1;
- (id)init;
- (id)initWithConfiguration:(id)arg1;
- (void)reportTimeRecorder:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

