//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, NSString;

@interface GADCustomEventRequest : NSObject
{
    _Bool _userHasLocation;
    _Bool _isTesting;
    long long _userGender;
    NSDate *_userBirthday;
    double _userLatitude;
    double _userLongitude;
    double _userLocationAccuracyInMeters;
    NSString *_userLocationDescription;
    NSArray *_userKeywords;
    NSDictionary *_additionalParameters;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *additionalParameters; // @synthesize additionalParameters=_additionalParameters;
- (id)initWithConnector:(id)arg1;
@property(readonly, nonatomic) _Bool isTesting; // @synthesize isTesting=_isTesting;
@property(readonly, copy, nonatomic) NSDate *userBirthday; // @synthesize userBirthday=_userBirthday;
@property(readonly, nonatomic) long long userGender; // @synthesize userGender=_userGender;
@property(readonly, nonatomic) _Bool userHasLocation; // @synthesize userHasLocation=_userHasLocation;
@property(readonly, copy, nonatomic) NSArray *userKeywords; // @synthesize userKeywords=_userKeywords;
@property(readonly, nonatomic) double userLatitude; // @synthesize userLatitude=_userLatitude;
@property(readonly, nonatomic) double userLocationAccuracyInMeters; // @synthesize userLocationAccuracyInMeters=_userLocationAccuracyInMeters;
@property(readonly, copy, nonatomic) NSString *userLocationDescription; // @synthesize userLocationDescription=_userLocationDescription;
@property(readonly, nonatomic) double userLongitude; // @synthesize userLongitude=_userLongitude;

@end

