//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADBinaryHeap, NSString;

@interface GADContent : NSObject
{
    long long _contentAgeWeight;
    long long _contentLengthWeight;
    unsigned long long _contentTotalLength;
    GADBinaryHeap *_heap;
    unsigned long long _maximumShingleCount;
    unsigned long long _minimumParagraphLength;
    unsigned long long _shingleLength;
    NSString *_fingerprint;
    long long _score;
    unsigned long long _sequenceNumber;
}

- (void).cxx_destruct;
- (void)applyRollingHashToTokens:(id)arg1 baseHash:(unsigned long long)arg2;
- (void)deductServedPenalty;
@property(readonly, nonatomic) NSString *fingerprint; // @synthesize fingerprint=_fingerprint;
- (id)init;
- (id)initWithSequenceNumber:(unsigned long long)arg1;
@property(readonly, nonatomic) long long score; // @synthesize score=_score;
- (void)selectShinglesFromTokens:(id)arg1;
@property(readonly, nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
- (id)shingleHash;
- (void)updateContentWithText:(id)arg1;
- (void)updateHeapWithHash:(unsigned long long)arg1 shingle:(id)arg2;

@end

