//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CTTelephonyNetworkInfo, GADNetwork, MPVolumeView, NSArray, NSDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSString, UISlider;

@interface GADDevice : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    id <NSObject> _radioAccessTechnologyChangeObserver;
    long long _statusBarOrientation;
    unsigned long long _supportedInterfaceOrientationsForKeyWindow;
    struct CGRect _standardizedMainScreenPortraitBounds;
    struct CGRect _standardizedMainScreenLandscapeBounds;
    _Bool _userInterfaceIdiomIsPhone;
    unsigned long long _bookstores;
    float _audioVolume;
    NSArray *_audioRoutePortNames;
    CTTelephonyNetworkInfo *_telephonyNetworkInfo;
    NSDictionary *_infoPlist;
    _Bool _hasCachedStaticParameters;
    struct CGSize _standardizedOrientedKeyWindowSize;
    MPVolumeView *_volumeView;
    UISlider *_volumeSliderView;
    NSString *_lastKnownRadioAccessTechnology;
    NSString *_radioAccessTechnology;
    NSString *_mobileCountryCode;
    NSString *_mobileNetworkCode;
    NSString *_userAgentString;
    NSString *_deviceModel;
    NSString *_systemVersion;
    GADNetwork *_network;
    double _mainScreenDensity;
    _Bool _isOtherAudioPlaying;
    NSNumber *_shouldSilenceAudioValue;
    _Bool _canText;
    _Bool _canMakePhoneCalls;
    CDStruct_f6aba300 _operatingSystemVersion;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)OSIsSupported;
@property(readonly, copy, nonatomic) NSArray *audioRoutePortNames;
@property(readonly, nonatomic) float audioVolume;
- (id)baseSDKVersion;
- (id)cacheDirectoryURLWithError:(id *)arg1;
- (void)cacheStaticParameters;
@property(readonly, nonatomic) _Bool canMakePhoneCalls; // @synthesize canMakePhoneCalls=_canMakePhoneCalls;
- (id)canOpenURLs:(id)arg1;
@property(readonly, nonatomic) _Bool canText; // @synthesize canText=_canText;
- (void)dealloc;
- (id)deviceIdentifier;
@property(readonly, nonatomic) NSString *deviceModel;
@property(readonly, nonatomic) NSString *deviceSubmodel;
- (void)disableRadioAccessTechnologyChecking;
- (id)diskUsageStatisticsWithError:(id *)arg1;
- (void)enableRadioAccessTechnologyChecking;
- (id)init;
- (_Bool)isOSAtLeastMajor:(long long)arg1 minor:(long long)arg2 patch:(long long)arg3;
@property(readonly, nonatomic) _Bool isOtherAudioPlaying; // @synthesize isOtherAudioPlaying=_isOtherAudioPlaying;
- (_Bool)isSimulator;
@property(readonly, nonatomic) _Bool jailbroken;
- (id)lastKnownRadioAccessTechnology;
@property(readonly, nonatomic) _Bool limitAdTracking;
@property(readonly, copy, nonatomic) NSString *limitAdTrackingString;
@property(readonly, nonatomic) NSString *locale;
@property(readonly, nonatomic) double mainScreenDensity;
@property(copy) NSString *mobileCountryCode;
@property(copy) NSString *mobileNetworkCode;
@property(readonly, nonatomic) GADNetwork *network; // @synthesize network=_network;
@property(readonly, nonatomic) CDStruct_f6aba300 operatingSystemVersion; // @synthesize operatingSystemVersion=_operatingSystemVersion;
@property(readonly, nonatomic) _Bool orientationLandscape;
- (id)parameters;
@property(copy) NSString *radioAccessTechnology;
- (id)rawDeviceIdentifier;
@property(copy) NSString *userAgentString;
@property(readonly, nonatomic) NSNumber *shouldSilenceAudioValue; // @synthesize shouldSilenceAudioValue=_shouldSilenceAudioValue;
@property(readonly, nonatomic) struct CGRect standardizedLandscapeScreenBounds;
@property(readonly, nonatomic) struct CGRect standardizedOrientedApplicationFrame;
@property(readonly, nonatomic) struct CGSize standardizedOrientedKeyWindowSize;
@property(readonly, nonatomic) struct CGRect standardizedOrientedScreenBounds;
@property(readonly, nonatomic) struct CGSize standardizedPortraitKeyWindowSize;
@property(readonly, nonatomic) struct CGRect standardizedPortraitScreenBounds;
@property(readonly, nonatomic) NSString *systemVersion;
- (id)temporaryDirectoryURLWithCreation:(_Bool)arg1 error:(id *)arg2;
- (id)temporaryPathWithCreation:(_Bool)arg1;
- (void)updateAudio;
- (void)updateAudioPortNames;
- (void)updateAudioVolume;
- (void)updateBookstores;
- (void)updateDynamicParameters;
- (void)updateMobileCarrierInformation;
- (void)updateOperatingSystemVersionProperties;
- (void)updateOrientation;
- (void)updateOrientedKeyWindowSize;

@end

