//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADInAppPurchaseDelegate.h"
#import "SKPaymentTransactionObserver.h"

@class NSMutableSet, NSString;

@interface GADDefaultInAppPurchaseFlow : NSObject <SKPaymentTransactionObserver, GADInAppPurchaseDelegate>
{
    NSMutableSet *_activeInAppPurchases;
    id <GADDefaultInAppPurchaseDelegate> _defaultInAppPurchaseDelegate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)completeTransaction:(id)arg1;
- (id)dequeueInAppPurchaseForTransaction:(id)arg1;
- (void)didReceiveInAppPurchase:(id)arg1;
- (void)disableDefaultPurchaseFlow;
- (void)enableDefaultPurchaseFlowWithDelegate:(id)arg1;
- (void)enqueueInAppPurchase:(id)arg1;
- (void)failedTransaction:(id)arg1;
- (id)init;
@property(readonly, nonatomic, getter=isDefaultPurchaseFlowEnabled) _Bool defaultPurchaseFlowEnabled;
- (void)notifyUserOfUnavailableProduct;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)purchaseProduct:(id)arg1 inAppPurchase:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

