//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADAdAppViewController.h"

@class NSString;

@interface GADInterstitialViewController : GADAdAppViewController
{
    NSString *_previousScreenName;
    NSString *_previousScreenClass;
}

- (void).cxx_destruct;
- (void)finishAppearing;
- (void)finishDismissal;
- (id)initWithAdView:(id)arg1;
- (id)initWithSlot:(id)arg1;
- (_Bool)isLoaded;
- (void)presentFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)relinquishScreenWithCompletion:(CDUnknownBlockType)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

