//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADTransparentOverlayPresenter.h"

@class GADMRAIDResizeProperties, UIView;

@interface GADMRAIDResizeOverlayPresenter : GADTransparentOverlayPresenter
{
    _Bool _dismissToDefaultState;
    GADMRAIDResizeProperties *_resizeProperties;
    id <GADMRAIDEventHandling> _MRAIDEventHandler;
    UIView *_referenceView;
}

+ (struct CGRect)adjustedContentFrame:(struct CGRect)arg1 inBounds:(struct CGRect)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak id <GADMRAIDEventHandling> MRAIDEventHandler; // @synthesize MRAIDEventHandler=_MRAIDEventHandler;
- (void)composeTransparentInterstitialViewsForPresentation;
- (struct CGRect)contentFrame;
@property(nonatomic) _Bool dismissToDefaultState; // @synthesize dismissToDefaultState=_dismissToDefaultState;
- (id)init;
- (id)initWithReferenceView:(id)arg1;
- (_Bool)isReadyToPresent;
@property(retain, nonatomic) UIView *referenceView; // @synthesize referenceView=_referenceView;
- (void)repositionContentIfNeeded;
@property(retain, nonatomic) GADMRAIDResizeProperties *resizeProperties; // @synthesize resizeProperties=_resizeProperties;
- (_Bool)resizePropertiesAreValid:(id)arg1 relativeToView:(id)arg2;
- (void)updateTransparentInterstitialOrientation;

@end

