//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADSlotAdEventDelegate.h"
#import "GADSlotAdLoadDelegate.h"
#import "GADSlotDelegate.h"

@class GADAdViewVideoController, GADNativeAdImage, GADSlot, GADVideoOptions, NSDictionary, NSString, UIImageView;

@interface GADMediaContent : NSObject <GADSlotAdEventDelegate, GADSlotAdLoadDelegate, GADSlotDelegate>
{
    NSDictionary *_configuration;
    GADNativeAdImage *_placeholderImage;
    UIImageView *_placeholderImageView;
    _Bool _hasLoaded;
    CDUnknownBlockType _completionHandler;
    GADVideoOptions *_videoOptions;
    id <GADMediaContentDelegate> _delegate;
    GADSlot *_slot;
}

+ (id)videoSupportURL;
- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <GADMediaContentDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)frameInInterface;
- (void)handleJavaScriptLoadedNotification:(id)arg1;
- (id)initWithVideoDictionary:(id)arg1 placeholderImage:(id)arg2 videoOptions:(id)arg3;
- (void)loadVideoWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)mediaView;
- (void)notifyVideoLoadCompletedWithError:(id)arg1;
@property(readonly, nonatomic) GADSlot *slot; // @synthesize slot=_slot;
- (void)slot:(id)arg1 didFailToLoadAdContentWithError:(id)arg2;
- (void)slot:(id)arg1 didLoadVideoWithSize:(struct CGSize)arg2;
- (void)slotFinishedLoadingAdContent:(id)arg1;
@property(readonly, nonatomic) GADAdViewVideoController *videoController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

