//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADMInternalAdNetworkConnector.h"
#import "GADMediationAdRequestInternal.h"

@class GADAdLoaderConfiguration, GADMAdManager, GADMAdNetworkConfig, GADMConfig, NSDictionary, NSString;

@interface GADMAdNetworkConnector : NSObject <GADMInternalAdNetworkConnector, GADMediationAdRequestInternal>
{
    NSDictionary *_strippedCredentials;
    _Bool _isLocationShared;
    _Bool _didNetworkRefresh;
    _Bool _clicked;
    GADMAdNetworkConfig *_networkConfig;
    GADMAdManager *_adManager;
    GADMConfig *_mediationConfig;
    GADAdLoaderConfiguration *_adLoaderConfiguration;
    id <GADMAdNetworkAdapter> _adapter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GADAdLoaderConfiguration *adLoaderConfiguration; // @synthesize adLoaderConfiguration=_adLoaderConfiguration;
@property(nonatomic) __weak GADMAdManager *adManager; // @synthesize adManager=_adManager;
- (struct CGSize)adSize;
@property(retain, nonatomic) id <GADMAdNetworkAdapter> adapter; // @synthesize adapter=_adapter;
- (void)adapter:(id)arg1 clickDidOccurInBanner:(id)arg2;
- (void)adapter:(id)arg1 didFailAd:(id)arg2;
- (void)adapter:(id)arg1 didFailInterstitial:(id)arg2;
- (void)adapter:(id)arg1 didReceiveAdView:(id)arg2;
- (void)adapter:(id)arg1 didReceiveInterstitial:(id)arg2;
- (void)adapter:(id)arg1 didReceiveMediatedNativeAd:(id)arg2;
- (void)adapterDidDismissFullScreenModal:(id)arg1;
- (void)adapterDidDismissInterstitial:(id)arg1;
- (void)adapterDidGetAdClick:(id)arg1;
- (void)adapterDidReceiveInterstitial:(id)arg1;
- (id)adapterNames;
- (id)adapterVersion;
- (void)adapterWillDismissFullScreenModal:(id)arg1;
- (void)adapterWillDismissInterstitial:(id)arg1;
- (void)adapterWillLeaveApplication:(id)arg1;
- (void)adapterWillPresentFullScreenModal:(id)arg1;
- (void)adapterWillPresentInterstitial:(id)arg1;
- (void)askAdapterToStopBeingDelegate;
- (_Bool)autoClickProtectionEnabled;
- (id)childDirectedTreatment;
- (id)credentials;
- (double)croppedContentThreshold;
- (id)currentAdapterName;
- (void)dealloc;
@property(nonatomic) _Bool didNetworkRefresh; // @synthesize didNetworkRefresh=_didNetworkRefresh;
- (id)extras;
- (void)getAdFromAdapterWithType:(id)arg1;
- (id)init;
- (id)initWithConfig:(id)arg1 networkConfig:(id)arg2;
- (id)inlineAd;
@property(nonatomic, getter=isClicked) _Bool clicked; // @synthesize clicked=_clicked;
@property(retain, nonatomic) GADMConfig *mediationConfig; // @synthesize mediationConfig=_mediationConfig;
@property(retain, nonatomic) GADMAdNetworkConfig *networkConfig; // @synthesize networkConfig=_networkConfig;
- (id)networkExtras;
- (id)networkExtrasForClass:(Class)arg1;
- (void)pingMediationURLs:(id)arg1 defaultURL:(id)arg2 durations:(id)arg3 exitCodes:(id)arg4 fillStatus:(id)arg5;
- (id)publisherId;
- (void)reportClick;
- (void)reportFill;
- (void)reportImpression;
- (void)setUpAdapter;
- (id)slot;
- (_Bool)testMode;
- (id)userBirthday;
- (long long)userGender;
- (_Bool)userHasLocation;
- (id)userKeywords;
- (double)userLatitude;
- (id)userLocation;
- (double)userLocationAccuracyInMeters;
- (id)userLocationDescription;
- (double)userLongitude;
- (id)userRequestAgent;
- (id)viewControllerForPresentingModalView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

