//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADMAdNetworkConnector.h"

#import "GADImpressionMonitorDelegate.h"

@class GADImpressionMonitor, NSMutableArray, NSString;

@interface GADMAdNetworkConnectorBanner : GADMAdNetworkConnector <GADImpressionMonitorDelegate>
{
    GADImpressionMonitor *_impressionMonitor;
    _Bool _didNetworkReturn;
    NSMutableArray *_queuedAppEvents;
}

- (void).cxx_destruct;
- (void)adapter:(id)arg1 didFailAd:(id)arg2;
- (void)adapter:(id)arg1 didFailInterstitial:(id)arg2;
- (void)adapter:(id)arg1 didReceiveAdView:(id)arg2;
- (void)adapter:(id)arg1 didReceiveAppEvent:(id)arg2 withInfo:(id)arg3;
- (void)adapterDidDismissFullScreenModal:(id)arg1;
- (void)adapterDidDismissInterstitial:(id)arg1;
- (void)adapterDidReceiveInterstitial:(id)arg1;
- (void)adapterWillDismissFullScreenModal:(id)arg1;
- (void)adapterWillDismissInterstitial:(id)arg1;
- (void)adapterWillLeaveApplication:(id)arg1;
- (void)adapterWillPresentFullScreenModal:(id)arg1;
- (void)adapterWillPresentInterstitial:(id)arg1;
@property(nonatomic) _Bool didNetworkReturn; // @synthesize didNetworkReturn=_didNetworkReturn;
- (void)getAdFromAdapterWithType:(id)arg1;
- (void)impressionMonitorDidMonitorImpression:(id)arg1;
@property(readonly, nonatomic) NSMutableArray *queuedAppEvents; // @synthesize queuedAppEvents=_queuedAppEvents;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

