//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface GADMConfig : NSObject
{
    NSMutableArray *_adNetworkConfigs;
    _Bool _allowPublisherRenderedAttribution;
    double _refreshInterval;
    long long _bannerAnimationType;
    double _adNetworkTimeout;
    long long _impressionDefinition;
    NSArray *_impressionURLs;
    NSArray *_clickURLs;
    NSArray *_noFillURLs;
    NSString *_qdata;
    NSString *_appKey;
    NSArray *_rewards;
    NSString *_defaultSlotSize;
    NSString *_defaultAdSize;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *adNetworkConfigs; // @synthesize adNetworkConfigs=_adNetworkConfigs;
@property(nonatomic) double adNetworkTimeout; // @synthesize adNetworkTimeout=_adNetworkTimeout;
@property(readonly, nonatomic) _Bool allowPublisherRenderedAttribution; // @synthesize allowPublisherRenderedAttribution=_allowPublisherRenderedAttribution;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(nonatomic) long long bannerAnimationType; // @synthesize bannerAnimationType=_bannerAnimationType;
@property(copy, nonatomic) NSArray *clickURLs; // @synthesize clickURLs=_clickURLs;
@property(readonly, copy, nonatomic) NSString *defaultAdSize; // @synthesize defaultAdSize=_defaultAdSize;
@property(readonly, copy, nonatomic) NSString *defaultSlotSize; // @synthesize defaultSlotSize=_defaultSlotSize;
- (id)description;
@property(readonly, nonatomic) long long impressionDefinition; // @synthesize impressionDefinition=_impressionDefinition;
@property(copy, nonatomic) NSArray *impressionURLs; // @synthesize impressionURLs=_impressionURLs;
- (id)init;
- (id)initWithAppKey:(id)arg1 configDict:(id)arg2 error:(id *)arg3;
@property(copy, nonatomic) NSArray *noFillURLs; // @synthesize noFillURLs=_noFillURLs;
- (_Bool)parseConfig:(id)arg1 error:(id *)arg2;
- (_Bool)parseSettingsConfig:(id)arg1 error:(id *)arg2;
@property(copy, nonatomic) NSString *qdata; // @synthesize qdata=_qdata;
@property(nonatomic) double refreshInterval; // @synthesize refreshInterval=_refreshInterval;
@property(copy, nonatomic) NSArray *rewards; // @synthesize rewards=_rewards;

@end

