//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GADAdReward, GADMRewardBasedVideoAdNetworkConnector, NSError;

@protocol GADMRewardBasedVideoAdConnectorDelegate
- (void)connector:(GADMRewardBasedVideoAdNetworkConnector *)arg1 didFailToReceiveRewardBasedVideoAdWithError:(NSError *)arg2;
- (void)connector:(GADMRewardBasedVideoAdNetworkConnector *)arg1 didFailToSetUpRewardBasedVideoAdWithError:(NSError *)arg2;
- (void)connector:(GADMRewardBasedVideoAdNetworkConnector *)arg1 didRewardUserWithReward:(GADAdReward *)arg2;
- (void)connectorDidCloseRewardBasedVideoAd:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
- (void)connectorDidOpenRewardBasedVideoAd:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
- (void)connectorDidReceiveClick:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
- (void)connectorDidReceiveRewardBasedVideoAd:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
- (void)connectorDidSetUpRewardBasedVideoAd:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
- (void)connectorDidStartPlayingRewardBasedVideoAd:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
- (void)connectorWillLeaveApplication:(GADMRewardBasedVideoAdNetworkConnector *)arg1;
@end

