//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString, UIColor, UIFont;

@interface GADNativeAdAttribution : NSObject
{
    NSArray *_loadingImages;
    NSMutableArray *_availableImages;
    CDUnknownBlockType _assetCompletionHandler;
    NSArray *_icons;
    double _iconPresentationDuration;
    double _iconAnimationDuration;
    NSString *_text;
    UIFont *_font;
    UIColor *_textColor;
    UIColor *_backgroundColor;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void)failedLoadingNativeAdImageWithError:(id)arg1;
- (void)finishedLoadingNativeAdImage:(id)arg1;
@property(readonly, copy, nonatomic) UIFont *font; // @synthesize font=_font;
@property(readonly, nonatomic) double iconAnimationDuration; // @synthesize iconAnimationDuration=_iconAnimationDuration;
@property(readonly, nonatomic) double iconPresentationDuration; // @synthesize iconPresentationDuration=_iconPresentationDuration;
@property(readonly, nonatomic) NSArray *icons; // @synthesize icons=_icons;
- (id)init;
- (id)initWithDictionary:(id)arg1;
- (void)loadAssetsWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, copy, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;

@end

