//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class GADAdChoicesView, GADMediaView, GADNativeAdViewPolicy, GADNativeAppInstallAd;

@interface GADNativeAppInstallAdView : UIView
{
    GADNativeAdViewPolicy *_nativeAdViewPolicy;
    UIView *_headlineView;
    UIView *_callToActionView;
    UIView *_iconView;
    UIView *_bodyView;
    UIView *_storeView;
    UIView *_priceView;
    UIView *_imageView;
    UIView *_starRatingView;
    GADMediaView *_mediaView;
    GADAdChoicesView *_adChoicesView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak GADAdChoicesView *adChoicesView; // @synthesize adChoicesView=_adChoicesView;
@property(nonatomic) __weak UIView *bodyView; // @synthesize bodyView=_bodyView;
@property(nonatomic) __weak UIView *callToActionView; // @synthesize callToActionView=_callToActionView;
- (void)commonInit;
- (void)didMoveToSuperview;
@property(nonatomic) __weak UIView *headlineView; // @synthesize headlineView=_headlineView;
@property(nonatomic) __weak UIView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak UIView *imageView; // @synthesize imageView=_imageView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) __weak GADMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(retain, nonatomic) GADNativeAppInstallAd *nativeAppInstallAd;
@property(nonatomic) __weak UIView *priceView; // @synthesize priceView=_priceView;
@property(nonatomic) __weak UIView *starRatingView; // @synthesize starRatingView=_starRatingView;
@property(nonatomic) __weak UIView *storeView; // @synthesize storeView=_storeView;
- (void)updateMediaView;

@end

