//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADMediatedNativeAd.h"
#import "GADNativeAdViewPolicyDelegate.h"
#import "GADSlotAdEventDelegate.h"

@class GADMediatedNativeAd, GADSlot, NSArray, NSDictionary, NSMutableArray, NSMutableSet, NSObject<OS_dispatch_queue>, NSSet, NSString, UIViewController;

@interface GADNativeAd : NSObject <GADMediatedNativeAd, GADSlotAdEventDelegate, GADNativeAdViewPolicyDelegate>
{
    _Bool _hasRecordedImpression;
    NSSet *_impressionTrackingURLs;
    NSMutableSet *_requestedAssets;
    NSMutableSet *_completedAssets;
    _Bool _failedToLoadARequiredAsset;
    _Bool _assetLoadingStarted;
    NSMutableArray *_assetLoadCompletionHandlers;
    NSObject<OS_dispatch_queue> *_lockQueue;
    _Bool _publisherRenderAdChoicesAllowed;
    id <GADNativeAdDelegate> _delegate;
    UIViewController *_rootViewController;
    NSDictionary *_extraAssets;
    NSString *_adNetworkClassName;
    NSString *_adUnitID;
    NSDictionary *_adConfiguration;
    GADMediatedNativeAd *_mediatedNativeAd;
    GADSlot *_slot;
    NSSet *_thirdPartyClickTrackingURLs;
    NSString *_googleClickTrackingURLString;
    NSArray *_clickActions;
    long long _attributionCorner;
    NSString *_debugSignalInformation;
}

+ (Class)classFromAdConfigurationDictionary:(id)arg1;
+ (id)firstAdObjectInAdConfigurationDictionary:(id)arg1;
+ (id)mediationConnectorForConfiguration:(id)arg1 networkConfiguration:(id)arg2;
+ (id)supportHTMLURL;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *adConfiguration; // @synthesize adConfiguration=_adConfiguration;
- (id)adFormatTemplateID;
@property(copy, nonatomic) NSString *adNetworkClassName; // @synthesize adNetworkClassName=_adNetworkClassName;
@property(copy, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
- (void)addAssetWithNameToRequestedAssets:(id)arg1;
@property(readonly, nonatomic) long long attributionCorner; // @synthesize attributionCorner=_attributionCorner;
- (void)callAndClearAssetLoadCompletionHandlersWithError:(id)arg1;
@property(copy, nonatomic) NSArray *clickActions; // @synthesize clickActions=_clickActions;
- (void)dealloc;
@property(copy, nonatomic) NSString *debugSignalInformation; // @synthesize debugSignalInformation=_debugSignalInformation;
@property(nonatomic) __weak id <GADNativeAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSDictionary *extraAssets; // @synthesize extraAssets=_extraAssets;
- (void)failedToLoadAssetWithName:(id)arg1;
- (void)finishedLoadingAssetWithName:(id)arg1;
- (void)gadNativeAd_commonInit;
@property(copy, nonatomic) NSString *googleClickTrackingURLString; // @synthesize googleClickTrackingURLString=_googleClickTrackingURLString;
- (_Bool)hasRecordedImpression;
- (_Bool)hasValidConfigurationForRequestParameters:(id)arg1;
- (id)init;
- (id)initWithDictionary:(id)arg1 options:(id)arg2;
- (id)initWithMediatedNativeAd:(id)arg1 options:(id)arg2;
- (void)loadAssetsWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) GADMediatedNativeAd *mediatedNativeAd; // @synthesize mediatedNativeAd=_mediatedNativeAd;
- (id)mediatedNativeAdDelegate;
- (void)mediatedNativeAdDidDismissScreen:(id)arg1;
- (void)mediatedNativeAdDidRecordClick:(id)arg1;
- (void)mediatedNativeAdDidRecordImpression:(id)arg1;
- (void)mediatedNativeAdWillDismissScreen:(id)arg1;
- (void)mediatedNativeAdWillLeaveApplication:(id)arg1;
- (void)mediatedNativeAdWillPresentScreen:(id)arg1;
- (void)nativeAdViewPolicy:(id)arg1 didBeginTrackingView:(id)arg2;
- (void)nativeAdViewPolicy:(id)arg1 didUnloadNativeAd:(id)arg2 fromView:(id)arg3;
- (void)notifyLoadingDelegateIfAllRequestedAssetsHaveLoaded;
- (void)observeNotificationsFromMediatedNativeAd;
- (void)performClickOnView:(id)arg1 assetName:(id)arg2 environment:(id)arg3;
- (void)pingDebugSignal;
@property(nonatomic) _Bool publisherRenderAdChoicesAllowed; // @synthesize publisherRenderAdChoicesAllowed=_publisherRenderAdChoicesAllowed;
- (void)recordImpressionWithEnvironment:(id)arg1;
- (id)requiredAssets;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) GADSlot *slot; // @synthesize slot=_slot;
@property(copy, nonatomic) NSSet *thirdPartyClickTrackingURLs; // @synthesize thirdPartyClickTrackingURLs=_thirdPartyClickTrackingURLs;
- (_Bool)shouldLoadAssets;
- (void)slotDidDismissScreen:(id)arg1;
- (void)slotDidRecordClick:(id)arg1;
- (void)slotDidRecordImpression:(id)arg1;
- (void)slotWillDismissScreen:(id)arg1;
- (void)slotWillLeaveApplication:(id)arg1;
- (void)slotWillPresentScreen:(id)arg1;
- (void)stopObservingMediatedNativeAd;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

