//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADImpressionMonitorDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class GADAdChoicesView, GADAdExposureMonitor, GADImpressionMonitor, GADNativeAd<GADNativeAdSourceAttributing><GADOverlayViewSource>, GADOverlayView, NSMapTable, NSMutableArray, NSString, UIView;

@interface GADNativeAdViewPolicy : NSObject <GADImpressionMonitorDelegate, UIGestureRecognizerDelegate>
{
    UIView *_adChoicesContentView;
    GADAdChoicesView *_weakAdChoicesViewFromPublisher;
    UIView *_adView;
    GADOverlayView *_overlayView;
    NSMapTable *_assetViewAssetNames;
    NSString *_attributionIconAssetName;
    NSString *_attributionTextAssetName;
    NSString *_backgroundAssetName;
    long long _adChoicesViewCorner;
    GADImpressionMonitor *_impressionMonitor;
    NSMutableArray *_adChoicesViewConstraints;
    _Bool _shouldAllowPublisherRenderAdChoices;
    GADAdExposureMonitor *_adExposureMonitor;
    id <GADNativeAdViewPolicyDelegate> _delegate;
    GADNativeAd<GADNativeAdSourceAttributing><GADOverlayViewSource> *_nativeAd;
}

- (void).cxx_destruct;
- (void)adViewDidLayoutSubviews;
- (void)adViewDidMoveToSuperview;
- (void)addUserInteractionToAdView;
- (void)beginObservingVideoClickNotifications;
- (void)checkForImpression;
- (void)constrainAdChoicesViewToCorner;
- (void)dealloc;
@property(nonatomic) __weak id <GADNativeAdViewPolicyDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finishAdExposureMonitoring;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleImpressionTracking;
- (void)handleTap:(id)arg1;
- (void)handleVideoClickNotification:(id)arg1;
- (void)impressionMonitorDidMonitorImpression:(id)arg1;
- (id)initWithAdView:(id)arg1 attributionIconAssetName:(id)arg2 attributionTextAssetName:(id)arg3 backgroundAssetName:(id)arg4;
@property(retain, nonatomic) GADNativeAd<GADNativeAdSourceAttributing><GADOverlayViewSource> *nativeAd; // @synthesize nativeAd=_nativeAd;
- (_Bool)nativeAdHasVideo;
- (id)nativeAdSignalDictionary;
- (void)orderViews;
- (void)recordImpression;
- (void)replaceAssetWithName:(id)arg1 withAssetView:(id)arg2 weakReferencePointer:(id *)arg3;
- (id)signalDictionaryWithAssetView:(id)arg1 assetName:(id)arg2 adView:(id)arg3;
- (void)startImpressionMonitoring;
- (void)stopImpressionMonitoring;
- (id)tapHandlingEnvironmentWithTapLocation:(struct CGPoint)arg1 tappedViewName:(id)arg2;
- (void)updateAdChoicesView;
- (void)updateOverlay;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

