//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface GADNetwork : NSObject
{
    GADNetwork *_selfReference;
    unsigned long long _networkType;
    unsigned long long _lastKnownNetworkType;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSObject<OS_dispatch_queue> *_enableCheckingQueue;
    struct __SCNetworkReachability *_networkReachabilityRef;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)disableNetworkChecking;
- (void)disableReachability;
- (void)enableNetworkChecking;
- (id)init;
- (id)lastKnownNetworkTypeString;
@property unsigned long long networkType;
- (id)networkTypeString;
- (id)requestDictionary;
- (void)setNetworkTypeFromFlags:(unsigned int)arg1;

@end

