//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADIntermitting.h"

@class GADIntermission, GADOpener, GADSlot, NSString, UIViewController;

@interface GADOverlayProxy : NSObject <GADIntermitting>
{
    GADIntermission *_intermission;
    UIViewController *_viewController;
    GADSlot *_slot;
    GADOpener *_opener;
}

+ (id)overlayProxyForViewController:(id)arg1;
- (void).cxx_destruct;
- (id)init;
- (id)initWithViewController:(id)arg1;
@property(readonly, nonatomic) GADIntermission *intermission; // @synthesize intermission=_intermission;
@property(retain, nonatomic) GADOpener *opener; // @synthesize opener=_opener;
- (void)presentFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)relinquishScreenWithCompletion:(CDUnknownBlockType)arg1;
@property(nonatomic) __weak GADSlot *slot; // @synthesize slot=_slot;
- (_Bool)shouldDismissOnApplicationEnteringForeground;
@property(readonly, nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

