//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class GADAdView, GADAutoClickProtection, GADSlot, NSMapTable, NSMutableDictionary, NSMutableSet, NSString, NSURL, UIViewController;

@interface GADOpener : NSObject <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, UIAlertViewDelegate>
{
    NSMapTable *_confirmationAlertURLs;
    NSMutableSet *_allowedAppURLs;
    _Bool _didOpenAnotherApplication;
    UIViewController *_viewController;
    NSURL *_referringURL;
    GADAdView *_adView;
    GADSlot *_slot;
    NSString *_navigationURLString;
    GADAutoClickProtection *_autoClickProtection;
    NSMutableDictionary *_cachedStoreProductViewController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak GADAdView *adView; // @synthesize adView=_adView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) GADAutoClickProtection *autoClickProtection; // @synthesize autoClickProtection=_autoClickProtection;
@property(retain, nonatomic) NSMutableDictionary *cachedStoreProductViewController; // @synthesize cachedStoreProductViewController=_cachedStoreProductViewController;
- (_Bool)canOpenContent:(id)arg1;
- (void)configureOverlay:(id)arg1 orientations:(unsigned long long)arg2 usingCustomClose:(_Bool)arg3;
- (void)confirmClickToURL:(id)arg1 message:(id)arg2;
- (id)confirmationMessageForURL:(id)arg1;
@property(nonatomic) _Bool didOpenAnotherApplication; // @synthesize didOpenAnotherApplication=_didOpenAnotherApplication;
- (void)didOpenURL:(id)arg1;
- (void)disableAutoCollapseForResize;
- (void)expandToWebAppWithSupportedOrientations:(unsigned long long)arg1 usingCustomClose:(_Bool)arg2;
- (void)fetchInAppStoreForProductID:(id)arg1;
- (id)init;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
@property(copy, nonatomic) NSString *navigationURLString; // @synthesize navigationURLString=_navigationURLString;
- (void)openApp:(id)arg1;
- (void)openBrowserToURL:(id)arg1 supportedOrientations:(unsigned long long)arg2;
- (void)openCalendarWithDictionary:(id)arg1;
- (void)openEmailComposer:(id)arg1;
- (void)openInAppPurchase:(id)arg1 quantity:(long long)arg2 reportingURLStringFormats:(id)arg3;
- (void)openInAppStore:(id)arg1 fallbackURL:(id)arg2;
- (void)openInAppStoreWithProductID:(id)arg1 fallbackURL:(id)arg2 shouldWaitForFetch:(_Bool)arg3;
- (void)openPromptToStorePictureAtURL:(id)arg1;
- (void)openSafariViewControllerToURL:(id)arg1 supportedOrientations:(unsigned long long)arg2;
- (void)openSmsComposer:(id)arg1;
- (void)openWebApp:(id)arg1 supportedOrientations:(unsigned long long)arg2 usingCustomClose:(_Bool)arg3;
- (void)openWebAppWithHTML:(id)arg1 supportedOrientations:(unsigned long long)arg2 usingCustomClose:(_Bool)arg3;
- (void)openWebAppWithResizeProperties:(id)arg1;
- (void)openWebViewBrowserToURL:(id)arg1 supportedOrientations:(unsigned long long)arg2;
- (id)overlayWithOrientations:(unsigned long long)arg1 useCustomClose:(_Bool)arg2;
- (void)presentComposerController:(id)arg1 forURL:(id)arg2;
@property(copy, nonatomic) NSURL *referringURL; // @synthesize referringURL=_referringURL;
@property(nonatomic) __weak GADSlot *slot; // @synthesize slot=_slot;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (_Bool)shouldPerformOpenAction;
- (_Bool)shouldPerformOpenActionWithOrientations:(unsigned long long)arg1;
- (id)topViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

