//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPercentDrivenInteractiveTransition.h"

#import "UIViewControllerTransitioningDelegate.h"

@class GADViewControllerFullScreenSwipeAnimation, NSString;

@interface GADPercentDrivenUserInteractionAnimationController : UIPercentDrivenInteractiveTransition <UIViewControllerTransitioningDelegate>
{
    id <GADPercentDrivenUserInteractionAnimationControllerDelegate> _delegate;
    GADViewControllerFullScreenSwipeAnimation *_transitionAnimation;
}

- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(nonatomic) __weak id <GADPercentDrivenUserInteractionAnimationControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handlePanGesture:(id)arg1;
- (id)initWithAnimation:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (_Bool)isAnimatingBottomToTop;
- (_Bool)isAnimatingTopToBottom;
@property(retain, nonatomic) GADViewControllerFullScreenSwipeAnimation *transitionAnimation; // @synthesize transitionAnimation=_transitionAnimation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

