//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, NSURL, NSURLConnection, NSURLRequest;

@interface GADResourceCache : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSURLRequest *_request;
    NSString *_cacheID;
    NSURL *_fileURL;
    NSMutableDictionary *_responseHeaders;
    id <GADResourceCacheDelegate> _delegate;
    NSURLConnection *_connection;
    unsigned long long _cachingState;
    long long _requestID;
    _Bool _hasBeenUsed;
}

- (void).cxx_destruct;
- (void)appendDataToFile:(id)arg1;
- (_Bool)appendDataToFile:(id)arg1 withError:(id *)arg2;
@property(readonly, copy) NSString *cacheID; // @synthesize cacheID=_cacheID;
- (void)cachingHasFailedWithError:(id)arg1;
- (void)cachingHasSucceeded;
@property unsigned long long cachingState;
@property(readonly) _Bool cachingSucceeded;
- (void)cancel;
@property(retain) NSURLConnection *connection;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
- (_Bool)createEmptyFile:(id)arg1 withError:(id *)arg2;
- (void)dealloc;
@property __weak id <GADResourceCacheDelegate> delegate;
@property(readonly, copy) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(readonly) _Bool hasBeenUsed; // @synthesize hasBeenUsed=_hasBeenUsed;
- (id)init;
- (id)initWithURLRequest:(id)arg1 cacheID:(id)arg2 error:(id *)arg3;
- (void)notifyCachingFailedForRequestID:(long long)arg1 withError:(id)arg2;
- (void)notifyCachingHasReceivedResponseWithRequestID:(long long)arg1;
- (void)notifyCachingStartedWithRequestID:(long long)arg1;
- (void)notifyCachingSucceededWithRequestID:(long long)arg1;
@property(readonly, copy) NSURLRequest *request; // @synthesize request=_request;
@property long long requestID;
@property(readonly, copy) NSDictionary *responseHeaders;
- (void)start;

@end

