//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADAdFetcherDelegate.h"
#import "GADInterstitialAdClickDelegate.h"
#import "GADInterstitialDelegate.h"
#import "GADInterstitialRewardBasedVideoAdDelegate.h"
#import "GADMRewardBasedVideoAdConnectorDelegate.h"
#import "GADSDKCoreControllerDelegate.h"

@class GADAd, GADAdFetcher, GADInterstitial, GADMConfig, GADMRewardBasedVideoAdNetworkConnector, GADRequest, GADSlotStatistics, NSMutableArray, NSMutableDictionary, NSString;

@interface GADRewardBasedVideoAd : NSObject <GADMRewardBasedVideoAdConnectorDelegate, GADSDKCoreControllerDelegate, GADAdFetcherDelegate, GADInterstitialDelegate, GADInterstitialAdClickDelegate, GADInterstitialRewardBasedVideoAdDelegate>
{
    GADInterstitial *_interstitial;
    id _configurationObserver;
    _Bool _ready;
    _Bool _requestInProgress;
    id <GADRewardBasedVideoAdDelegate> _delegate;
    NSString *_adNetworkClassName;
    GADRequest *_request;
    NSString *_adUnitID;
    NSString *_requestID;
    GADAdFetcher *_adFetcher;
    GADMConfig *_mediationConfig;
    NSMutableArray *_pendingAdRequestConnectors;
    NSMutableArray *_allocationIDs;
    GADMRewardBasedVideoAdNetworkConnector *_requestingConnector;
    GADMRewardBasedVideoAdNetworkConnector *_receivedConnector;
    NSMutableDictionary *_pendingSetUpConnectorsTimestamp;
    NSMutableDictionary *_connectors;
    GADAd *_ad;
    GADSlotStatistics *_adStatistics;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) GADAd *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) GADAdFetcher *adFetcher; // @synthesize adFetcher=_adFetcher;
- (void)adFetcher:(id)arg1 didFailToFetchAd:(id)arg2 withError:(id)arg3 responseCode:(unsigned long long)arg4;
- (void)adFetcher:(id)arg1 didFetchAd:(id)arg2;
- (id)adLoadActionTimeRecorder;
- (void)adLoadedSuccessfully;
@property(copy, nonatomic) NSString *adNetworkClassName; // @synthesize adNetworkClassName=_adNetworkClassName;
@property(readonly, nonatomic) GADSlotStatistics *adStatistics; // @synthesize adStatistics=_adStatistics;
@property(copy, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
@property(retain, nonatomic) NSMutableArray *allocationIDs; // @synthesize allocationIDs=_allocationIDs;
- (void)buildPendingAdRequestConnectorsList;
- (void)connector:(id)arg1 didFailToReceiveRewardBasedVideoAdWithError:(id)arg2;
- (void)connector:(id)arg1 didFailToSetUpRewardBasedVideoAdWithError:(id)arg2;
- (void)connector:(id)arg1 didRewardUserWithReward:(id)arg2;
- (void)connectorDidCloseRewardBasedVideoAd:(id)arg1;
- (void)connectorDidOpenRewardBasedVideoAd:(id)arg1;
- (void)connectorDidReceiveClick:(id)arg1;
- (void)connectorDidReceiveRewardBasedVideoAd:(id)arg1;
- (void)connectorDidSetUpRewardBasedVideoAd:(id)arg1;
- (void)connectorDidStartPlayingRewardBasedVideoAd:(id)arg1;
- (void)connectorWillLeaveApplication:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *connectors; // @synthesize connectors=_connectors;
- (void)dealloc;
- (id)decodedJSONResponseFromAd:(id)arg1 error:(id *)arg2;
@property(nonatomic) __weak id <GADRewardBasedVideoAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void)failedJavaScriptFile;
- (void)failedToLoadAdWithError:(id)arg1;
- (void)fetchAdForRequest:(id)arg1 withAdUnitID:(id)arg2;
- (id)init;
- (void)interstitial:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)interstitial:(id)arg1 didRewardUserWithReward:(id)arg2;
- (void)interstitialDidDismissScreen:(id)arg1;
- (void)interstitialDidReceiveAd:(id)arg1;
- (void)interstitialDidReceiveAdClick:(id)arg1;
- (void)interstitialDidStartPlayingRewardBasedVideoAd:(id)arg1;
- (void)interstitialWillDismissScreen:(id)arg1;
- (void)interstitialWillLeaveApplication:(id)arg1;
- (void)interstitialWillPresentScreen:(id)arg1;
- (void)invalidJavaScriptRequest;
@property(readonly, nonatomic, getter=isReady) _Bool ready; // @synthesize ready=_ready;
- (void)loadAd:(id)arg1;
- (void)loadAd:(id)arg1 headers:(id)arg2;
- (void)loadAdURLWithParameters:(id)arg1;
- (void)loadInterstitialWithAd:(id)arg1;
- (void)loadInterstitialWithAdRequest:(id)arg1;
- (void)loadRequest:(id)arg1 withAdUnitID:(id)arg2;
- (void)makeNextAdRequest;
@property(retain, nonatomic) GADMConfig *mediationConfig; // @synthesize mediationConfig=_mediationConfig;
- (void)mediation_adapterDidFailToSetUpWithNetworkConfig:(id)arg1;
- (void)mediation_connectorDidFailToReceiveAd:(id)arg1 withError:(id)arg2;
- (void)mediation_connectorDidReceiveAd:(id)arg1;
- (void)mediation_connectorWillStartRequestingAd;
@property(retain, nonatomic) NSMutableArray *pendingAdRequestConnectors; // @synthesize pendingAdRequestConnectors=_pendingAdRequestConnectors;
@property(retain, nonatomic) NSMutableDictionary *pendingSetUpConnectorsTimestamp; // @synthesize pendingSetUpConnectorsTimestamp=_pendingSetUpConnectorsTimestamp;
- (void)pingNoFillURLs;
- (void)presentFromRootViewController:(id)arg1;
- (void)presentMediatedRewardBasedVideoAdFromViewController:(id)arg1;
- (void)processMediationAd:(id)arg1;
@property(retain, nonatomic) GADMRewardBasedVideoAdNetworkConnector *receivedConnector; // @synthesize receivedConnector=_receivedConnector;
- (void)removeStaleConnectors;
@property(retain, nonatomic) GADRequest *request; // @synthesize request=_request;
- (void)requestAdFromConnector:(id)arg1;
@property(copy, nonatomic) NSString *requestID; // @synthesize requestID=_requestID;
@property(nonatomic) _Bool requestInProgress; // @synthesize requestInProgress=_requestInProgress;
- (id)requestParameters;
- (long long)requestedAdType;
@property(retain, nonatomic) GADMRewardBasedVideoAdNetworkConnector *requestingConnector; // @synthesize requestingConnector=_requestingConnector;
- (void)resetFillStatus;
- (void)setUpAdaptersForAdNetworkConfigs:(id)arg1;
- (void)setUpAdaptersFromApplicationConfiguration;
- (void)startObservingApplicationConfiguration;
- (void)stopObservingApplicationConfiguration;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

