//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface GADResourceCachesStatus : NSObject
{
    NSMutableDictionary *_resourceCaches;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)init;
- (_Bool)isCachingInProgressForFileURL:(id)arg1;
- (_Bool)lockCachingWithResourceCache:(id)arg1;
- (id)resourceCacheForFileURL:(id)arg1;
- (void)resourceCacheStoppedCaching:(id)arg1;

@end

