//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADGMSGHandler.h"

@class GADSlot;

@interface GADSwipeToViewControllerGMSGHandler : GADGMSGHandler
{
    GADSlot *_slot;
}

+ (id)actionBlockDictionary;
- (void).cxx_destruct;
- (void)adView:(id)arg1 disableSwipeToViewController:(id)arg2;
- (void)adView:(id)arg1 enableSwipeToViewController:(id)arg2;
- (id)initWithSlot:(id)arg1;
@property(nonatomic) __weak GADSlot *slot; // @synthesize slot=_slot;

@end

