//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADStatisticsCore, GADTimingManager, NSDictionary, NSString;

@interface GADSlotStatistics : NSObject
{
    GADStatisticsCore *_statisticsCore;
    GADTimingManager *_timingManager;
    NSString *_identifier;
}

- (void).cxx_destruct;
- (id)adapterDurationsParameter;
- (id)adapterExitCodesParameter;
- (id)adapterFillStatusParameter;
- (id)adapterFillStatusParameterOrderedByAllocationIDs:(id)arg1;
- (void)endTimingAdapterWithExitCode:(long long)arg1;
- (void)endTimingAdapterWithFillStatus:(long long)arg1 allocationID:(id)arg2;
- (void)endTimingNamed:(id)arg1;
- (id)fillStatusStringFromArray:(id)arg1;
- (id)init;
- (void)resetFillStatus;
- (void)resetTimingAdapters;
- (void)setIdentifier:(id)arg1;
- (void)startTimingAdapter;
- (void)startTimingNamed:(id)arg1 withExplicitEnd:(_Bool)arg2;
@property(readonly, copy, nonatomic) NSDictionary *statistics;
- (id)timingNamed:(id)arg1;

@end

