//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, NSString, NSURL;

@interface GADSafeBrowsingReporter : NSObject
{
    NSURL *_reportURL;
    _Bool _shouldInterceptRequests;
    _Bool _shouldSendRenderedAd;
    NSString *_clickString;
    NSSet *_excludedHeaders;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *clickString; // @synthesize clickString=_clickString;
@property(readonly, nonatomic) NSSet *excludedHeaders; // @synthesize excludedHeaders=_excludedHeaders;
- (id)init;
- (id)initWithDictionary:(id)arg1;
- (void)reportResourceCollection:(id)arg1;
@property(readonly, nonatomic) _Bool shouldInterceptRequests; // @synthesize shouldInterceptRequests=_shouldInterceptRequests;
@property(readonly, nonatomic) _Bool shouldSendRenderedAd; // @synthesize shouldSendRenderedAd=_shouldSendRenderedAd;

@end

