//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADOverlayPresenting.h"

@class GADViewController, NSString, UIView;

@interface GADTransparentOverlayPresenter : NSObject <GADOverlayPresenting>
{
    GADViewController *_presentedViewController;
    UIView *_pivotView;
    UIView *_cropView;
    id _orientationChangeListener;
    id _placementDisappearanceObserver;
}

+ (struct CGRect)frameWithSize:(struct CGSize)arg1 centeredInFrame:(struct CGRect)arg2;
- (void).cxx_destruct;
- (void)animateTransparentInterstitialPresentationWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)composeTransparentInterstitialViewsForPresentation;
@property(retain, nonatomic) UIView *cropView; // @synthesize cropView=_cropView;
- (void)dealloc;
- (void)dismissWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)init;
@property(readonly, nonatomic, getter=isReadyToPresent) _Bool readyToPresent;
@property(retain, nonatomic) id orientationChangeListener; // @synthesize orientationChangeListener=_orientationChangeListener;
@property(retain, nonatomic) UIView *pivotView; // @synthesize pivotView=_pivotView;
- (struct CGRect)pivotedApplicationFrameForOrientation:(long long)arg1;
@property(retain, nonatomic) id placementDisappearanceObserver; // @synthesize placementDisappearanceObserver=_placementDisappearanceObserver;
- (void)presentFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)presentationViewController;
@property(nonatomic) __weak GADViewController *presentedViewController; // @synthesize presentedViewController=_presentedViewController;
- (void)setNeedsUpdateOrientation;
- (struct CGAffineTransform)transformForOrientation:(long long)arg1;
- (void)updateTransparentInterstitialOrientation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

