//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GADURLPingData : NSObject
{
    NSString *_URLString;
    CDUnknownBlockType _completionBlock;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
@property(readonly, copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (id)initWithURLString:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

