//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GADVideoRendering.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, NSString;

@interface GADVideoPlayerView : UIView <GADVideoRendering>
{
    AVPlayer *_player;
    AVPlayerItem *_playerItem;
    AVPlayerLayer *_playerLayer;
    _Bool _playbackOptimizationEnabled;
    _Bool _playbackOptimizationDisabledBySDKCore;
}

- (void).cxx_destruct;
- (void)commonInit;
- (void)disableVideoPlaybackOptimization;
- (void)enableVideoPlaybackOptimization;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)optimizeVideoForAdVisibility:(_Bool)arg1;
- (void)resetVideoPlaybackOptimization;
- (void)setFrame:(struct CGRect)arg1;
- (void)setUpWithPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

