//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GADVideoRendering.h"
#import "GLKViewDelegate.h"

@class AVPlayer, AVPlayerItemVideoOutput, CADisplayLink, EAGLContext, GADBlockInvocation, GADGLSphericalShader, GLKView, NSString, NSThread;

@interface GADVideoPlayerGLView : UIView <GLKViewDelegate, GADVideoRendering>
{
    GLKView *_glView;
    NSThread *_renderThread;
    CADisplayLink *_displayLink;
    AVPlayerItemVideoOutput *_videoOutput;
    AVPlayer *_currentPlayer;
    double _nextDisplayTime;
    _Bool _hasDisplayedAtLeastOnePixelBuffer;
    double _displayStartTimeIntervalSince1970;
    double _videoOutputEmptyTimeIntervalThreshold;
    EAGLContext *_context;
    GADGLSphericalShader *_sphericalShader;
    _Bool _applicationActive;
    _Bool _isSubViewOfVisibleWindow;
    GADBlockInvocation *_renderThreadBlockInvocation;
    id <GADVideoPlayerGLViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <GADVideoPlayerGLViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disableVideoPlaybackOptimization;
- (void)displayLinkCallback:(id)arg1;
- (id)displayLinkCallbackBlockInvocation;
- (void)enableVideoPlaybackOptimization;
- (void)glkView:(id)arg1 drawInRect:(struct CGRect)arg2;
- (void)handleUserTouchMovedByVector:(struct CGVector)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)optimizeVideoForAdVisibility:(_Bool)arg1;
- (void)pauseDisplayLink;
- (void)renderThreadApplicationDidEnterBackground;
- (void)renderThreadApplicationWillEnterForeground;
- (id)renderThreadBlockInvocationWithDisplayLink:(id)arg1;
- (void)renderThreadResetVideoOutput;
- (void)renderThreadSetUp;
- (void)renderThreadSetUpFailedWithErrorMessage:(id)arg1;
- (void)renderThreadSetUpSucceeded;
- (void)renderThreadUserTouchMovedByVector:(id)arg1;
- (void)renderThreadWillMoveToWindow:(id)arg1;
- (void)resetVideoPlaybackOptimization;
- (void)resumeDisplayLink;
- (void)setUpWithPlayer:(id)arg1;
- (void)startRenderThread;
- (void)stopRenderThread;
- (void)unscheduleDisplayLink;
- (void)willMoveToWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

