//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADAdLoaderOptions.h"

@interface GADVideoOptions : GADAdLoaderOptions
{
    _Bool _startMuted;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)requestParameters;
@property(nonatomic) _Bool startMuted; // @synthesize startMuted=_startMuted;

@end

