//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, UIView;

@interface GADViewControllerFullScreenSwipeAnimation : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _presenting;
    _Bool _draggableViewShownOnPresentation;
    long long _direction;
    double _startY;
    UIView *_draggableView;
    double _transitionDuration;
    struct CGRect _draggableViewEndFrameAfterAnimation;
    struct CGRect _animatedViewFrameBeforeAnimation;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
@property(nonatomic) struct CGRect animatedViewFrameBeforeAnimation; // @synthesize animatedViewFrameBeforeAnimation=_animatedViewFrameBeforeAnimation;
- (id)animationContextForBottomToTopAnimationDismissalWithTransitionContext:(id)arg1;
- (id)animationContextForBottomToTopAnimationPresentationWithTransitionContext:(id)arg1;
- (id)animationContextForRestoringAnimationToSavedState:(id)arg1;
- (id)animationContextForTopToBottomAnimationDismissalWithTransitionContext:(id)arg1;
- (id)animationContextForTopToBottomAnimationPresentationWithTransitionContext:(id)arg1;
@property(nonatomic) long long direction; // @synthesize direction=_direction;
@property(retain, nonatomic) UIView *draggableView; // @synthesize draggableView=_draggableView;
@property(nonatomic) struct CGRect draggableViewEndFrameAfterAnimation; // @synthesize draggableViewEndFrameAfterAnimation=_draggableViewEndFrameAfterAnimation;
@property(nonatomic) _Bool draggableViewShownOnPresentation; // @synthesize draggableViewShownOnPresentation=_draggableViewShownOnPresentation;
- (id)init;
- (_Bool)isPresenting;
- (_Bool)removeDraggableViewAnimationIfInvalidForAnimationContext:(id)arg1;
@property(nonatomic) double startY; // @synthesize startY=_startY;
@property(nonatomic) double transitionDuration; // @synthesize transitionDuration=_transitionDuration;
- (double)transitionDuration:(id)arg1;
- (void)willAnimateDismissal;
- (void)willAnimatePresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

