//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADResourceCacheDelegate.h"

@class GADResourceCache, NSData, NSObject<OS_dispatch_queue>, NSString, NSURL;

@interface GADVersionedCache : NSObject <GADResourceCacheDelegate>
{
    NSString *_cacheID;
    NSURL *_cacheURL;
    NSString *_userDefaultsKey;
    GADResourceCache *_resourceCache;
    CDUnknownBlockType _completionBlock;
    _Bool _loading;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSString *_newVersion;
    NSData *_cacheData;
    NSString *_version;
}

- (void).cxx_destruct;
@property(readonly) NSData *cacheData;
- (void)executeCompletionBlock:(CDUnknownBlockType)arg1 onMainThreadWithError:(id)arg2;
- (id)initWithCacheID:(id)arg1;
- (void)resetState;
- (void)resetStateAndNotifyCompletionBlockWithError:(id)arg1;
- (void)resourceCache:(id)arg1 didFailCachingWithError:(id)arg2;
- (void)resourceCacheDidSucceededCaching:(id)arg1;
- (void)updateWithURL:(id)arg1 version:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
@property(readonly) NSString *version;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

