//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSValue;

@interface GADWeakReference : NSObject
{
    id _weakObject;
    NSValue *_uniqueID;
}

+ (_Bool)set:(id)arg1 containsObject:(id)arg2;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (id)initWithObject:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSValue *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(readonly, nonatomic) __weak id weakObject; // @synthesize weakObject=_weakObject;

@end

