//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GAIBatchingDispatcher, NSMutableDictionary;

@interface GAI : NSObject
{
    _Bool trackUncaughtExceptions_;
    _Bool _dryRun;
    _Bool _optOut;
    GAIBatchingDispatcher *dispatcher_;
    NSMutableDictionary *trackers_;
    id <GAITracker> defaultTracker_;
    Class trackerImplClass_;
    id <GAILogger> logger_;
    Class _urlConnectionClass;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
+ (id)sharedLogger;
+ (id)thread;
+ (oneway void)threadMain:(id)arg1;
- (id)autorelease;
- (id)clientId;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)createDispatcher:(id *)arg1;
@property(nonatomic) id <GAITracker> defaultTracker; // @synthesize defaultTracker=defaultTracker_;
- (void)dispatch;
@property(nonatomic) double dispatchInterval;
- (void)dispatchWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) GAIBatchingDispatcher *dispatcher; // @synthesize dispatcher=dispatcher_;
@property(nonatomic) _Bool dryRun; // @synthesize dryRun=_dryRun;
- (id)init;
@property(retain, nonatomic) id <GAILogger> logger; // @synthesize logger=logger_;
@property(nonatomic) _Bool optOut; // @synthesize optOut=_optOut;
- (oneway void)release;
- (void)removeTrackerByName:(id)arg1;
- (void)reset;
- (id)retain;
- (unsigned long long)retainCount;
@property(nonatomic) _Bool trackUncaughtExceptions; // @synthesize trackUncaughtExceptions=trackUncaughtExceptions_;
@property(nonatomic) Class trackerImplClass; // @synthesize trackerImplClass=trackerImplClass_;
@property(retain, nonatomic) NSMutableDictionary *trackers; // @synthesize trackers=trackers_;
@property(nonatomic) Class urlConnectionClass; // @synthesize urlConnectionClass=_urlConnectionClass;
- (id)trackerWithName:(id)arg1 trackingId:(id)arg2;
- (id)trackerWithTrackingId:(id)arg1;

@end

