//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GAISqlStore, NSArray, NSString;

@interface GAIAnalyticsPropertiesStore : NSObject
{
    GAISqlStore *_sqlStore;
    NSArray *_propertiesTableColumns;
    NSString *_propertiesTableSchemaSql;
    NSString *_propertiesTableUpsertSql;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)bindRecord:(id)arg1 toUpsertStatement:(struct sqlite3_stmt *)arg2;
- (id)buildPropertiesTableSchemaSql;
- (id)buildPropertiesTableUpsertSql;
- (_Bool)clearPropertiesTable;
- (_Bool)createOrValidatePropertiesTable;
- (_Bool)createPropertiesTable;
- (id)createPropertyRecordWithTrackingId:(id)arg1 clientId:(id)arg2 hitNumber:(long long)arg3 checkedIAdCampaign:(_Bool)arg4;
- (void)dealloc;
- (_Bool)hasValidPropertyColumns;
- (id)initWithSqlStore:(id)arg1;
@property(readonly, nonatomic) _Bool isPropertiesTableFull;
- (id)nextHitNumberForTrackingId:(id)arg1 clientId:(id)arg2;
- (void)onOpenDatabase:(id)arg1;
@property(readonly, nonatomic) NSArray *propertiesTableColumns; // @synthesize propertiesTableColumns=_propertiesTableColumns;
@property(readonly, nonatomic) NSString *propertiesTableSchemaSql; // @synthesize propertiesTableSchemaSql=_propertiesTableSchemaSql;
@property(readonly, nonatomic) NSString *propertiesTableUpsertSql; // @synthesize propertiesTableUpsertSql=_propertiesTableUpsertSql;
- (id)propertyRecordForTrackingId:(id)arg1;
- (struct sqlite3_stmt *)selectStmtWithTrackingId:(id)arg1;
- (_Bool)setCheckedIAdCampaignForTrackingId:(id)arg1;
@property(retain, nonatomic) GAISqlStore *sqlStore; // @synthesize sqlStore=_sqlStore;
@property(readonly, nonatomic) unsigned long long storageLimit;
@property(readonly, nonatomic) unsigned long long trackerIdCount;
- (_Bool)upsertPropertyRecord:(id)arg1;

@end

