//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GAICoreDataUtil : NSObject
{
}

+ (id)entityWithDescription:(id)arg1;
+ (id)model;
+ (id)modelDescription;
+ (id)modelWithDescription:(id)arg1;
+ (id)oldModel;
+ (id)oldModelDescription;
- (id)init;

@end

