//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectContext, NSNumber, NSString;

@interface GAIDataStore : NSObject
{
    _Bool _setUpCoreData;
    NSString *_clientId;
    NSString *_hashedIdfa;
    NSNumber *_lastChangeTimeStamp;
    NSNumber *_idfaChangeCount;
    unsigned long long _maxHitCount;
    NSManagedObjectContext *_oldContext;
    NSManagedObjectContext *_context;
    NSManagedObjectContext *_currentContext;
}

+ (id)dataStore;
+ (id)databaseFullPath:(id)arg1;
+ (id)databaseFullURL:(id)arg1;
+ (id)thread;
- (void).cxx_destruct;
- (void)addHit:(id)arg1;
@property(retain, nonatomic) NSString *clientId;
@property(retain, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
- (long long)context:(id)arg1 hitCount:(id *)arg2;
- (_Bool)context:(id)arg1 removeStaleHits:(id *)arg2;
- (id)contextWithModel:(id)arg1 URL:(id)arg2;
- (id)coordinatorWithModel:(id)arg1 URL:(id)arg2;
@property(retain, nonatomic) NSManagedObjectContext *currentContext; // @synthesize currentContext=_currentContext;
- (void)dealloc;
- (_Bool)deleteAllHits:(id *)arg1;
- (_Bool)deleteExcessHits:(id *)arg1;
- (_Bool)deleteHitsWithIds:(id)arg1 error:(id *)arg2;
- (id)fetchClientId;
- (id)fetchHitsWithLimit:(unsigned long long)arg1 error:(id *)arg2;
- (void)gai_performBlockHelper:(id)arg1;
@property(retain, nonatomic) NSString *hashedIdfa;
- (long long)hitCount:(id *)arg1;
@property(retain, nonatomic) NSNumber *idfaChangeCount;
- (id)init;
@property(retain, nonatomic) NSNumber *lastChangeTimeStamp;
@property(nonatomic) unsigned long long maxHitCount; // @synthesize maxHitCount=_maxHitCount;
@property(retain, nonatomic) NSManagedObjectContext *oldContext; // @synthesize oldContext=_oldContext;
- (id)oldHitDescription:(id)arg1;
- (void)onExit:(id)arg1;
- (id)performBlockAndWait:(CDUnknownBlockType)arg1 withError:(id *)arg2;
- (id)requestEntityName:(id)arg1;
- (id)requestHitsWithLimit:(unsigned long long)arg1;
- (id)requestPropertyWithName:(id)arg1;
- (_Bool)save:(id *)arg1;
- (_Bool)setProperty:(id)arg1 numberValue:(id)arg2 withError:(id *)arg3;
- (_Bool)setProperty:(id)arg1 stringValue:(id)arg2 withError:(id *)arg3;
- (_Bool)setUpCoreData;

@end

