//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface GAISqlStore : NSObject
{
    NSString *_databaseName;
    struct sqlite3 *_database;
    NSMutableDictionary *_statementCache;
    NSString *_databasePath;
}

+ (id)databaseDirectoryPath;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)closeAndDeleteDatabase;
- (id)closeDatabase;
@property(nonatomic) struct sqlite3 *database; // @synthesize database=_database;
@property(readonly, copy, nonatomic) NSString *databaseName; // @synthesize databaseName=_databaseName;
@property(readonly, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
- (void)dealloc;
- (_Bool)dropTableWithName:(id)arg1;
- (_Bool)ensureOpenDatabase;
@property(readonly, copy, nonatomic) NSString *errorMessage;
- (int)executeSql:(id)arg1;
- (void)finalizeAndClearStatements;
- (id)initWithDatabaseName:(id)arg1;
- (_Bool)openAndValidateDatabase;
- (struct sqlite3_stmt *)prepareSql:(id)arg1;
- (void)removeStatementForQuery:(id)arg1;
- (unsigned long long)rowCountForTableWithName:(id)arg1;
- (void)setStatement:(struct sqlite3_stmt *)arg1 forQuery:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *statementCache; // @synthesize statementCache=_statementCache;
- (struct sqlite3_stmt *)statementForQuery:(id)arg1;
- (_Bool)tableExists:(id)arg1;

@end

