//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class GAIDataStore, NSMutableDictionary;

@interface GAITrackerModel : NSObject <NSCopying>
{
    _Bool _allowIDFACollection;
    NSMutableDictionary *_parameters;
    GAIDataStore *_dataStore;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)adTargetingEnabled;
- (id)admobId;
@property(nonatomic) _Bool allowIDFACollection; // @synthesize allowIDFACollection=_allowIDFACollection;
- (id)buildDictionary;
- (id)cacheBuster;
- (id)clientId;
- (id)copyWithOverride:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)crc;
- (id)dataSource;
@property(retain, nonatomic) GAIDataStore *dataStore; // @synthesize dataStore=_dataStore;
- (id)defaultParameters;
- (id)deviceModelVersion;
- (id)forcedParameters;
- (id)idfa;
- (id)init;
- (id)initWithDataStore:(id)arg1;
- (id)language;
- (id)methodsForKeys;
- (id)objectForKeyedSubscript:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
- (id)requiredParameters;
- (id)screenResolution;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)valueForKey:(id)arg1;
- (id)valueForUndefinedKey:(id)arg1;
- (void)willSendScreenView;

@end

