//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GSDK_PBArray, GSDK_PBMutableArray;

@interface GSDK_PBField : NSObject
{
    int number_;
    GSDK_PBMutableArray *mutableVarintList_;
    GSDK_PBMutableArray *mutableFixed32List_;
    GSDK_PBMutableArray *mutableFixed64List_;
    GSDK_PBMutableArray *mutableLengthDelimitedList_;
    GSDK_PBMutableArray *mutableGroupList_;
}

- (void)dealloc;
- (id)description;
@property(readonly, retain, nonatomic) GSDK_PBArray *fixed32List; // @synthesize fixed32List=mutableFixed32List_;
@property(readonly, retain, nonatomic) GSDK_PBArray *fixed64List; // @synthesize fixed64List=mutableFixed64List_;
@property(readonly, retain, nonatomic) GSDK_PBArray *groupList; // @synthesize groupList=mutableGroupList_;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, retain, nonatomic) GSDK_PBArray *lengthDelimitedList; // @synthesize lengthDelimitedList=mutableLengthDelimitedList_;
@property(readonly, nonatomic) int number; // @synthesize number=number_;
- (unsigned long long)serializedSize;
- (unsigned long long)serializedSizeAsMessageSetExtension;
@property(readonly, retain, nonatomic) GSDK_PBArray *varintList; // @synthesize varintList=mutableVarintList_;
- (void)writeAsMessageSetExtensionToOutput:(id)arg1;
- (void)writeToOutput:(id)arg1;

@end

