//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSDK_GTMABAddressBook : NSObject
{
    void *addressBook_;
}

+ (id)addressBook;
+ (id)localizedLabel:(id)arg1;
- (_Bool)addRecord:(id)arg1;
- (void *)addressBookRef;
- (void)dealloc;
- (id)groupForId:(int)arg1;
- (id)groups;
- (id)groupsWithCompositeNameWithPrefix:(id)arg1;
- (_Bool)hasUnsavedChanges;
- (id)init;
- (id)people;
- (id)peopleWithCompositeNameWithPrefix:(id)arg1;
- (id)personForId:(int)arg1;
- (_Bool)removeRecord:(id)arg1;
- (_Bool)save;

@end

