//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface GSDK_GTMRegexStringSegment : NSObject
{
    NSData *utf8StrBuf_;
    CDStruct_912cb5d2 *regMatches_;
    unsigned long long numRegMatches_;
    _Bool isMatch_;
}

- (void)dealloc;
- (id)description;
- (id)init;
- (id)initWithUTF8StrBuf:(id)arg1 regMatches:(CDStruct_912cb5d2 *)arg2 numRegMatches:(unsigned long long)arg3 isMatch:(_Bool)arg4;
- (_Bool)isMatch;
- (id)string;
- (id)subPatternString:(unsigned long long)arg1;

@end

