//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface GSDK_GTMURLBuilder : NSObject
{
    NSMutableDictionary *params_;
    NSString *baseURLString_;
}

+ (id)builderWithString:(id)arg1;
+ (id)builderWithURL:(id)arg1;
- (id)URL;
- (id)URLString;
@property(readonly, nonatomic) NSString *baseURLString; // @synthesize baseURLString=baseURLString_;
- (void)dealloc;
- (unsigned long long)hash;
- (id)init;
- (id)initWithString:(id)arg1;
- (long long)integerValueForParameter:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)parameters;
- (void)removeParameter:(id)arg1;
- (void)setIntegerValue:(long long)arg1 forParameter:(id)arg2;
- (void)setParameters:(id)arg1;
- (void)setValue:(id)arg1 forParameter:(id)arg2;
- (id)valueForParameter:(id)arg1;

@end

