//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface GSDK_PBCodedInputStream : NSObject
{
    NSData *buffer_;
    struct PBInputBufferState state_;
    int lastTag_;
    unsigned long long recursionDepth_;
}

+ (id)streamWithData:(id)arg1;
- (unsigned long long)bytesUntilLimit;
- (void)checkLastTagWas:(int)arg1;
- (void)dealloc;
- (id)initWithData:(id)arg1;
- (_Bool)isAtEnd;
- (void)popLimit:(unsigned long long)arg1;
- (unsigned long long)position;
- (unsigned long long)pushLimit:(unsigned long long)arg1;
- (_Bool)readBool;
- (id)readData;
- (double)readDouble;
- (int)readEnum;
- (unsigned int)readFixed32;
- (unsigned long long)readFixed64;
- (float)readFloat;
- (void)readGroup:(int)arg1 builder:(id)arg2 extensionRegistry:(id)arg3;
- (int)readInt32;
- (long long)readInt64;
- (void)readMessage:(id)arg1 extensionRegistry:(id)arg2;
- (int)readSFixed32;
- (long long)readSFixed64;
- (int)readSInt32;
- (long long)readSInt64;
- (id)readString;
- (int)readTag;
- (unsigned int)readUInt32;
- (unsigned long long)readUInt64;
- (void)readUnknownGroup:(int)arg1 builder:(id)arg2;
- (_Bool)skipField:(int)arg1;
- (void)skipMessage;

@end

