//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSDictionary, NSError, NSMutableData, NSRunLoop, NSString, NSURLConnection;

@interface HttpAsynConnection : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    _Bool finish;
    NSString *srcURL;
    NSString *sslFile;
    NSDictionary *responseHeader;
    NSMutableData *responseData;
    long long getDataTime;
    long long responseCode;
    NSString *statusString;
    NSError *responseError;
    NSError *connError;
    NSURLConnection *conn;
    NSRunLoop *runLoop;
}

@property(retain) NSURLConnection *conn; // @synthesize conn;
@property(retain) NSError *connError; // @synthesize connError;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
@property _Bool finish; // @synthesize finish;
@property(readonly) long long getDataTime; // @synthesize getDataTime;
@property(readonly) long long responseCode; // @synthesize responseCode;
@property(retain) NSMutableData *responseData; // @synthesize responseData;
@property(retain) NSError *responseError; // @synthesize responseError;
@property(copy) NSDictionary *responseHeader; // @synthesize responseHeader;
@property(retain) NSRunLoop *runLoop; // @synthesize runLoop;
@property(retain) NSString *srcURL; // @synthesize srcURL;
@property(retain) NSString *sslFile; // @synthesize sslFile;
@property NSString *statusString; // @synthesize statusString;
- (_Bool)shouldTrustProtectionSpace:(id)arg1;
- (void)startRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

