//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@class NSSet;

@interface NSArray (ALUtils)
- (id)al_randomArrayElement;
@property(readonly, copy, nonatomic) NSSet *al_uniqueObjects; // @dynamic al_uniqueObjects;
@end

