//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@class NSNumber;

@interface NSDate (ALUtils)
+ (double)al_timeIntervalNow;
- (id)al_dateByAddingOffsetInDays:(long long)arg1;
@property(readonly, nonatomic) __weak NSDate *al_tomorrow; // @dynamic al_tomorrow;
@property(readonly, nonatomic) NSNumber *al_unixTimestampInMilliseconds; // @dynamic al_unixTimestampInMilliseconds;
@property(readonly, nonatomic) NSNumber *al_unixTimestampInSeconds; // @dynamic al_unixTimestampInSeconds;
@property(readonly, nonatomic) __weak NSDate *al_yesterday; // @dynamic al_yesterday;
@end

