//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@class NSString;

@interface NSDictionary (ALUtils)
- (id)al_dictionaryByURLEncodingKeysAndValues;
@property(readonly, copy, nonatomic) NSString *al_httpGetQueryStringWithMembers; // @dynamic al_httpGetQueryStringWithMembers;
@end

