//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumber.h"

@interface NSNumber (ALUtils)
+ (id)al_numberWithString:(id)arg1;
- (id)al_stringValueWithFormat:(unsigned long long)arg1;
@property(readonly, nonatomic) double al_timeIntervalValue; // @dynamic al_timeIntervalValue;
@end

