//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (GADNSURLUtilities)
- (id)gad_URLByAppendingQueryParameters:(id)arg1;
- (id)gad_absoluteStringWithoutFragmentComponent;
- (id)gad_canonicalURL;
- (id)gad_dictionaryFromQueryParametersAndConvertKeysToLowercase:(_Bool)arg1;
- (id)gad_impressionTicket;
- (_Bool)gad_isHostEqualToString:(id)arg1 caseSensitive:(_Bool)arg2;
- (_Bool)gad_isSchemeEqualToString:(id)arg1 caseSensitive:(_Bool)arg2;
- (id)gad_parameterValueForKey:(id)arg1;
- (id)gad_parameterValuesForKey:(id)arg1;
@end

