//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CDAudioInterruptProtocol.h"

@class NSString;

@interface SimpleAudioEngine : NSObject <CDAudioInterruptProtocol>
{
    _Bool mute_;
    _Bool enabled_;
}

+ (id)alloc;
+ (void)end;
+ (id)sharedEngine;
@property float backgroundMusicVolume;
- (void)dealloc;
@property float effectsVolume;
- (_Bool)enabled;
- (id)init;
- (_Bool)isBackgroundMusicPlaying;
- (_Bool)mute;
- (void)pauseAllEffects;
- (void)pauseBackgroundMusic;
- (void)pauseEffect:(unsigned int)arg1;
- (void)playBackgroundMusic:(id)arg1;
- (void)playBackgroundMusic:(id)arg1 loop:(_Bool)arg2;
- (unsigned int)playEffect:(id)arg1 loop:(_Bool)arg2;
- (unsigned int)playEffect:(id)arg1 loop:(_Bool)arg2 pitch:(float)arg3 pan:(float)arg4 gain:(float)arg5;
- (void)preloadBackgroundMusic:(id)arg1;
- (void)preloadEffect:(id)arg1;
- (void)resumeAllEffects;
- (void)resumeBackgroundMusic;
- (void)resumeEffect:(unsigned int)arg1;
- (void)rewindBackgroundMusic;
- (void)setEnabled:(_Bool)arg1;
- (void)setMute:(_Bool)arg1;
- (id)soundSourceForFile:(id)arg1;
- (void)stopAllEffects;
- (void)stopBackgroundMusic;
- (void)stopEffect:(unsigned int)arg1;
- (void)unloadEffect:(id)arg1;
@property(readonly) _Bool willPlayBackgroundMusic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

