//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TAGTrackingTag.h"

@interface TAGArbitraryPixel : TAGTrackingTag
{
}

+ (id)functionId;
+ (id)urlKey;
- (void)addDictionary:(id)arg1 toArray:(id)arg2;
- (void)cacheUnrepeatableId:(id)arg1;
- (void)clearCache;
- (void)evaluateTrackingTag:(id)arg1;
- (id)getHitSender;
- (id)getQueryParametersStringFromArray:(id)arg1;
- (_Bool)idInCache:(id)arg1;
- (_Bool)idInPlist:(id)arg1;
- (_Bool)idProcessed:(id)arg1;
- (id)init;

@end

