//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface TAGBoolean : NSObject <NSCopying, NSCoding>
{
    _Bool _boolValue;
}

+ (id)booleanWithBool:(_Bool)arg1;
+ (id)booleanWithString:(id)arg1;
+ (void)initialize;
+ (id)no;
+ (id)yes;
@property(nonatomic) _Bool boolValue; // @synthesize boolValue=_boolValue;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithBool:(_Bool)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;

@end

