//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface TAGExpandedRuleBuilder : NSObject
{
    NSMutableArray *_positivePredicates;
    NSMutableArray *_negativePredicates;
    NSMutableArray *_addTags;
    NSMutableArray *_removeTags;
    NSMutableArray *_addMacros;
    NSMutableArray *_removeMacros;
}

- (void).cxx_destruct;
- (void)addAddMacro:(id)arg1;
- (void)addAddTag:(id)arg1;
@property(retain, nonatomic) NSMutableArray *addMacros; // @synthesize addMacros=_addMacros;
- (void)addNegativePredicate:(id)arg1;
- (void)addPositivePredicate:(id)arg1;
- (void)addRemoveMacro:(id)arg1;
- (void)addRemoveTag:(id)arg1;
@property(retain, nonatomic) NSMutableArray *addTags; // @synthesize addTags=_addTags;
- (id)build;
- (id)init;
@property(retain, nonatomic) NSMutableArray *negativePredicates; // @synthesize negativePredicates=_negativePredicates;
@property(retain, nonatomic) NSMutableArray *positivePredicates; // @synthesize positivePredicates=_positivePredicates;
@property(retain, nonatomic) NSMutableArray *removeMacros; // @synthesize removeMacros=_removeMacros;
@property(retain, nonatomic) NSMutableArray *removeTags; // @synthesize removeTags=_removeTags;

@end

