//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TAGFunctionCallImplementation.h"

@interface TAGEncode : TAGFunctionCallImplementation
{
}

+ (id)arg0Key;
+ (id)functionId;
+ (id)inputFormatKey;
+ (id)noPaddingKey;
+ (id)outputFormatKey;
- (id)evaluate:(id)arg1;
- (id)init;
- (_Bool)isCacheable;

@end

