//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface TAGExpandedResource : NSObject
{
    int _resourceFormatVersion;
    NSArray *_rules;
    NSString *_version;
    NSDictionary *_macros;
}

+ (id)builder;
- (void).cxx_destruct;
- (id)allMacros;
- (id)description;
- (id)initWithRules:(id)arg1 macros:(id)arg2 version:(id)arg3 resourceFormatVersion:(int)arg4;
@property(readonly, retain, nonatomic) NSDictionary *macros; // @synthesize macros=_macros;
- (id)macrosByName:(id)arg1;
@property(readonly, nonatomic) int resourceFormatVersion; // @synthesize resourceFormatVersion=_resourceFormatVersion;
@property(readonly, retain, nonatomic) NSArray *rules; // @synthesize rules=_rules;
@property(readonly, copy, nonatomic) NSString *version; // @synthesize version=_version;

@end

