//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TAGPreviewManager : NSObject
{
    long long _previewMode;
    NSString *_ctfeUrlPath;
    NSString *_containerId;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)clear;
@property(retain) NSString *containerId; // @synthesize containerId=_containerId;
- (id)containerIdForQuery:(id)arg1;
@property(retain) NSString *ctfeUrlPath; // @synthesize ctfeUrlPath=_ctfeUrlPath;
- (_Bool)generatePreviewDataForUrl:(id)arg1;
- (id)init;
- (_Bool)isPreviewingContainer:(id)arg1;
@property long long previewMode; // @synthesize previewMode=_previewMode;

@end

