//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPBMutableArray;

@interface TAGPPublicIdMapping : TAGPBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasId_pArray; // @dynamic hasId_pArray;
@property(nonatomic) _Bool hasPreviewAuthCode; // @dynamic hasPreviewAuthCode;
@property(retain, nonatomic) TAGPBMutableArray *id_pArray; // @dynamic id_pArray;
@property(retain, nonatomic) NSString *previewAuthCode; // @dynamic previewAuthCode;

@end

