//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"

@class NSMutableData, NSString, NSURLConnection;

@interface TAGResourceLoader : NSObject <NSURLConnectionDataDelegate>
{
    id <TAGLoadCallback> _callback;
    NSString *_ctfeServerAddress;
    NSString *_ctfeUrlPathAndQuery;
    NSString *_previousVersion;
    NSURLConnection *_connection;
    NSMutableData *_responseData;
    long long _statusCode;
    NSString *_containerId;
    NSString *_defaultCtfeUrlPathAndQuery;
}

+ (id)sdkVersion;
- (void).cxx_destruct;
@property(retain, nonatomic) id <TAGLoadCallback> callback; // @synthesize callback=_callback;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
@property(copy, nonatomic) NSString *containerId; // @synthesize containerId=_containerId;
@property(copy) NSString *ctfeServerAddress; // @synthesize ctfeServerAddress=_ctfeServerAddress;
@property(readonly, copy, nonatomic) NSString *ctfeUrl;
@property(copy, nonatomic) NSString *ctfeUrlPathAndQuery; // @synthesize ctfeUrlPathAndQuery=_ctfeUrlPathAndQuery;
@property(copy, nonatomic) NSString *defaultCtfeUrlPathAndQuery; // @synthesize defaultCtfeUrlPathAndQuery=_defaultCtfeUrlPathAndQuery;
- (id)initWithContainerId:(id)arg1;
- (void)loadResourceAsync;
@property(copy) NSString *previousVersion; // @synthesize previousVersion=_previousVersion;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

