//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSConnectivityMonitor : NSObject
{
}

+ (void)dealloc;
+ (void)sendToWebview:(struct __SCNetworkReachability *)arg1 flags:(unsigned int)arg2;
+ (void)setConnectionMonitoring:(_Bool)arg1;
+ (void)startListening:(id)arg1;
+ (void)startReachabilityListener;
+ (void)stopAll;
+ (void)stopListening:(id)arg1;
+ (void)stopReachabilityListener;
+ (void)updateListeningStatus;

@end

