//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class UADSResolve;

@interface UADSResolveOperation : NSOperation
{
    CDUnknownBlockType _completeBlock;
    UADSResolve *_resolve;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completeBlock; // @synthesize completeBlock=_completeBlock;
- (id)initWithHostName:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)main;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) UADSResolve *resolve; // @synthesize resolve=_resolve;
- (void)startObserving;
- (void)stopObserving;

@end

