//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSApiSdk : NSObject
{
}

+ (void)WebViewExposed_getDebugMode:(id)arg1;
+ (void)WebViewExposed_initComplete:(id)arg1;
+ (void)WebViewExposed_loadComplete:(id)arg1;
+ (void)WebViewExposed_logDebug:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_logError:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_logInfo:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_logWarning:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_reinitialize:(id)arg1;
+ (void)WebViewExposed_setDebugMode:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setShowTimeout:(id)arg1 callback:(id)arg2;

@end

