//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSClientProperties : NSObject
{
}

+ (id)getAppName;
+ (id)getAppVersion;
+ (id)getCurrentViewController;
+ (id)getDelegate;
+ (id)getGameId;
+ (int)getSupportedOrientations;
+ (id)getSupportedOrientationsPlist;
+ (_Bool)isAppDebuggable;
+ (void)setCurrentViewController:(id)arg1;
+ (void)setDelegate:(id)arg1;
+ (void)setGameId:(id)arg1;

@end

