//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSApiStorage : NSObject
{
}

+ (void)WebViewExposed_clear:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_delete:(id)arg1 key:(id)arg2 callback:(id)arg3;
+ (void)WebViewExposed_get:(id)arg1 key:(id)arg2 callback:(id)arg3;
+ (void)WebViewExposed_getKeys:(id)arg1 key:(id)arg2 recursive:(id)arg3 callback:(id)arg4;
+ (void)WebViewExposed_read:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_set:(id)arg1 key:(id)arg2 value:(id)arg3 callback:(id)arg4;
+ (void)WebViewExposed_write:(id)arg1 callback:(id)arg2;
+ (long long)getStorageTypeFromString:(id)arg1;

@end

