//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class UADSWebRequest;

@interface UADSWebRequestOperation : NSOperation
{
    UADSWebRequest *_request;
    CDUnknownBlockType _completeBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completeBlock; // @synthesize completeBlock=_completeBlock;
- (id)initWithUrl:(id)arg1 requestType:(id)arg2 headers:(id)arg3 body:(id)arg4 completeBlock:(CDUnknownBlockType)arg5 connectTimeout:(int)arg6;
- (void)main;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) UADSWebRequest *request; // @synthesize request=_request;
- (void)startObserving;
- (void)stopObserving;

@end

