//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSCacheQueue : NSObject
{
}

+ (void)cancelAllDownloads;
+ (_Bool)download:(id)arg1 target:(id)arg2;
+ (_Bool)downloadFile:(id)arg1 target:(id)arg2;
+ (int)getConnectTimeout;
+ (int)getProgressInterval;
+ (_Bool)hasOperations;
+ (void)setConnectTimeout:(int)arg1;
+ (void)setProgressInterval:(int)arg1;
+ (void)start;

@end

