//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UADSMetaData.h"

@interface UADSMediationMetaData : UADSMetaData
{
}

- (id)init;
- (void)setName:(id)arg1;
- (void)setOrdinal:(int)arg1;
- (void)setVersion:(id)arg1;

@end

