//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface UADSInvocation : NSObject
{
    int _invocationId;
    NSMutableArray *_invocations;
    NSMutableArray *_responses;
}

+ (id)getInvocationWithId:(int)arg1;
+ (void)setClassTable:(id)arg1;
- (void).cxx_destruct;
- (void)addInvocation:(id)arg1 methodName:(id)arg2 parameters:(id)arg3 callback:(id)arg4;
- (id)init;
@property(nonatomic) int invocationId; // @synthesize invocationId=_invocationId;
@property(retain, nonatomic) NSMutableArray *invocations; // @synthesize invocations=_invocations;
- (_Bool)nextInvocation;
@property(retain, nonatomic) NSMutableArray *responses; // @synthesize responses=_responses;
- (void)sendInvocationCallback;
- (void)setInvocationResponseWithStatus:(id)arg1 error:(id)arg2 params:(id)arg3;

@end

