//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UADSInitializeState.h"

@interface UADSInitializeStateLoadWeb : UADSInitializeState
{
    int _retries;
    int _maxRetries;
    int _retryDelay;
}

- (id)execute;
- (id)initWithConfiguration:(id)arg1 retries:(int)arg2 retryDelay:(int)arg3;
@property(nonatomic) int maxRetries; // @synthesize maxRetries=_maxRetries;
@property(nonatomic) int retries; // @synthesize retries=_retries;
@property(nonatomic) int retryDelay; // @synthesize retryDelay=_retryDelay;

@end

