//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UADSInitializeState.h"

@interface UADSInitializeStateRetry : UADSInitializeState
{
    int _retryDelay;
    id _retryState;
}

- (void).cxx_destruct;
- (id)execute;
- (id)initWithConfiguration:(id)arg1 retryState:(id)arg2 retryDelay:(int)arg3;
@property(nonatomic) int retryDelay; // @synthesize retryDelay=_retryDelay;
@property(retain, nonatomic) id retryState; // @synthesize retryState=_retryState;

@end

