//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSApiDeviceInfo : NSObject
{
}

+ (void)WebViewExposed_getAdvertisingTrackingId:(id)arg1;
+ (void)WebViewExposed_getBatteryLevel:(id)arg1;
+ (void)WebViewExposed_getBatteryStatus:(id)arg1;
+ (void)WebViewExposed_getConnectionType:(id)arg1;
+ (void)WebViewExposed_getDeviceVolume:(id)arg1;
+ (void)WebViewExposed_getFreeMemory:(id)arg1;
+ (void)WebViewExposed_getFreeSpace:(id)arg1;
+ (void)WebViewExposed_getHeadset:(id)arg1;
+ (void)WebViewExposed_getLimitAdTrackingFlag:(id)arg1;
+ (void)WebViewExposed_getModel:(id)arg1;
+ (void)WebViewExposed_getNetworkOperator:(id)arg1;
+ (void)WebViewExposed_getNetworkOperatorName:(id)arg1;
+ (void)WebViewExposed_getNetworkType:(id)arg1;
+ (void)WebViewExposed_getOsVersion:(id)arg1;
+ (void)WebViewExposed_getScreenBrightness:(id)arg1;
+ (void)WebViewExposed_getScreenHeight:(id)arg1;
+ (void)WebViewExposed_getScreenScale:(id)arg1;
+ (void)WebViewExposed_getScreenWidth:(id)arg1;
+ (void)WebViewExposed_getStatusBarHeight:(id)arg1;
+ (void)WebViewExposed_getStatusBarWidth:(id)arg1;
+ (void)WebViewExposed_getSupportedOrientations:(id)arg1;
+ (void)WebViewExposed_getSupportedOrientationsPlist:(id)arg1;
+ (void)WebViewExposed_getSystemLanguage:(id)arg1;
+ (void)WebViewExposed_getTimeZone:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_getTotalMemory:(id)arg1;
+ (void)WebViewExposed_getTotalSpace:(id)arg1;
+ (void)WebViewExposed_getUniqueEventId:(id)arg1;
+ (void)WebViewExposed_getUserInterfaceIdiom:(id)arg1;
+ (void)WebViewExposed_isRooted:(id)arg1;
+ (void)WebViewExposed_isSimulator:(id)arg1;
+ (void)WebViewExposed_isStatusBarHidden:(id)arg1;

@end

