//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSPlacement : NSObject
{
}

+ (long long)currentState:(id)arg1;
+ (long long)formatStringToPlacementState:(id)arg1;
+ (id)getDefaultPlacement;
+ (long long)getPlacementState;
+ (long long)getPlacementState:(id)arg1;
+ (_Bool)isReady;
+ (_Bool)isReady:(id)arg1;
+ (void)reset;
+ (void)setDefaultPlacement:(id)arg1;
+ (void)setPlacementState:(id)arg1 placementState:(id)arg2;

@end

