//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface UADSMetaData : NSObject
{
    NSString *_category;
    NSMutableDictionary *_entries;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
- (void)commit;
@property(retain, nonatomic) NSMutableDictionary *entries; // @synthesize entries=_entries;
- (id)initWithCategory:(id)arg1;
- (void)set:(id)arg1 value:(id)arg2;

@end

