//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UADSWebViewMethodInvokeOperation.h"

@interface UADSWebViewShowOperation : UADSWebViewMethodInvokeOperation
{
}

+ (void)callback:(id)arg1;
- (id)initWithPlacementId:(id)arg1 parametersDictionary:(id)arg2;
- (void)main;

@end

