//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSApiAdUnit : NSObject
{
}

+ (void)WebViewExposed_close:(id)arg1;
+ (void)WebViewExposed_getShouldAutorotate:(id)arg1;
+ (void)WebViewExposed_getStatusBarHidden:(id)arg1;
+ (void)WebViewExposed_getSupportedOrientations:(id)arg1;
+ (void)WebViewExposed_getTransform:(id)arg1;
+ (void)WebViewExposed_getViewFrame:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_getViews:(id)arg1;
+ (void)WebViewExposed_open:(id)arg1 supportedOrientations:(id)arg2 callback:(id)arg3;
+ (void)WebViewExposed_open:(id)arg1 supportedOrientations:(id)arg2 statusBarHidden:(id)arg3 callback:(id)arg4;
+ (void)WebViewExposed_open:(id)arg1 supportedOrientations:(id)arg2 statusBarHidden:(id)arg3 shouldAutorotate:(id)arg4 callback:(id)arg5;
+ (void)WebViewExposed_setKeepScreenOn:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setShouldAutorotate:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setStatusBarHidden:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setSupportedOrientations:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setTransform:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setViewFrame:(id)arg1 x:(id)arg2 y:(id)arg3 width:(id)arg4 height:(id)arg5 callback:(id)arg6;
+ (void)WebViewExposed_setViews:(id)arg1 callback:(id)arg2;
+ (id)getAdUnit;
+ (void)setAdUnit:(id)arg1;

@end

