//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSWebRequestQueue : NSObject
{
}

+ (void)cancelAllOperations;
+ (void)requestUrl:(id)arg1 type:(id)arg2 headers:(id)arg3 body:(id)arg4 completeBlock:(CDUnknownBlockType)arg5 connectTimeout:(int)arg6;
+ (void)requestUrl:(id)arg1 type:(id)arg2 headers:(id)arg3 completeBlock:(CDUnknownBlockType)arg4 connectTimeout:(int)arg5;
+ (_Bool)resolve:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
+ (void)start;

@end

