//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSApiRequest : NSObject
{
}

+ (void)WebViewExposed_get:(id)arg1 url:(id)arg2 headers:(id)arg3 connectTimeout:(id)arg4 callback:(id)arg5;
+ (void)WebViewExposed_head:(id)arg1 url:(id)arg2 headers:(id)arg3 connectTimeout:(id)arg4 callback:(id)arg5;
+ (void)WebViewExposed_post:(id)arg1 url:(id)arg2 body:(id)arg3 headers:(id)arg4 connectTimeout:(id)arg5 callback:(id)arg6;
+ (id)getHeadersArray:(id)arg1;
+ (id)getHeadersMap:(id)arg1;
+ (void)sendFailed:(id)arg1 url:(id)arg2 error:(id)arg3;
+ (void)sendSuccess:(id)arg1 url:(id)arg2 response:(id)arg3 responseCode:(long long)arg4 headers:(id)arg5;

@end

