//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UADSApiCache : NSObject
{
}

+ (void)WebViewExposed_deleteFile:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_download:(id)arg1 fileId:(id)arg2 callback:(id)arg3;
+ (void)WebViewExposed_getFileInfo:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_getFilePath:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_getFiles:(id)arg1;
+ (void)WebViewExposed_getFreeSpace:(id)arg1;
+ (void)WebViewExposed_getHash:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_getProgressInterval:(id)arg1;
+ (void)WebViewExposed_getTimeouts:(id)arg1;
+ (void)WebViewExposed_getTotalSpace:(id)arg1;
+ (void)WebViewExposed_isCaching:(id)arg1;
+ (void)WebViewExposed_setProgressInterval:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_setTimeouts:(id)arg1 callback:(id)arg2;
+ (void)WebViewExposed_stop:(id)arg1;
+ (id)fileIdToFilename:(id)arg1;
+ (id)getFileDictionary:(id)arg1;

@end

