//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDelegate.h"

@class NSCondition, NSDictionary, NSError, NSMutableData, NSMutableURLRequest, NSString, NSURLConnection;

@interface UADSWebRequest : NSObject <NSURLConnectionDelegate>
{
    _Bool _canceled;
    _Bool _finished;
    int _connectTimeout;
    NSString *_url;
    NSString *_requestType;
    NSString *_body;
    NSDictionary *_headers;
    NSDictionary *_responseHeaders;
    NSMutableData *_receivedData;
    NSError *_error;
    long long _expectedContentLength;
    long long _responseCode;
    NSCondition *_blockCondition;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _startBlock;
    NSMutableURLRequest *_request;
    NSURLConnection *_connection;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSCondition *blockCondition; // @synthesize blockCondition=_blockCondition;
@property(retain, nonatomic) NSString *body; // @synthesize body=_body;
- (void)cancel;
@property(nonatomic) _Bool canceled; // @synthesize canceled=_canceled;
@property(nonatomic) int connectTimeout; // @synthesize connectTimeout=_connectTimeout;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) long long expectedContentLength; // @synthesize expectedContentLength=_expectedContentLength;
@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(retain, nonatomic) NSDictionary *headers; // @synthesize headers=_headers;
- (id)initWithUrl:(id)arg1 requestType:(id)arg2 headers:(id)arg3 connectTimeout:(int)arg4;
- (id)makeRequest;
- (id)makeUserInfoDictionary:(long long)arg1 message:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
- (void)receiveTimerTimedOut;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSString *requestType; // @synthesize requestType=_requestType;
@property(nonatomic) long long responseCode; // @synthesize responseCode=_responseCode;
@property(retain, nonatomic) NSDictionary *responseHeaders; // @synthesize responseHeaders=_responseHeaders;
@property(copy, nonatomic) CDUnknownBlockType startBlock; // @synthesize startBlock=_startBlock;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

