//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UADSInitializeState.h"

@class NSString;

@interface UADSInitializeStateCreate : UADSInitializeState
{
    NSString *_webViewData;
}

- (void).cxx_destruct;
- (id)execute;
- (id)initWithConfiguration:(id)arg1 webViewData:(id)arg2;
@property(retain) NSString *webViewData; // @synthesize webViewData=_webViewData;

@end

