//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

#import "CCUITextInput.h"

@class NSString, UIColor, UIFont, UILabel;

@interface UITextView (CCUITextInput) <CCUITextInput>
@property(nonatomic, setter=ccui_setTextHorizontalAlignment:) long long ccui_alignment;
@property(retain, nonatomic, setter=ccui_setFont:) UIFont *ccui_font;
@property(retain, nonatomic, setter=ccui_setPlaceholder:) NSString *ccui_placeholder;
@property(retain, nonatomic, setter=ccui_setPlaceholderLabel:) UILabel *ccui_placeholderLabel;
@property(nonatomic, setter=ccui_setSecureTextEntry:) _Bool ccui_secureTextEntry;
- (void)ccui_setDelegate:(id)arg1;
@property(retain, nonatomic, setter=ccui_setText:) NSString *ccui_text;
@property(retain, nonatomic, setter=ccui_setTextColor:) UIColor *ccui_textColor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

