//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPMoviePlayerController;

@interface UIVideoViewWrapperIos : NSObject
{
    int _left;
    int _top;
    int _width;
    int _height;
    _Bool _keepRatioEnabled;
    struct VideoPlayer *_videoPlayer;
    MPMoviePlayerController *_moviePlayer;
}

- (void)dealloc;
- (id)init:(void *)arg1;
- (_Bool)isFullScreenEnabled;
@property(retain, nonatomic) MPMoviePlayerController *moviePlayer; // @synthesize moviePlayer=_moviePlayer;
- (void)pause;
- (void)play;
- (void)playStateChange;
- (void)resume;
- (void)seekTo:(float)arg1;
- (void)setFrame:(int)arg1:(int)arg2:(int)arg3:(int)arg4;
- (void)setFullScreenEnabled:(_Bool)arg1;
- (void)setKeepRatioEnabled:(_Bool)arg1;
- (void)setURL:(int)arg1:(basic_string_a490aa4c *)arg2;
- (void)setVisible:(_Bool)arg1;
- (void)stop;
- (void)videoFinished:(id)arg1;

@end

