//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (ALUtils)
+ (id)al_instantiateFromXib;
- (void)al_pinToSuperview;
- (void)al_pinToSuperviewWithTop:(unsigned long long)arg1 left:(unsigned long long)arg2 bottom:(unsigned long long)arg3 right:(unsigned long long)arg4;
@end

