//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SKStoreProductViewControllerDelegate.h"

@class NSDictionary, NSNumber, NSString, SKStoreProductViewController, VungleAdLegacy, VungleCacheManager, VungleLegacyAdReport, VungleLogCoordinator, VungleNetworkManager, VunglePublisherInformation, VungleReportAdController, VungleVideoPlayer, VungleWebView;

@interface VungleAdViewController : UIViewController <SKStoreProductViewControllerDelegate>
{
    _Bool _didPlayOnce;
    double _adStart;
    _Bool _incentivized;
    _Bool _videoIsPlaying;
    _Bool _validCTAURLResolved;
    _Bool _statusBarHidden;
    _Bool _willShowProductView;
    _Bool _firstView;
    _Bool _finished;
    _Bool _storeLoaded;
    _Bool _removeLastBundle;
    CDUnknownBlockType _doneWithAdBlock;
    VunglePublisherInformation *_publisherInformation;
    NSNumber *_appStoreId;
    NSDictionary *_eventsDisplayed;
    NSDictionary *_events;
    double _timeViewed;
    double _videoLength;
    VungleVideoPlayer *_videoPlayer;
    VungleWebView *_webView;
    VungleAdLegacy *_bundle;
    SKStoreProductViewController *_storeViewController;
    VungleNetworkManager *_networkManager;
    VungleLogCoordinator *_logController;
    id <VungleInterstitialAdDelegate> _interstitialAdDelegate;
    VungleLegacyAdReport *_report;
    VungleReportAdController *_reportAdController;
    VungleCacheManager *_cacheManager;
    id <VungleSDKDelegate> _sdkDelegate;
    unsigned long long _supportedOrientations;
}

- (void).cxx_destruct;
- (void)addClickSequenceToReport:(id)arg1;
- (void)appDidEnterBackground:(id)arg1;
@property(copy) NSNumber *appStoreId; // @synthesize appStoreId=_appStoreId;
- (void)appWillEnterForeground:(id)arg1;
@property(retain, nonatomic) VungleAdLegacy *bundle; // @synthesize bundle=_bundle;
@property(nonatomic) __weak VungleCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)dispatchEventNamed:(id)arg1 subCategory:(id)arg2 max:(int)arg3;
- (void)dispatchEventURLs:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType doneWithAdBlock; // @synthesize doneWithAdBlock=_doneWithAdBlock;
@property(copy, nonatomic) NSDictionary *events; // @synthesize events=_events;
@property(retain) NSDictionary *eventsDisplayed; // @synthesize eventsDisplayed=_eventsDisplayed;
- (void)finishAdView:(_Bool)arg1;
@property _Bool finished; // @synthesize finished=_finished;
@property _Bool firstView; // @synthesize firstView=_firstView;
@property(nonatomic) _Bool incentivized; // @synthesize incentivized=_incentivized;
- (id)initWithAdLegacy:(id)arg1 networkManager:(id)arg2 reportAdController:(id)arg3 cacheManager:(id)arg4 videoPlayer:(id)arg5 supportedOrientations:(unsigned long long)arg6 interstitialAdDelegate:(id)arg7 logController:(id)arg8 sdkDelegate:(id)arg9;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) __weak id <VungleInterstitialAdDelegate> interstitialAdDelegate; // @synthesize interstitialAdDelegate=_interstitialAdDelegate;
- (_Bool)isAdSuccessfullyViewed;
@property(nonatomic) __weak VungleLogCoordinator *logController; // @synthesize logController=_logController;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
- (id)playStateWithPlayer:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)prepareStoreViewControllerWithAppID:(id)arg1;
- (_Bool)presentAppStoreWithDelegate:(id)arg1;
- (void)presentStoreDelayed:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
@property(copy, nonatomic) VunglePublisherInformation *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
- (void)reactToAppEnteringBackground;
- (void)reactToAppEnteringForeground;
@property _Bool removeLastBundle; // @synthesize removeLastBundle=_removeLastBundle;
@property(retain, nonatomic) VungleLegacyAdReport *report; // @synthesize report=_report;
@property(nonatomic) __weak VungleReportAdController *reportAdController; // @synthesize reportAdController=_reportAdController;
@property(nonatomic) __weak id <VungleSDKDelegate> sdkDelegate; // @synthesize sdkDelegate=_sdkDelegate;
@property _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
@property _Bool storeLoaded; // @synthesize storeLoaded=_storeLoaded;
@property(retain, nonatomic) SKStoreProductViewController *storeViewController; // @synthesize storeViewController=_storeViewController;
@property(nonatomic) unsigned long long supportedOrientations; // @synthesize supportedOrientations=_supportedOrientations;
@property double timeViewed; // @synthesize timeViewed=_timeViewed;
@property(nonatomic) _Bool validCTAURLResolved; // @synthesize validCTAURLResolved=_validCTAURLResolved;
@property(nonatomic) _Bool videoIsPlaying; // @synthesize videoIsPlaying=_videoIsPlaying;
@property double videoLength; // @synthesize videoLength=_videoLength;
@property(retain, nonatomic) VungleVideoPlayer *videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) VungleWebView *webView; // @synthesize webView=_webView;
@property _Bool willShowProductView; // @synthesize willShowProductView=_willShowProductView;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)updateLatestPlayInfo;
- (void)updateReportAd;
- (void)updateViewProgressWithPlayer:(id)arg1;
- (id)validInAppDownloadUrl:(id)arg1;
- (void)videoCTAClicked:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)vunglePostRollAction:(int)arg1;
- (void)vungleVideoPlayerDidFinish:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

