//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface VungleTaskToBlockMapping : NSObject
{
    _Bool _isTerminating;
    NSMutableDictionary *_taskToOperation;
    NSMutableDictionary *_operationToBlock;
}

- (void).cxx_destruct;
- (void)addOperation:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)addTask:(id)arg1 withOperation:(id)arg2;
- (CDUnknownBlockType)blockForOperation:(id)arg1;
- (CDUnknownBlockType)blockForTask:(id)arg1;
- (void)cleanupMapping;
- (id)description;
- (id)init;
@property(nonatomic) _Bool isTerminating; // @synthesize isTerminating=_isTerminating;
- (id)keyForOperation:(id)arg1;
- (id)keyForTask:(id)arg1;
- (unsigned long long)objectsCount;
- (id)operationForTask:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *operationToBlock; // @synthesize operationToBlock=_operationToBlock;
- (void)removeMappingsForOperation:(id)arg1;
- (void)removeOperationWhileTerminating:(id)arg1 withTaskKey:(id)arg2;
- (void)removeTask:(id)arg1;
- (void)removeTaskWhileTerminating:(id)arg1 forOperation:(id)arg2;
- (void)replaceTask:(id)arg1 withNewTask:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *taskToOperation; // @synthesize taskToOperation=_taskToOperation;
- (unsigned long long)stateForTask:(id)arg1;
- (id)taskIdentifierForOperation:(id)arg1;

@end

