//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleDismissibleContainerView.h"

@interface VungleDismissibleWebViewContainerView : VungleDismissibleContainerView
{
    _Bool _willBeDismissed;
}

- (void)blankOutContentInWebView:(id)arg1;
- (void)didMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1 containedView:(id)arg2;
@property(nonatomic) _Bool willBeDismissed; // @synthesize willBeDismissed=_willBeDismissed;
- (void)willMoveToSuperview:(id)arg1;

@end

