//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIAlertViewDelegate.h"

@class AVPlayer, AVPlayerItem, NSDictionary, NSMutableDictionary, NSString, UIAlertView, VungleAdViewController, VungleConfigController, VunglePlayOptionsProvider;

@interface VungleVideoPlayer : UIView <UIAlertViewDelegate>
{
    _Bool _finishCallbackExecuted;
    _Bool _observerSet;
    _Bool _muted;
    _Bool _ctaEnabled;
    _Bool _ctaDisplayOntouch;
    _Bool _firstTime;
    _Bool _isLocal;
    _Bool _isPaused;
    float _closeDelay;
    float _closeDelayIncentivized;
    float _countdownDelay;
    float _ctaShowDelay;
    float _ctaButtonClickArea;
    double _startTime;
    NSString *_originalVideoUrl;
    VungleAdViewController *_adViewController;
    AVPlayer *_player;
    id _videoTimerObserver;
    id _videoTimerFineGrainObserver;
    NSMutableDictionary *_eventsPlayed;
    AVPlayerItem *_playerItem;
    NSDictionary *_incentivizedMetaData;
    VungleConfigController *_configController;
    id <VungleAssetLoader> _assetLoader;
    VunglePlayOptionsProvider *_playOptionsProvider;
    UIAlertView *_incentivizedAlertView;
    struct CGSize _originalCTAButtonSize;
}

+ (Class)layerClass;
+ (_Bool)requiresConstraintBasedLayout;
- (void).cxx_destruct;
@property(nonatomic) __weak VungleAdViewController *adViewController; // @synthesize adViewController=_adViewController;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
@property(nonatomic) __weak id <VungleAssetLoader> assetLoader; // @synthesize assetLoader=_assetLoader;
- (void)callToActionButtonTouchUpInside:(id)arg1;
- (_Bool)canPlay;
- (void)closeButtonTouchUpInside:(id)arg1;
@property(nonatomic) float closeDelay; // @synthesize closeDelay=_closeDelay;
@property(nonatomic) float closeDelayIncentivized; // @synthesize closeDelayIncentivized=_closeDelayIncentivized;
@property(nonatomic) __weak VungleConfigController *configController; // @synthesize configController=_configController;
@property(nonatomic) float countdownDelay; // @synthesize countdownDelay=_countdownDelay;
- (void)createUIElements;
- (void)ctaAction:(id)arg1;
@property(nonatomic) float ctaButtonClickArea; // @synthesize ctaButtonClickArea=_ctaButtonClickArea;
@property(nonatomic) _Bool ctaDisplayOntouch; // @synthesize ctaDisplayOntouch=_ctaDisplayOntouch;
@property(nonatomic) _Bool ctaEnabled; // @synthesize ctaEnabled=_ctaEnabled;
@property(nonatomic) float ctaShowDelay; // @synthesize ctaShowDelay=_ctaShowDelay;
- (double)currentPosition;
- (void)dealloc;
- (void)doSkip;
@property(retain, nonatomic) NSMutableDictionary *eventsPlayed; // @synthesize eventsPlayed=_eventsPlayed;
- (void)fadeIn:(id)arg1 duration:(double)arg2;
@property(nonatomic) _Bool firstTime; // @synthesize firstTime=_firstTime;
- (id)getInternalImageNamed:(id)arg1;
@property(retain, nonatomic) UIAlertView *incentivizedAlertView; // @synthesize incentivizedAlertView=_incentivizedAlertView;
@property(copy, nonatomic) NSDictionary *incentivizedMetaData; // @synthesize incentivizedMetaData=_incentivizedMetaData;
- (id)initWithAdPart:(id)arg1 assetLoader:(id)arg2 configController:(id)arg3 playOptionsProvider:(id)arg4 isMuted:(_Bool)arg5;
@property(nonatomic) _Bool isLocal; // @synthesize isLocal=_isLocal;
@property(nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
- (void)mute:(_Bool)arg1 firstTime:(_Bool)arg2;
- (void)muteButtonTouchUpInside:(id)arg1;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) struct CGSize originalCTAButtonSize; // @synthesize originalCTAButtonSize=_originalCTAButtonSize;
@property(copy, nonatomic) NSString *originalVideoUrl; // @synthesize originalVideoUrl=_originalVideoUrl;
- (void)pause;
- (void)play;
@property(copy, nonatomic) VunglePlayOptionsProvider *playOptionsProvider; // @synthesize playOptionsProvider=_playOptionsProvider;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
- (void)playerEnded:(id)arg1;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
- (void)resetButtons;
- (void)rewindAndPlay;
@property(retain, nonatomic) id videoTimerFineGrainObserver; // @synthesize videoTimerFineGrainObserver=_videoTimerFineGrainObserver;
@property(retain, nonatomic) id videoTimerObserver; // @synthesize videoTimerObserver=_videoTimerObserver;
- (void)setupUIConstraints;
- (void)skipAction:(id)arg1;
@property(readonly, nonatomic) double startTime; // @synthesize startTime=_startTime;
- (void)stop;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (double)videoLength;
- (void)waitForStreaming;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

