//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VungleAd;

@protocol VungleInterstitialAdDelegate <NSObject>
- (void)didDismissInterstitialAdViewControllerWithReportable:(id <VungleReportable>)arg1;
- (void)didFinishAdView:(VungleAd *)arg1 withSuccess:(_Bool)arg2;
- (void)willBackgroundAdViewControllerWithReportable:(id <VungleReportable>)arg1;
- (void)willDismissInterstitialAdViewControllerWithReportable:(id <VungleReportable>)arg1;
- (void)willPresentInterstitialAdViewControllerWithReportable:(id <VungleReportable>)arg1;
@end

