//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSMutableSet;

@interface VungleOperation : NSOperation
{
    long long _state;
    _Bool _hasFinishedAlready;
    NSMutableSet *_internalErrors;
    CDUnknownBlockType _finishHandler;
}

+ (id)keyPathsForValuesAffectingIsExecuting;
+ (id)keyPathsForValuesAffectingIsFinished;
+ (id)keyPathsForValuesAffectingIsReady;
- (void).cxx_destruct;
- (void)appendError:(id)arg1;
- (void)appendFinishHandler:(CDUnknownBlockType)arg1;
- (_Bool)canTransitionToState:(long long)arg1;
- (void)evaluateConditions;
- (void)execute;
- (void)finish;
@property(copy, nonatomic) CDUnknownBlockType finishHandler; // @synthesize finishHandler=_finishHandler;
- (void)finishWithErrors:(id)arg1;
- (void)finishedWithErrors:(id)arg1;
@property(nonatomic) _Bool hasFinishedAlready; // @synthesize hasFinishedAlready=_hasFinishedAlready;
- (id)init;
@property(retain, nonatomic) NSMutableSet *internalErrors; // @synthesize internalErrors=_internalErrors;
- (_Bool)isExecuting;
- (_Bool)isFinished;
- (_Bool)isReady;
@property(nonatomic, getter=state, setter=setState:) long long state;
- (void)start;
- (void)willEnqueue;

@end

