//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VungleMRAIDCommandFactory : NSObject
{
}

+ (id)buildCommand:(id)arg1 withParameters:(id)arg2 webView:(id)arg3;
+ (id)buildJSExpressionCommand:(id)arg1 webView:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;

@end

