//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleOperation.h"

@class NSDictionary, NSString, UIWebView;

@interface VungleJSCommandOperation : VungleOperation
{
    _Bool _isArbitraryJavascript;
    id <VungleJSCommandDelegate><VungleMRAIDCommandDelegate> _delegate;
    CDUnknownBlockType _resultBlock;
    NSString *_command;
    NSDictionary *_parameters;
    UIWebView *_webView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *command; // @synthesize command=_command;
- (id)constructJavascriptExpression;
@property(nonatomic) __weak id <VungleJSCommandDelegate><VungleMRAIDCommandDelegate> delegate; // @synthesize delegate=_delegate;
- (void)execute;
- (void)finishWithErrors:(id)arg1;
- (id)initWithCommand:(id)arg1 parameters:(id)arg2 webView:(id)arg3;
- (id)initWithCommand:(id)arg1 parameters:(id)arg2 webView:(id)arg3 resultBlock:(CDUnknownBlockType)arg4;
@property(nonatomic) _Bool isArbitraryJavascript; // @synthesize isArbitraryJavascript=_isArbitraryJavascript;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;

@end

