//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface VungleMRAIDInterstitialViewController : UIViewController
{
    _Bool _playCommandEnabled;
    unsigned long long _orientationMask;
    UIViewController *_presenterController;
}

- (void).cxx_destruct;
- (void)didDismissInterstitialAd;
- (void)didPresentInterstitialAd;
- (void)disableRemoteCommandCenterControls:(id)arg1;
- (void)dismissInterstitialAdAnimated:(_Bool)arg1;
- (void)enableAVPlayerObservation;
- (id)init;
@property(nonatomic) unsigned long long orientationMask; // @synthesize orientationMask=_orientationMask;
@property(nonatomic) _Bool playCommandEnabled; // @synthesize playCommandEnabled=_playCommandEnabled;
- (_Bool)prefersStatusBarHidden;
- (void)presentIOS7TransparentController:(id)arg1 fromViewController:(id)arg2;
- (void)presentIOS8orHigherTransparentController:(id)arg1 fromViewController:(id)arg2;
- (void)presentInterstitialAdFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)presentViewController:(id)arg1 fromViewController:(id)arg2;
@property(retain, nonatomic) UIViewController *presenterController; // @synthesize presenterController=_presenterController;
- (void)restoreCommandCenterControls;
- (void)setupGUILayout;
- (_Bool)shouldAutorotate;
- (_Bool)shouldDisplayCloseButton;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)willDismissInterstitialAd;
- (void)willPresentInterstitialAd;

@end

