//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleMRAIDInterstitialViewController.h"

#import "VungleMRAIDControllerDelegate.h"

@class NSString, UIView, VungleInterstitialMRAIDAd, VungleMRAIDController, VungleNetworkManager, VunglePublisherInformation;

@interface VungleInternalMRAIDViewController : VungleMRAIDInterstitialViewController <VungleMRAIDControllerDelegate>
{
    id <VungleInterstitialAdDelegate> _delegate;
    VunglePublisherInformation *_publisherInformation;
    VungleInterstitialMRAIDAd *_ad;
    VungleMRAIDController *_MRAIDController;
    CDUnknownBlockType _completionBlock;
    UIView *_container;
    VungleNetworkManager *_networkManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) VungleMRAIDController *MRAIDController; // @synthesize MRAIDController=_MRAIDController;
@property(retain, nonatomic) VungleInterstitialMRAIDAd *ad; // @synthesize ad=_ad;
- (void)appDidBecomeActive:(id)arg1;
- (void)appWillEnterBackground:(id)arg1;
- (void)appWillEnterForeground:(id)arg1;
- (void)appWillResignActive:(id)arg1;
- (void)applyInterfaceOrientationCorrectionWithMask:(unsigned long long)arg1;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) __weak UIView *container; // @synthesize container=_container;
- (id)controllerToPresentModalAdView;
- (void)dealloc;
@property(nonatomic) __weak id <VungleInterstitialAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deviceOrientationChangeNotification:(id)arg1;
- (void)didPresentInterstitialAd;
- (void)didReceiveMemoryWarning;
- (id)initWithVungleMRAIDAd:(id)arg1 networkManager:(id)arg2;
- (void)loadAdWithCompletionBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
- (_Bool)prefersStatusBarHidden;
@property(copy, nonatomic) VunglePublisherInformation *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
- (void)setupAutoLayoutConstraintsForAdContainer:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)vungleMRAIDController:(id)arg1 didFailToLoadAd:(id)arg2 error:(id)arg3;
- (void)vungleMRAIDController:(id)arg1 didLoadAdInContainerView:(id)arg2;
- (void)vungleMRAIDController:(id)arg1 executeRequestWithTPATURLArray:(id)arg2;
- (void)vungleMRAIDController:(id)arg1 setOrientationPropertiesWithForceOrientationMask:(unsigned long long)arg2;
- (void)vungleMRAIDControllerDidCloseAdExperienceWithReportable:(id)arg1;
- (void)vungleMRAIDControllerIsEnteringBackgroundWithReportable:(id)arg1;
- (unsigned long long)vungleMRAIDControllerOrientationMask;
- (void)vungleMRAIDControllerSuccessfulView:(_Bool)arg1;
- (void)vungleMRAIDControllerWillCloseAdExperienceWithReportable:(id)arg1;
- (void)vungleMRAIDControllerWillStartAdExperienceWithReportable:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

