//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "VungleInterstitialAdDelegate.h"
#import "VungleRequestAdManagerDelegate.h"
#import "VungleRequestStreamingAdControllerDelegate.h"
#import "VungleSDKInitializerDelegate.h"
#import "VungleStreamingConfigurableDelegate.h"

@class NSDictionary, NSString, NSUserDefaults, UIViewController, VungleAdViewController, VungleCacheManager, VungleConfigController, VungleDeviceInformationProvider, VungleIDFVPermissionProvider, VungleInternalMRAIDViewController, VungleLogCoordinator, VungleNetworkManager, VungleNewRequestController, VunglePlayOptionsProvider, VunglePlayabilityCoordinator, VunglePublisherInformation, VungleReportAdController, VungleRequestAdController, VungleRequestStreamingAdController, VungleSDKInitializer, VungleSleepHandler, VungleURLBuilder, VungleVDUIDProvider;

@interface VungleSDK : NSObject <VungleRequestAdManagerDelegate, VungleRequestStreamingAdControllerDelegate, VungleStreamingConfigurableDelegate, VungleSDKInitializerDelegate, VungleInterstitialAdDelegate>
{
    _Bool _muted;
    _Bool _loggingEnabled;
    _Bool _isPlaying;
    _Bool _didStartup;
    _Bool _isSuccessfulAdView;
    _Bool _validCTAURLResolved;
    NSDictionary *_userData;
    id <VungleAssetLoader> _assetLoader;
    VungleNetworkManager *_networkManager;
    double _startTime;
    double _preventPlayUntilTime;
    id _playableEventTimer;
    UIViewController *_tmpViewController;
    NSUserDefaults *_defaults;
    VungleRequestAdController *_requestAdController;
    VungleConfigController *_configController;
    VungleNewRequestController *_createNewRequestController;
    VungleRequestStreamingAdController *_requestStreamingAdController;
    VungleReportAdController *_reportingController;
    VungleInternalMRAIDViewController *_vmraidController;
    VungleSDKInitializer *_SDKInitializer;
    VungleSleepHandler *_sleepHandler;
    VungleLogCoordinator *_logCoordinator;
    VunglePlayabilityCoordinator *_playabilityCoordinator;
    VunglePlayOptionsProvider *_currentPlayOptions;
    VungleVDUIDProvider *_VDUIDProvider;
    VungleDeviceInformationProvider *_deviceInformationProvider;
    VunglePublisherInformation *_publisherInformation;
    VungleIDFVPermissionProvider *_IDFVPermissionProvider;
    id <VungleSDKDelegate> _internalDelegate;
    VungleCacheManager *_cacheManager;
    VungleAdViewController *_currentAdViewController;
    NSString *_pluginName;
    unsigned long long _endTaskId;
    VungleURLBuilder *_urlBuilder;
}

+ (id)setupSDKWithAssetLoader:(id)arg1;
+ (id)sharedSDK;
- (void).cxx_destruct;
@property(retain, nonatomic) VungleIDFVPermissionProvider *IDFVPermissionProvider; // @synthesize IDFVPermissionProvider=_IDFVPermissionProvider;
@property(retain, nonatomic) VungleSDKInitializer *SDKInitializer; // @synthesize SDKInitializer=_SDKInitializer;
@property(retain, nonatomic) VungleVDUIDProvider *VDUIDProvider; // @synthesize VDUIDProvider=_VDUIDProvider;
- (void)appDidEnterBackground;
- (void)appWillEnterForeground;
@property(retain) id <VungleAssetLoader> assetLoader; // @synthesize assetLoader=_assetLoader;
- (void)attachLogger:(id)arg1;
@property(readonly, nonatomic) VungleCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
- (void)clearCache;
- (void)clearSleep;
@property(retain, nonatomic) VungleConfigController *configController; // @synthesize configController=_configController;
@property(retain, nonatomic) VungleNewRequestController *createNewRequestController; // @synthesize createNewRequestController=_createNewRequestController;
@property(retain, nonatomic) VungleAdViewController *currentAdViewController; // @synthesize currentAdViewController=_currentAdViewController;
@property(copy, nonatomic) VunglePlayOptionsProvider *currentPlayOptions; // @synthesize currentPlayOptions=_currentPlayOptions;
- (void)dealloc;
- (id)debugInfo;
@property(retain, nonatomic) NSUserDefaults *defaults; // @synthesize defaults=_defaults;
@property(retain) id <VungleSDKDelegate> delegate;
- (void)detachLogger:(id)arg1;
- (id)deviceInfo;
@property(retain, nonatomic) VungleDeviceInformationProvider *deviceInformationProvider; // @synthesize deviceInformationProvider=_deviceInformationProvider;
- (void)didDismissInterstitialAdViewControllerWithReportable:(id)arg1;
- (void)didFinishAdView:(id)arg1 withSuccess:(_Bool)arg2;
- (void)didGetIDFV:(id)arg1;
- (void)didGetIFA:(id)arg1;
- (void)didGetUserAgent:(id)arg1;
@property _Bool didStartup; // @synthesize didStartup=_didStartup;
@property(nonatomic) unsigned long long endTaskId; // @synthesize endTaskId=_endTaskId;
- (id)initWithAssetLoader:(id)arg1;
- (id)initWithAssetLoader:(id)arg1 networkManager:(id)arg2 defaults:(id)arg3;
- (void)initialRequestAd;
@property(retain, nonatomic) id <VungleSDKDelegate> internalDelegate; // @synthesize internalDelegate=_internalDelegate;
- (_Bool)isAdPlayable;
- (_Bool)isCachedAdAvailable;
@property _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) _Bool isSuccessfulAdView; // @synthesize isSuccessfulAdView=_isSuccessfulAdView;
- (void)log:(id)arg1;
@property(retain, nonatomic) VungleLogCoordinator *logCoordinator; // @synthesize logCoordinator=_logCoordinator;
@property _Bool loggingEnabled; // @synthesize loggingEnabled=_loggingEnabled;
@property _Bool muted; // @synthesize muted=_muted;
@property(retain, nonatomic) VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
- (_Bool)playAd:(id)arg1 error:(id *)arg2;
- (_Bool)playAd:(id)arg1 withOptions:(id)arg2 error:(id *)arg3;
@property(retain, nonatomic) VunglePlayabilityCoordinator *playabilityCoordinator; // @synthesize playabilityCoordinator=_playabilityCoordinator;
@property(copy) id playableEventTimer; // @synthesize playableEventTimer=_playableEventTimer;
@property(copy, nonatomic) NSString *pluginName; // @synthesize pluginName=_pluginName;
- (_Bool)presentAd:(id)arg1 withViewController:(id)arg2 playOptions:(id)arg3;
@property double preventPlayUntilTime; // @synthesize preventPlayUntilTime=_preventPlayUntilTime;
@property(retain, nonatomic) VunglePublisherInformation *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
@property(retain, nonatomic) VungleReportAdController *reportingController; // @synthesize reportingController=_reportingController;
- (void)requestAd;
@property(retain, nonatomic) VungleRequestAdController *requestAdController; // @synthesize requestAdController=_requestAdController;
- (void)requestAdController:(id)arg1 didFinishWithError:(id)arg2;
@property(retain, nonatomic) VungleRequestStreamingAdController *requestStreamingAdController; // @synthesize requestStreamingAdController=_requestStreamingAdController;
- (void)sendNewRequest;
- (void)sendRequest:(id)arg1;
- (void)sendSessionEndRequest;
- (void)setAPIEndpoint:(id)arg1;
- (void)setHTTPHeaderPair:(id)arg1;
- (void)setPluginName:(id)arg1 version:(id)arg2;
@property(retain, nonatomic) VungleSleepHandler *sleepHandler; // @synthesize sleepHandler=_sleepHandler;
@property double startTime; // @synthesize startTime=_startTime;
@property UIViewController *tmpViewController; // @synthesize tmpViewController=_tmpViewController;
@property(retain, nonatomic) VungleURLBuilder *urlBuilder; // @synthesize urlBuilder=_urlBuilder;
@property(retain) NSDictionary *userData; // @synthesize userData=_userData;
@property(nonatomic) _Bool validCTAURLResolved; // @synthesize validCTAURLResolved=_validCTAURLResolved;
@property(retain, nonatomic) VungleInternalMRAIDViewController *vmraidController; // @synthesize vmraidController=_vmraidController;
- (void)setup;
- (void)setupEndpointControllersWithURLBuilder:(id)arg1 networkManager:(id)arg2 cacheManager:(id)arg3 defaults:(id)arg4;
- (void)setupInitialOperationChain;
- (void)setupReactionToBundleAdChange;
- (void)startWithAppId:(id)arg1;
- (void)startWithAppId:(id)arg1 networkManager:(id)arg2;
- (void)streamingAdControllerDidValidateCTA:(_Bool)arg1;
- (void)streamingAdControllerShouldPlayAd:(id)arg1;
- (void)streamingSettingsUpdateShouldStream:(_Bool)arg1 streamingRequestTimeout:(double)arg2 bufferingTimeout:(double)arg3;
- (void)updateCacheWithSDKVersion:(id)arg1;
- (void)updateCachedReportable:(id)arg1;
- (void)updateControllersWithPublisherInformation;
- (void)willBackgroundAdViewControllerWithReportable:(id)arg1;
- (void)willDismissInterstitialAdViewControllerWithReportable:(id)arg1;
- (void)willPresentInterstitialAdViewControllerWithReportable:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

