//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "VungleLoggable.h"

@class NSDate, NSDictionary, NSString;

@interface VungleLogEntry : NSObject <NSCoding, VungleLoggable>
{
    NSString *_message;
    long long _level;
    NSDate *_creationDate;
    NSDate *_submissionDate;
    NSDictionary *_deviceInformation;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(copy, nonatomic) NSDictionary *deviceInformation; // @synthesize deviceInformation=_deviceInformation;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMessage:(id)arg1 level:(long long)arg2;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSDate *submissionDate; // @synthesize submissionDate=_submissionDate;
- (id)toDictionary;
- (id)toLog;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

