//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSURL, VungleAd, VungleCacheManager, VungleNetworkManager, VunglePublisherInformation, VungleSleepHandler;

@interface VungleRequestAdController : NSObject
{
    _Bool _requestingAd;
    int _numberOfTimeouts;
    VunglePublisherInformation *_publisherInformation;
    id <VungleRequestAdManagerDelegate> _delegate;
    NSArray *_backoffArray;
    unsigned long long _currentBackoffIndex;
    double _sleepUntil;
    VungleCacheManager *_cacheManager;
    VungleNetworkManager *_networkManager;
    VungleAd *_bundle;
    NSURL *_URL;
    VungleSleepHandler *_sleepHandler;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void)attemptToGetNewAdAndNotifyDelegateWithError:(id)arg1;
@property(retain, nonatomic) NSArray *backoffArray; // @synthesize backoffArray=_backoffArray;
@property(retain, nonatomic) VungleAd *bundle; // @synthesize bundle=_bundle;
@property(nonatomic) __weak VungleCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
- (void)clearSleep;
@property(nonatomic) unsigned long long currentBackoffIndex; // @synthesize currentBackoffIndex=_currentBackoffIndex;
@property(nonatomic) __weak id <VungleRequestAdManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getPreferenceValueForKey:(id)arg1;
- (void)handleInterstitialMRAIDAd:(id)arg1 preparer:(id)arg2;
- (void)handleVungleLegacyAd:(id)arg1 fromBundleMeta:(id)arg2;
- (id)init;
- (id)initWithBaseURL:(id)arg1 networkManager:(id)arg2 sleepHandler:(id)arg3 cacheManager:(id)arg4;
- (_Bool)isBodyFormatValid:(id)arg1;
- (_Bool)isBundleExpired:(id)arg1 referenceDate:(id)arg2;
- (_Bool)isResponseExpired:(id)arg1;
- (_Bool)isResponseSuccessful:(id)arg1 error:(id *)arg2;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
@property int numberOfTimeouts; // @synthesize numberOfTimeouts=_numberOfTimeouts;
- (_Bool)performSleep:(id)arg1;
- (void)processValidResponse:(id)arg1;
@property(copy, nonatomic) VunglePublisherInformation *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
- (id)requestAdOperationWithDeviceInfo:(id)arg1;
- (void)requestAdWithBackoffArray:(id)arg1 currentBackoffIndex:(unsigned long long *)arg2;
- (void)requestAdWithDeviceInfo:(id)arg1 delegate:(id)arg2;
@property _Bool requestingAd; // @synthesize requestingAd=_requestingAd;
- (void)resetInterstitialMRAIDAd:(id)arg1;
- (void)setPreferenceValue:(id)arg1 forKey:(id)arg2;
@property(retain, nonatomic) VungleSleepHandler *sleepHandler; // @synthesize sleepHandler=_sleepHandler;
@property(nonatomic) double sleepUntil; // @synthesize sleepUntil=_sleepUntil;
- (_Bool)validateRequestAd:(id)arg1 withError:(id *)arg2;

@end

