//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"
#import "VungleNativeCommandHandlerDelegate.h"

@class NSString, UIWebView, VungleNativeCommandHandler;

@interface VungleMRAIDBridge : NSObject <UIWebViewDelegate, VungleNativeCommandHandlerDelegate>
{
    id <VungleMRAIDBridgeDelegate> _delegate;
    id <VungleMRAIDReportBuilderProtocol> _reportBuilderDelegate;
    UIWebView *_webView;
    VungleNativeCommandHandler *_commandHandler;
}

- (void).cxx_destruct;
- (id)MRAIDJSInjectionError;
@property(retain, nonatomic) VungleNativeCommandHandler *commandHandler; // @synthesize commandHandler=_commandHandler;
- (void)commandHandler:(id)arg1 handleErrorCode:(id)arg2;
- (void)commandHandler:(id)arg1 handleMRAIDCustomClose:(long long)arg2;
- (void)commandHandler:(id)arg1 handleMRAIDOpenCallForURL:(id)arg2;
- (void)commandHandler:(id)arg1 handleMRAIDSetOrientationPropertiesWithForceOrientationMask:(unsigned long long)arg2;
- (void)commandHandler:(id)arg1 handleSuccessfulView:(_Bool)arg2;
- (void)commandHandler:(id)arg1 handleTPAT:(id)arg2;
- (void)commandHandler:(id)arg1 handleUIAction:(id)arg2;
- (void)commandHandler:(id)arg1 handleUIAction:(id)arg2 withValue:(id)arg3;
- (void)commandHandlerHandleMRAIDClose:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <VungleMRAIDBridgeDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dispatchPropertiesChangeWithDictionary:(id)arg1;
- (CDUnknownBlockType)finishResultBlock;
- (id)initWithWebView:(id)arg1 delegate:(id)arg2;
- (void)loadHTMLFileWithURL:(id)arg1 cacheableReplacements:(id)arg2 nonCacheableReplacements:(id)arg3 viewProperties:(id)arg4;
- (id)localAdTemplateRequestErrorWithError:(id)arg1;
- (id)propertiesChangeJSExpressionWithProperties:(id)arg1;
- (id)readyJSExpressionWithCacheableReplacements:(id)arg1 nonCacheableReplacements:(id)arg2;
@property(nonatomic) __weak id <VungleMRAIDReportBuilderProtocol> reportBuilderDelegate; // @synthesize reportBuilderDelegate=_reportBuilderDelegate;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

