//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString, VungleAd, VungleRequestAdController;

@protocol VungleRequestAdManagerDelegate <NSObject>
- (void)log:(NSString *)arg1;
- (void)requestAd;
- (void)requestAdController:(VungleRequestAdController *)arg1 didFinishWithError:(NSError *)arg2;
@property(nonatomic) _Bool validCTAURLResolved;

@optional
- (void)didPrepareAd:(VungleAd *)arg1 error:(NSError *)arg2;
- (void)willPrepareAd:(VungleAd *)arg1;
@end

