//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VungleCacheManager, VungleNetworkManager, VunglePublisherInformation;

@interface VungleRequestStreamingAdController : NSObject
{
    _Bool _internalShouldStream;
    VunglePublisherInformation *_publisherInformation;
    VungleNetworkManager *_networkManager;
    VungleCacheManager *_cacheManager;
    id <VungleRequestStreamingAdControllerDelegate> _delegate;
    double _internalRequestStreamingTimeout;
}

- (void).cxx_destruct;
@property(nonatomic) __weak VungleCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
- (void)configureOperation:(id)arg1 playOptions:(id)arg2 publisherInformation:(id)arg3 deviceInformation:(id)arg4;
- (id)createStreamingAdWithJSONResponse:(id)arg1 networkResponse:(id)arg2;
@property(nonatomic) __weak id <VungleRequestStreamingAdControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleRequestStreamingAd:(id)arg1;
- (id)initWithNetworkManager:(id)arg1 cacheManager:(id)arg2 publisherInformation:(id)arg3 delegate:(id)arg4;
@property(nonatomic) double internalRequestStreamingTimeout; // @synthesize internalRequestStreamingTimeout=_internalRequestStreamingTimeout;
@property(nonatomic) _Bool internalShouldStream; // @synthesize internalShouldStream=_internalShouldStream;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
@property(copy, nonatomic) VunglePublisherInformation *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
- (void)sendStreamingAdRequestWithURL:(id)arg1 playOptions:(id)arg2 deviceInformation:(id)arg3;
- (void)setShouldStream:(_Bool)arg1;
- (void)setStreamingRequestTimeout:(double)arg1;

@end

