//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSUserDefaults;

@interface VungleIDFVPermissionProvider : NSObject
{
    NSUserDefaults *_defaults;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSUserDefaults *defaults; // @synthesize defaults=_defaults;
- (id)initWithDefaults:(id)arg1;
- (void)setShouldCollectIDFV:(_Bool)arg1;
- (_Bool)shouldCollectIDFV;

@end

