//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface VungleURLBuilder : NSObject
{
    NSString *_basePath;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *basePath; // @synthesize basePath=_basePath;
- (id)buildURLWithPath:(id)arg1 isAbsolute:(_Bool)arg2;
- (id)configString;
- (id)configURL;
- (id)initWithDefaults:(id)arg1;
- (id)reportAdString;
- (id)reportAdURL;
- (id)requestAdString;
- (id)requestAdURL;
- (id)requestStreamingAdString;
- (id)requestStreamingAdURL;
- (id)sessionEndString;
- (id)sessionEndURL;
- (id)vungleNewString;
- (id)vungleNewURL;

@end

