//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSURL;

@interface VungleNetworkResponse : NSObject
{
    NSData *_data;
    long long _statusCode;
    NSError *_error;
    NSURL *_requestURL;
    NSURL *_localDownloadURL;
    unsigned long long _attempts;
}

+ (id)vungleNetworkResponseWithNSHTTPURLResponse:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long attempts; // @synthesize attempts=_attempts;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (id)decoratedDictionary:(id *)arg1;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
- (_Bool)isValidCTAURLResolved;
@property(copy, nonatomic) NSURL *localDownloadURL; // @synthesize localDownloadURL=_localDownloadURL;
@property(copy, nonatomic) NSURL *requestURL; // @synthesize requestURL=_requestURL;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;

@end

