//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VungleAd, VungleNetworkManager, VungleOperationQueue;

@interface VungleAdPreparer : NSObject
{
    VungleOperationQueue *_queue;
    VungleNetworkManager *_networkManager;
    VungleAd *_adBeingPrepared;
}

+ (id)buildErrorWithVungleMRAIDAd:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) VungleAd *adBeingPrepared; // @synthesize adBeingPrepared=_adBeingPrepared;
- (id)initWithNetworkManager:(id)arg1;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
- (void)prepareAd:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)prepareAdOperationWithPrecedingOperations:(id)arg1;
@property(retain, nonatomic) VungleOperationQueue *queue; // @synthesize queue=_queue;

@end

