//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADAdNetworkExtras.h"

@class NSString;

@interface VungleAdNetworkExtras : NSObject <GADAdNetworkExtras>
{
    _Bool _muted;
    NSString *_userId;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

